{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageGroupPosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessageGroupPosition","text":"MessageGroupPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelcontentbasemessagecell\/configure(_:hidedateview:groupposition:isoverlay:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelcontentbasemessagecell\/configure(_:hidedateview:groupposition:isoverlay:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelContentBaseMessageCell\/configure(_:hideDateView:groupPosition:isOverlay:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageGroupPosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessageGroupPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"configure(_:hideDateView:groupPosition:isOverlay:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelContentBaseMessageCell(im)configure:hideDateView:groupPosition:isOverlay:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"configure:hideDateView:groupPosition:isOverlay:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelContentBaseMessageCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelContentBaseMessageCell":{"role":"symbol","title":"SBUOpenChannelContentBaseMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelContentBaseMessageCell"}],"abstract":[{"type":"text","text":"It is a base class used in message cell with contents."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelContentBaseMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelContentBaseMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcontentbasemessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessageGroupPosition":{"role":"symbol","title":"MessageGroupPosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageGroupPosition"}],"abstract":[{"type":"text","text":"This is an enumeration used to select the message position in group messages."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageGroupPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageGroupPosition"}],"url":"\/documentation\/sendbirduikit\/messagegroupposition"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelContentBaseMessageCell/configure(_:hideDateView:groupPosition:isOverlay:)":{"role":"symbol","title":"configure(_:hideDateView:groupPosition:isOverlay:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageGroupPosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessageGroupPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelContentBaseMessageCell\/configure(_:hideDateView:groupPosition:isOverlay:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configure:hideDateView:groupPosition:isOverlay:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcontentbasemessagecell\/configure(_:hidedateview:groupposition:isoverlay:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"configure:hideDateView:groupPosition:isOverlay:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configure:hideDateView:groupPosition:isOverlay:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"configure:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDBaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideDateView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"hideDateView"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupPosition:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageGroupPosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessageGroupPosition","text":"MessageGroupPosition"},{"kind":"text","text":")"},{"kind":"internalParam","text":"groupPosition"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOverlay:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isOverlay"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelContentBaseMessageCell\/title","value":"SBUOpenChannelContentBaseMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelContentBaseMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelContentBaseMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageGroupPosition\/title","value":"MessageGroupPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageGroupPosition\/fragments","value":[{"kind":"identifier","text":"MessageGroupPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelContentBaseMessageCell~1configure(_:hideDateView:groupPosition:isOverlay:)\/title","value":"configure:hideDateView:groupPosition:isOverlay:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelContentBaseMessageCell~1configure(_:hideDateView:groupPosition:isOverlay:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configure:hideDateView:groupPosition:isOverlay:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}