{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessagePosition","text":"MessagePosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageGroupPosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessageGroupPosition","text":"MessageGroupPosition"},{"kind":"text","text":" = .none, "},{"kind":"externalParam","text":"receiptState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState","preciseIdentifier":"c:@M@SendbirdUIKit@E@SBUMessageReceiptState","text":"SBUMessageReceiptState"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Message object"}]}]},{"name":"position","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Cell position (left \/ right \/ center)"}]}]},{"name":"hideDateView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Hide or expose date information"}]}]},{"name":"receiptState","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ReadReceipt state"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasemessagecell\/configure(message:position:hidedateview:groupposition:receiptstate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasemessagecell\/configure(message:position:hidedateview:groupposition:receiptstate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/configure(message:position:hideDateView:groupPosition:receiptState:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function configure a cell using informations."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"configureWithMessage:position:hideDateView:groupPosition:receiptState:"}],"role":"symbol","title":"configure(message:position:hideDateView:groupPosition:receiptState:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessagePosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageGroupPosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessageGroupPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"receiptState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUMessageReceiptState","preciseIdentifier":"c:@M@SendbirdUIKit@E@SBUMessageReceiptState"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseMessageCell(im)configureWithMessage:position:hideDateView:groupPosition:receiptState:","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState":{"role":"symbol","title":"SBUMessageReceiptState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageReceiptState"}],"abstract":[{"type":"text","text":"This is an enumeration to message receipt state."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageReceiptState"}],"url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell":{"role":"symbol","title":"SBUBaseMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/configure(message:position:hideDateView:groupPosition:receiptState:)":{"deprecated":true,"role":"symbol","title":"configure(message:position:hideDateView:groupPosition:receiptState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessagePosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageGroupPosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessageGroupPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"receiptState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUMessageReceiptState","preciseIdentifier":"c:@M@SendbirdUIKit@E@SBUMessageReceiptState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function configure a cell using informations."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/configure(message:position:hideDateView:groupPosition:receiptState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configureWithMessage:position:hideDateView:groupPosition:receiptState:"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/configure(message:position:hidedateview:groupposition:receiptstate:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessagePosition":{"role":"symbol","title":"MessagePosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePosition"}],"abstract":[{"type":"text","text":"This is an enumeration used to select the message position."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePosition"}],"url":"\/documentation\/sendbirduikit\/messageposition"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessageGroupPosition":{"role":"symbol","title":"MessageGroupPosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageGroupPosition"}],"abstract":[{"type":"text","text":"This is an enumeration used to select the message position in group messages."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageGroupPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageGroupPosition"}],"url":"\/documentation\/sendbirduikit\/messagegroupposition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"configureWithMessage:position:hideDateView:groupPosition:receiptState:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configureWithMessage:position:hideDateView:groupPosition:receiptState:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"configureWithMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDBaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"position:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessagePosition","text":"MessagePosition"},{"kind":"text","text":")"},{"kind":"internalParam","text":"position"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideDateView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"hideDateView"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupPosition:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageGroupPosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessageGroupPosition","text":"MessageGroupPosition"},{"kind":"text","text":")"},{"kind":"internalParam","text":"groupPosition"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiptState:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState","preciseIdentifier":"c:@M@SendbirdUIKit@E@SBUMessageReceiptState","text":"SBUMessageReceiptState"},{"kind":"text","text":")"},{"kind":"internalParam","text":"receiptState"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState\/title","value":"SBUMessageReceiptState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState\/fragments","value":[{"kind":"identifier","text":"SBUMessageReceiptState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell\/title","value":"SBUBaseMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUBaseMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1configure(message:position:hideDateView:groupPosition:receiptState:)\/title","value":"configureWithMessage:position:hideDateView:groupPosition:receiptState:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1configure(message:position:hideDateView:groupPosition:receiptState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configureWithMessage:position:hideDateView:groupPosition:receiptState:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessagePosition\/title","value":"MessagePosition"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessagePosition\/fragments","value":[{"kind":"identifier","text":"MessagePosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageGroupPosition\/title","value":"MessageGroupPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageGroupPosition\/fragments","value":[{"kind":"identifier","text":"MessageGroupPosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}