{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupActions"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuviewlifecycle\/setupactions()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuviewlifecycle\/setupactions()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle\/setupActions()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function handles the initialization of actions."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setupActions"}],"role":"symbol","title":"setupActions()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupActions"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(pl)SBUViewLifeCycle(im)setupActions","required":true,"modules":[{"name":"SendbirdUIKit"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUViewLifeCycle":{"role":"symbol","title":"SBUViewLifeCycle","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUViewLifeCycle"}],"abstract":[{"type":"text","text":"The protocol to manage the life cylce of some views. It defines setting views, styles, auto layouts and actions."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUViewLifeCycle"}],"url":"\/documentation\/sendbirduikit\/sbuviewlifecycle"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUViewLifeCycle/setupActions()":{"navigatorTitle":[{"kind":"identifier","text":"setupActions"}],"role":"symbol","title":"setupActions()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupActions"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of actions."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle\/setupActions()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirduikit\/sbuviewlifecycle\/setupactions()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setupActions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupActions"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setupActions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/title","value":"SBUViewLifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/fragments","value":[{"kind":"identifier","text":"SBUViewLifeCycle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle~1setupActions()\/title","value":"setupActions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle~1setupActions()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupActions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}