{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOpenChannelModuleDidSelectChannelImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"profileInputComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelModule","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC","text":"SBUCreateOpenChannelModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelModule\/ProfileInput","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC12ProfileInputC","text":"ProfileInput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needRemoveItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"profileInputComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUCreateOpenChannelModule.ProfileInput"},{"type":"text","text":" object."}]}]},{"name":"needRemoveItem","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If the image is already set, set the needRemoveItem to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"and activate the deletion option."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller\/createopenchannelmoduledidselectchannelimage(_:needremoveitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller\/createopenchannelmoduledidselectchannelimage(_:needremoveitem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController\/createOpenChannelModuleDidSelectChannelImage(_:needRemoveItem:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the selected channel image in "},{"type":"codeVoice","code":"profileInputComponent"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOpenChannelModuleDidSelectChannelImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUCreateOpenChannelModule","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ProfileInput","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC12ProfileInputC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needRemoveItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"createOpenChannelModuleDidSelectChannelImage(_:needRemoveItem:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUCreateOpenChannelViewController(im)createOpenChannelModuleDidSelectChannelImage:needRemoveItem:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"createOpenChannelModuleDidSelectChannelImage:needRemoveItem:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateOpenChannelViewController":{"role":"symbol","title":"SBUCreateOpenChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateOpenChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateOpenChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateOpenChannelViewController/createOpenChannelModuleDidSelectChannelImage(_:needRemoveItem:)":{"role":"symbol","title":"createOpenChannelModuleDidSelectChannelImage(_:needRemoveItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOpenChannelModuleDidSelectChannelImage"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUCreateOpenChannelModule","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ProfileInput","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC12ProfileInputC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needRemoveItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the selected channel image in "},{"type":"codeVoice","code":"profileInputComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController\/createOpenChannelModuleDidSelectChannelImage(_:needRemoveItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createOpenChannelModuleDidSelectChannelImage:needRemoveItem:"}],"url":"\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller\/createopenchannelmoduledidselectchannelimage(_:needremoveitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateOpenChannelModule":{"role":"symbol","title":"SBUCreateOpenChannelModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateOpenChannelModule"}],"abstract":[{"type":"text","text":"The class that represents the module for creating a new open channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateOpenChannelModule"}],"url":"\/documentation\/sendbirduikit\/sbucreateopenchannelmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateOpenChannelModule/ProfileInput":{"role":"symbol","title":"SBUCreateOpenChannelModule.ProfileInput","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileInput"}],"abstract":[{"type":"text","text":"A module component that represent the profile input of "},{"type":"codeVoice","code":"SBUCreateOpenChannelModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelModule\/ProfileInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProfileInput"}],"url":"\/documentation\/sendbirduikit\/sbucreateopenchannelmodule\/profileinput"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createOpenChannelModuleDidSelectChannelImage:needRemoveItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createOpenChannelModuleDidSelectChannelImage:needRemoveItem:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"createOpenChannelModuleDidSelectChannelImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUCreateOpenChannelModuleProfileInput","preciseIdentifier":"c:objc(cs)SBUCreateOpenChannelModuleProfileInput"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"profileInputComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"needRemoveItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"needRemoveItem"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController\/title","value":"SBUCreateOpenChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUCreateOpenChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController~1createOpenChannelModuleDidSelectChannelImage(_:needRemoveItem:)\/title","value":"createOpenChannelModuleDidSelectChannelImage:needRemoveItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController~1createOpenChannelModuleDidSelectChannelImage(_:needRemoveItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createOpenChannelModuleDidSelectChannelImage:needRemoveItem:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}