{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"profileInputComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelModule","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC","text":"SBUCreateOpenChannelModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelModule\/ProfileInput","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC12ProfileInputC","text":"ProfileInput"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller\/profileinputcomponent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller\/profileinputcomponent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController\/profileInputComponent","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"profileInputComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUCreateOpenChannelModule","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ProfileInput","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC12ProfileInputC"},{"kind":"text","text":"?"}],"title":"profileInputComponent","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUCreateOpenChannelViewController(py)profileInputComponent","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"profileInputComponent"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateOpenChannelModule":{"role":"symbol","title":"SBUCreateOpenChannelModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateOpenChannelModule"}],"abstract":[{"type":"text","text":"The class that represents the module for creating a new open channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateOpenChannelModule"}],"url":"\/documentation\/sendbirduikit\/sbucreateopenchannelmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateOpenChannelModule/ProfileInput":{"role":"symbol","title":"SBUCreateOpenChannelModule.ProfileInput","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProfileInput"}],"abstract":[{"type":"text","text":"A module component that represent the profile input of "},{"type":"codeVoice","code":"SBUCreateOpenChannelModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelModule\/ProfileInput","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProfileInput"}],"url":"\/documentation\/sendbirduikit\/sbucreateopenchannelmodule\/profileinput"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateOpenChannelViewController":{"role":"symbol","title":"SBUCreateOpenChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateOpenChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateOpenChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateOpenChannelViewController/profileInputComponent":{"role":"symbol","title":"profileInputComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"profileInputComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUCreateOpenChannelModule","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ProfileInput","preciseIdentifier":"s:13SendbirdUIKit26SBUCreateOpenChannelModuleC12ProfileInputC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController\/profileInputComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"profileInputComponent"}],"url":"\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller\/profileinputcomponent"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"profileInputComponent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"profileInputComponent"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBUCreateOpenChannelModuleProfileInput","preciseIdentifier":"c:objc(cs)SBUCreateOpenChannelModuleProfileInput"},{"kind":"text","text":" * "},{"kind":"identifier","text":"profileInputComponent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController\/title","value":"SBUCreateOpenChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUCreateOpenChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController~1profileInputComponent\/title","value":"profileInputComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController~1profileInputComponent\/fragments","value":[{"kind":"identifier","text":"profileInputComponent"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}