{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showChannelImagePicker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MediaResourceType","preciseIdentifier":"c:@M@SendbirdUIKit@E@MediaResourceType","text":"MediaResourceType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Media resource type ("},{"type":"codeVoice","code":"MediaResourceType"},{"type":"text","text":")"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller\/showchannelimagepicker(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller\/showchannelimagepicker(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController\/showChannelImagePicker(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function shows image picker for changing channel image."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showChannelImagePicker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MediaResourceType","preciseIdentifier":"c:@M@SendbirdUIKit@E@MediaResourceType"},{"kind":"text","text":")"}],"title":"showChannelImagePicker(with:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUCreateOpenChannelViewController(im)showChannelImagePickerWith:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"showChannelImagePickerWith:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateOpenChannelViewController/showChannelImagePicker(with:)":{"role":"symbol","title":"showChannelImagePicker(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showChannelImagePicker"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MediaResourceType","preciseIdentifier":"c:@M@SendbirdUIKit@E@MediaResourceType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function shows image picker for changing channel image."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController\/showChannelImagePicker(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showChannelImagePickerWith:"}],"url":"\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller\/showchannelimagepicker(with:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MediaResourceType":{"role":"symbol","title":"MediaResourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaResourceType"}],"abstract":[{"type":"text","text":"This is an enumeration used to select a media resource type."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MediaResourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MediaResourceType"}],"url":"\/documentation\/sendbirduikit\/mediaresourcetype"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateOpenChannelViewController":{"role":"symbol","title":"SBUCreateOpenChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateOpenChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateOpenChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateOpenChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbucreateopenchannelviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showChannelImagePickerWith:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showChannelImagePickerWith:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showChannelImagePickerWith:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MediaResourceType","preciseIdentifier":"c:@M@SendbirdUIKit@E@MediaResourceType","text":"MediaResourceType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController~1showChannelImagePicker(with:)\/title","value":"showChannelImagePickerWith:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController~1showChannelImagePicker(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showChannelImagePickerWith:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MediaResourceType\/title","value":"MediaResourceType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MediaResourceType\/fragments","value":[{"kind":"identifier","text":"MediaResourceType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController\/title","value":"SBUCreateOpenChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateOpenChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUCreateOpenChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}