{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbumessageinputview\/layoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbumessageinputview\/layoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputView\/layoutSubviews()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Lays out subviews and set up styles for SendbirdUIKit."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"title":"layoutSubviews()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUMessageInputView(im)layoutSubviews","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputView"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputView/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Lays out subviews and set up styles for SendbirdUIKit."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputView\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/sendbirduikit\/sbumessageinputview\/layoutsubviews()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputView":{"role":"symbol","title":"SBUMessageInputView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageInputView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageInputView"}],"url":"\/documentation\/sendbirduikit\/sbumessageinputview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"layoutSubviews"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputView~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputView~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputView\/title","value":"SBUMessageInputView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputView\/fragments","value":[{"kind":"identifier","text":"SBUMessageInputView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}