{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClickNewMessageInfo"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbunewmessageinfo\/onclicknewmessageinfo()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbunewmessageinfo\/onclicknewmessageinfo()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUNewMessageInfo\/onClickNewMessageInfo()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClickNewMessageInfo"},{"kind":"text","text":"()"}],"title":"onClickNewMessageInfo()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUNewMessageInfo(im)onClickNewMessageInfo","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"onClickNewMessageInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUNewMessageInfo"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUNewMessageInfo/onClickNewMessageInfo()":{"role":"symbol","title":"onClickNewMessageInfo()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClickNewMessageInfo"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUNewMessageInfo\/onClickNewMessageInfo()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onClickNewMessageInfo"}],"url":"\/documentation\/sendbirduikit\/sbunewmessageinfo\/onclicknewmessageinfo()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUNewMessageInfo":{"role":"symbol","title":"SBUNewMessageInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUNewMessageInfo"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUNewMessageInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUNewMessageInfo"}],"url":"\/documentation\/sendbirduikit\/sbunewmessageinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onClickNewMessageInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onClickNewMessageInfo"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onClickNewMessageInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUNewMessageInfo~1onClickNewMessageInfo()\/title","value":"onClickNewMessageInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUNewMessageInfo~1onClickNewMessageInfo()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onClickNewMessageInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUNewMessageInfo\/title","value":"SBUNewMessageInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUNewMessageInfo\/fragments","value":[{"kind":"identifier","text":"SBUNewMessageInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}