{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseFileContentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseFileContentView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseFileContentView","text":"SBUBaseFileContentView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelfilemessagecell\/basefilecontentview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelfilemessagecell\/basefilecontentview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelFileMessageCell\/baseFileContentView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseFileContentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUBaseFileContentView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseFileContentView"}],"title":"baseFileContentView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelFileMessageCell(py)baseFileContentView","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"baseFileContentView"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelFileMessageCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelFileMessageCell/baseFileContentView":{"role":"symbol","title":"baseFileContentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseFileContentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUBaseFileContentView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseFileContentView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelFileMessageCell\/baseFileContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseFileContentView"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelfilemessagecell\/basefilecontentview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelFileMessageCell":{"role":"symbol","title":"SBUOpenChannelFileMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelFileMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelFileMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelFileMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelfilemessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseFileContentView":{"role":"symbol","title":"SBUBaseFileContentView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseFileContentView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseFileContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseFileContentView"}],"url":"\/documentation\/sendbirduikit\/sbubasefilecontentview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"baseFileContentView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"baseFileContentView"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseFileContentView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseFileContentView","text":"SBUBaseFileContentView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"baseFileContentView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelFileMessageCell~1baseFileContentView\/title","value":"baseFileContentView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelFileMessageCell~1baseFileContentView\/fragments","value":[{"kind":"identifier","text":"baseFileContentView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelFileMessageCell\/title","value":"SBUOpenChannelFileMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelFileMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelFileMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseFileContentView\/title","value":"SBUBaseFileContentView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseFileContentView\/fragments","value":[{"kind":"identifier","text":"SBUBaseFileContentView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}