{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelfilemessagecell\/filemessage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelfilemessagecell\/filemessage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelFileMessageCell\/fileMessage","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":"?"}],"title":"fileMessage","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelFileMessageCell(py)fileMessage","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"fileMessage"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelFileMessageCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelFileMessageCell":{"role":"symbol","title":"SBUOpenChannelFileMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelFileMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelFileMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelFileMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelfilemessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelFileMessageCell/fileMessage":{"role":"symbol","title":"fileMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelFileMessageCell\/fileMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileMessage"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelfilemessagecell\/filemessage"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fileMessage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fileMessage"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBDFileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"fileMessage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelFileMessageCell\/title","value":"SBUOpenChannelFileMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelFileMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelFileMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelFileMessageCell~1fileMessage\/title","value":"fileMessage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelFileMessageCell~1fileMessage\/fragments","value":[{"kind":"identifier","text":"fileMessage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}