{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionViewLayout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuselectablephotoviewcontroller\/collectionview(_:layout:sizeforitemat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuselectablephotoviewcontroller\/collectionview(_:layout:sizeforitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewController\/collectionView(_:layout:sizeForItemAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UICollectionViewDelegateFlowLayout.collectionView(_:layout:sizeForItemAt:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"title":"collectionView(_:layout:sizeForItemAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUSelectablePhotoViewController(im)collectionView:layout:sizeForItemAtIndexPath:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewController\/UICollectionViewDelegateFlowLayout-Implementations"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUSelectablePhotoViewController":{"role":"symbol","title":"SBUSelectablePhotoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUSelectablePhotoViewController"}],"abstract":[{"type":"text","text":"The view controller that shows the selected accessible photos and videos."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUSelectablePhotoViewController"}],"url":"\/documentation\/sendbirduikit\/sbuselectablephotoviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUSelectablePhotoViewController/UICollectionViewDelegateFlowLayout-Implementations":{"role":"collectionGroup","title":"UICollectionViewDelegateFlowLayout Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewController\/UICollectionViewDelegateFlowLayout-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/sbuselectablephotoviewcontroller\/uicollectionviewdelegateflowlayout-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUSelectablePhotoViewController/collectionView(_:layout:sizeForItemAt:)":{"role":"symbol","title":"collectionView(_:layout:sizeForItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewController\/collectionView(_:layout:sizeForItemAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}],"url":"\/documentation\/sendbirduikit\/sbuselectablephotoviewcontroller\/collectionview(_:layout:sizeforitemat:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collectionView"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collectionViewLayout"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeForItemAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSelectablePhotoViewController\/title","value":"SBUSelectablePhotoViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSelectablePhotoViewController\/fragments","value":[{"kind":"identifier","text":"SBUSelectablePhotoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSelectablePhotoViewController~1collectionView(_:layout:sizeForItemAt:)\/title","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSelectablePhotoViewController~1collectionView(_:layout:sizeForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}