{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"externalParam","text":"photoCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUPhotoCollectionViewCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUPhotoCollectionViewCell","text":"SBUPhotoCollectionViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nib"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channelCell","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Customized channel cell"}]}]},{"name":"nib","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"nib information. If the value is nil, the nib file is not used."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.2.6"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuselectablephotoviewcontroller\/register(photocell:nib:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuselectablephotoviewcontroller\/register(photocell:nib:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewController\/register(photoCell:nib:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Used to register a custom cell as a base cell based on "},{"type":"codeVoice","code":"SBUPhotoCollectionViewCell"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"externalParam","text":"photoCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUPhotoCollectionViewCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUPhotoCollectionViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nib"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":"?)"}],"title":"register(photoCell:nib:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUSelectablePhotoViewController(im)registerWithPhotoCell:nib:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"registerWithPhotoCell:nib:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUSelectablePhotoViewController":{"role":"symbol","title":"SBUSelectablePhotoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUSelectablePhotoViewController"}],"abstract":[{"type":"text","text":"The view controller that shows the selected accessible photos and videos."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUSelectablePhotoViewController"}],"url":"\/documentation\/sendbirduikit\/sbuselectablephotoviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUSelectablePhotoViewController/register(photoCell:nib:)":{"role":"symbol","title":"register(photoCell:nib:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"externalParam","text":"photoCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUPhotoCollectionViewCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUPhotoCollectionViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nib"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Used to register a custom cell as a base cell based on "},{"type":"codeVoice","code":"SBUPhotoCollectionViewCell"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewController\/register(photoCell:nib:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerWithPhotoCell:nib:"}],"url":"\/documentation\/sendbirduikit\/sbuselectablephotoviewcontroller\/register(photocell:nib:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUPhotoCollectionViewCell":{"role":"symbol","title":"SBUPhotoCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUPhotoCollectionViewCell"}],"abstract":[{"type":"text","text":"The collection view cell for "},{"type":"codeVoice","code":"SBUSelectablePhotoViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUPhotoCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUPhotoCollectionViewCell"}],"url":"\/documentation\/sendbirduikit\/sbuphotocollectionviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerWithPhotoCell:nib:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerWithPhotoCell:nib:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerWithPhotoCell:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUPhotoCollectionViewCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUPhotoCollectionViewCell","text":"SBUPhotoCollectionViewCell"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"photoCell"},{"kind":"text","text":" "},{"kind":"identifier","text":"nib:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"nib"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSelectablePhotoViewController\/title","value":"SBUSelectablePhotoViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSelectablePhotoViewController\/fragments","value":[{"kind":"identifier","text":"SBUSelectablePhotoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSelectablePhotoViewController~1register(photoCell:nib:)\/title","value":"registerWithPhotoCell:nib:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSelectablePhotoViewController~1register(photoCell:nib:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerWithPhotoCell:nib:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUPhotoCollectionViewCell\/title","value":"SBUPhotoCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUPhotoCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"SBUPhotoCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}