{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectableStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUSelectableStackView","text":"SBUSelectableStackView"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuusermessagecell\/additioncontainerview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuusermessagecell\/additioncontainerview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserMessageCell\/additionContainerView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectableStackView"},{"type":"text","text":" that contains "},{"type":"codeVoice","code":"reactionView"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUSelectableStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUSelectableStackView"}],"title":"additionContainerView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUUserMessageCell(py)additionContainerView","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"additionContainerView"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserMessageCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserMessageCell":{"role":"symbol","title":"SBUUserMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbuusermessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUSelectableStackView":{"role":"symbol","title":"SBUSelectableStackView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUSelectableStackView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectableStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUSelectableStackView"}],"url":"\/documentation\/sendbirduikit\/sbuselectablestackview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserMessageCell/additionContainerView":{"role":"symbol","title":"additionContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUSelectableStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUSelectableStackView"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectableStackView"},{"type":"text","text":" that contains "},{"type":"codeVoice","code":"reactionView"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserMessageCell\/additionContainerView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"additionContainerView"}],"url":"\/documentation\/sendbirduikit\/sbuusermessagecell\/additioncontainerview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"additionContainerView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"additionContainerView"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectableStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUSelectableStackView","text":"SBUSelectableStackView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"additionContainerView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserMessageCell\/title","value":"SBUUserMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUUserMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSelectableStackView\/title","value":"SBUSelectableStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSelectableStackView\/fragments","value":[{"kind":"identifier","text":"SBUSelectableStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserMessageCell~1additionContainerView\/title","value":"additionContainerView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserMessageCell~1additionContainerView\/fragments","value":[{"kind":"identifier","text":"additionContainerView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}