{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTapWebview"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuusermessagecell\/ontapwebview(sender:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuusermessagecell\/ontapwebview(sender:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserMessageCell\/onTapWebview(sender:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTapWebview"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"title":"onTapWebview(sender:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUUserMessageCell(im)onTapWebviewWithSender:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"onTapWebviewWithSender:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserMessageCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserMessageCell":{"role":"symbol","title":"SBUUserMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbuusermessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserMessageCell/onTapWebview(sender:)":{"role":"symbol","title":"onTapWebview(sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onTapWebview"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserMessageCell\/onTapWebview(sender:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onTapWebviewWithSender:"}],"url":"\/documentation\/sendbirduikit\/sbuusermessagecell\/ontapwebview(sender:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onTapWebviewWithSender:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTapWebviewWithSender:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onTapWebviewWithSender:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserMessageCell\/title","value":"SBUUserMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUUserMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserMessageCell~1onTapWebview(sender:)\/title","value":"onTapWebviewWithSender:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserMessageCell~1onTapWebview(sender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onTapWebviewWithSender:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}