{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedTextRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextRange","preciseIdentifier":"c:objc(cs)UITextRange"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbulinkclickabletextview\/selectedtextrange"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbulinkclickabletextview\/selectedtextrange"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/selectedTextRange","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedTextRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextRange","preciseIdentifier":"c:objc(cs)UITextRange"},{"kind":"text","text":"?"}],"title":"selectedTextRange","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBULinkClickableTextView(py)selectedTextRange","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"selectedTextRange"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBULinkClickableTextView/selectedTextRange":{"role":"symbol","title":"selectedTextRange","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedTextRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextRange","preciseIdentifier":"c:objc(cs)UITextRange"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/selectedTextRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedTextRange"}],"url":"\/documentation\/sendbirduikit\/sbulinkclickabletextview\/selectedtextrange"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBULinkClickableTextView":{"role":"symbol","title":"SBULinkClickableTextView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBULinkClickableTextView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBULinkClickableTextView"}],"url":"\/documentation\/sendbirduikit\/sbulinkclickabletextview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"selectedTextRange"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"selectedTextRange"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UITextRange","preciseIdentifier":"c:objc(cs)UITextRange"},{"kind":"text","text":" * "},{"kind":"identifier","text":"selectedTextRange"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBULinkClickableTextView~1selectedTextRange\/title","value":"selectedTextRange"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBULinkClickableTextView~1selectedTextRange\/fragments","value":[{"kind":"identifier","text":"selectedTextRange"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBULinkClickableTextView\/title","value":"SBULinkClickableTextView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBULinkClickableTextView\/fragments","value":[{"kind":"identifier","text":"SBULinkClickableTextView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}