{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateLayouts"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuview\/updatelayouts()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuview\/updatelayouts()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUView\/updateLayouts()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function updates layouts."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"updateLayouts"}],"role":"symbol","title":"updateLayouts()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateLayouts"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUView(im)updateLayouts","extendedModule":"SendbirdUIKit","modules":[{"name":"SendbirdUIKit"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUView\/SBUViewLifeCycle-Implementations"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUView/SBUViewLifeCycle-Implementations":{"role":"collectionGroup","title":"SBUViewLifeCycle Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUView\/SBUViewLifeCycle-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/sbuview\/sbuviewlifecycle-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUView":{"role":"symbol","title":"SBUView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUView"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" conforming to "},{"type":"codeVoice","code":"SBUViewLifeCycle"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUView"}],"url":"\/documentation\/sendbirduikit\/sbuview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUView/updateLayouts()":{"role":"symbol","title":"updateLayouts()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateLayouts"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function updates layouts."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUView\/updateLayouts()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateLayouts"}],"url":"\/documentation\/sendbirduikit\/sbuview\/updatelayouts()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateLayouts"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateLayouts"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateLayouts"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUView\/title","value":"SBUView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUView\/fragments","value":[{"kind":"identifier","text":"SBUView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUView~1updateLayouts()\/title","value":"updateLayouts"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUView~1updateLayouts()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateLayouts"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}