{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"members"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser","text":"SBUUser"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelMemberListType","preciseIdentifier":"c:@M@SendbirdUIKit@E@ChannelMemberListType","text":"ChannelMemberListType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/init(channel:members:type:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/init(channel:members:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/init(channel:members:type:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithChannel:members:type:"}],"role":"symbol","title":"init(channel:members:type:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"members"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelMemberListType","preciseIdentifier":"c:@M@SendbirdUIKit@E@ChannelMemberListType"},{"kind":"text","text":")"}],"symbolKind":"init","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUUserListViewController(im)initWithChannel:members:type:","extendedModule":"SendbirdUIKit","platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUser":{"role":"symbol","title":"SBUUser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUser"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUser"}],"url":"\/documentation\/sendbirduikit\/sbuuser"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelMemberListType":{"deprecated":true,"role":"symbol","title":"ChannelMemberListType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelMemberListType"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelMemberListType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelMemberListType"}],"url":"\/documentation\/sendbirduikit\/channelmemberlisttype"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController/init(channel:members:type:)":{"deprecated":true,"role":"symbol","title":"init(channel:members:type:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"members"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelMemberListType","preciseIdentifier":"c:@M@SendbirdUIKit@E@ChannelMemberListType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/init(channel:members:type:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithChannel:members:type:"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/init(channel:members:type:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController":{"role":"symbol","title":"SBUUserListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserListViewController"}],"abstract":[{"type":"text","text":"This class handling members,  operators,  muted\/Participants,  banned,  participants,"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserListViewController"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithChannel:members:type:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannel:members:type:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithChannel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDBaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"members:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBUUser *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"members"},{"kind":"text","text":" "},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelMemberListType","preciseIdentifier":"c:@M@SendbirdUIKit@E@ChannelMemberListType","text":"ChannelMemberListType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/title","value":"SBUUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/fragments","value":[{"kind":"identifier","text":"SBUUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelMemberListType\/title","value":"ChannelMemberListType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelMemberListType\/fragments","value":[{"kind":"identifier","text":"ChannelMemberListType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1init(channel:members:type:)\/title","value":"initWithChannel:members:type:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1init(channel:members:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannel:members:type:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/title","value":"SBUUserListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/fragments","value":[{"kind":"identifier","text":"SBUUserListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}