{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/loadchannel(channelurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/loadchannel(channelurl:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/loadChannel(channelUrl:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"loadChannelWithChannelUrl:"}],"role":"symbol","title":"loadChannel(channelUrl:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUUserListViewController(im)loadChannelWithChannelUrl:","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This function has been moved to the `SBUUserListViewModel`."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController/loadChannel(channelUrl:)":{"deprecated":true,"role":"symbol","title":"loadChannel(channelUrl:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/loadChannel(channelUrl:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadChannelWithChannelUrl:"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/loadchannel(channelurl:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController":{"role":"symbol","title":"SBUUserListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserListViewController"}],"abstract":[{"type":"text","text":"This class handling members,  operators,  muted\/Participants,  banned,  participants,"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserListViewController"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"loadChannelWithChannelUrl:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadChannelWithChannelUrl:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"loadChannelWithChannelUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelUrl"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1loadChannel(channelUrl:)\/title","value":"loadChannelWithChannelUrl:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1loadChannel(channelUrl:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadChannelWithChannelUrl:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/title","value":"SBUUserListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/fragments","value":[{"kind":"identifier","text":"SBUUserListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}