{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"member"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser","text":"SBUUser"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/unmute(member:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/unmute(member:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/unmute(member:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"unmuteWithMember:"}],"role":"symbol","title":"unmute(member:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"member"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUUserListViewController(im)unmuteWithMember:","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This function has been moved to the `SBUUserListViewModel`."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController":{"role":"symbol","title":"SBUUserListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserListViewController"}],"abstract":[{"type":"text","text":"This class handling members,  operators,  muted\/Participants,  banned,  participants,"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserListViewController"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUser":{"role":"symbol","title":"SBUUser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUser"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUser"}],"url":"\/documentation\/sendbirduikit\/sbuuser"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController/unmute(member:)":{"deprecated":true,"role":"symbol","title":"unmute(member:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unmute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"member"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/unmute(member:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unmuteWithMember:"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/unmute(member:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"unmuteWithMember:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unmuteWithMember:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"unmuteWithMember:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser","text":"SBUUser"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"member"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/title","value":"SBUUserListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/fragments","value":[{"kind":"identifier","text":"SBUUserListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/title","value":"SBUUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/fragments","value":[{"kind":"identifier","text":"SBUUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1unmute(member:)\/title","value":"unmuteWithMember:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1unmute(member:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unmuteWithMember:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}