{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userListModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListModule","preciseIdentifier":"s:13SendbirdUIKit17SBUUserListModuleC","text":"SBUUserListModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListModule\/Header","preciseIdentifier":"s:13SendbirdUIKit17SBUUserListModuleC6HeaderC","text":"Header"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateTitleView"},{"kind":"text","text":" "},{"kind":"internalParam","text":"titleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"headerComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUUserListModule.Header"},{"type":"text","text":" object"}]}]},{"name":"titleView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Updated "},{"type":"codeVoice","code":"titleView"},{"type":"text","text":" object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/userlistmodule(_:didupdatetitleview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/userlistmodule(_:didupdatetitleview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/userListModule(_:didUpdateTitleView:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"titleView"},{"type":"text","text":" value has been updated."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userListModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUUserListModule","preciseIdentifier":"s:13SendbirdUIKit17SBUUserListModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit17SBUUserListModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateTitleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"title":"userListModule(_:didUpdateTitleView:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUUserListViewController(im)userListModule:didUpdateTitleView:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"userListModule:didUpdateTitleView:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/Header":{"role":"symbol","title":"Header","fragments":[{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"text","text":"SBUMessageSearchModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListModule/Header":{"role":"symbol","title":"SBUUserListModule.Header","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"codeVoice","code":"SBUUserListModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListModule\/Header","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Header"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistmodule\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListModule":{"role":"symbol","title":"SBUUserListModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserListModule"}],"abstract":[{"type":"text","text":"The class that represents the module for multiple types of the user list."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserListModule"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController/userListModule(_:didUpdateTitleView:)":{"role":"symbol","title":"userListModule(_:didUpdateTitleView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userListModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUUserListModule","preciseIdentifier":"s:13SendbirdUIKit17SBUUserListModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit17SBUUserListModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateTitleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"titleView"},{"type":"text","text":" value has been updated."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/userListModule(_:didUpdateTitleView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userListModule:didUpdateTitleView:"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/userlistmodule(_:didupdatetitleview:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController":{"role":"symbol","title":"SBUUserListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserListViewController"}],"abstract":[{"type":"text","text":"This class handling members,  operators,  muted\/Participants,  banned,  participants,"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserListViewController"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userListModule:didUpdateTitleView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userListModule:didUpdateTitleView:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userListModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)Header","text":"Header"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateTitleView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"titleView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1userListModule(_:didUpdateTitleView:)\/title","value":"userListModule:didUpdateTitleView:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1userListModule(_:didUpdateTitleView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userListModule:didUpdateTitleView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/title","value":"SBUUserListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/fragments","value":[{"kind":"identifier","text":"SBUUserListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}