{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/usercell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/usercell"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/userCell","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"userCell"}],"role":"symbol","title":"userCell","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUUserListViewController(py)userCell","extendedModule":"SendbirdUIKit","platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This property has been moved to the `SBUUserListModule.List`."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController/userCell":{"deprecated":true,"role":"symbol","title":"userCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/userCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userCell"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/usercell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController":{"role":"symbol","title":"SBUUserListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserListViewController"}],"abstract":[{"type":"text","text":"This class handling members,  operators,  muted\/Participants,  banned,  participants,"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserListViewController"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"userCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"userCell"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":" * "},{"kind":"identifier","text":"userCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1userCell\/title","value":"userCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1userCell\/fragments","value":[{"kind":"identifier","text":"userCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/title","value":"SBUUserListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/fragments","value":[{"kind":"identifier","text":"SBUUserListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}