{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userListViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUserListViewModel","text":"SBUUserListViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeUsers"},{"kind":"text","text":" "},{"kind":"internalParam","text":"users"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser","text":"SBUUser"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"needsToReload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/userlistviewmodel(_:didchangeusers:needstoreload:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/userlistviewmodel(_:didchangeusers:needstoreload:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/userListViewModel(_:didChangeUsers:needsToReload:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the users has been changed"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUUserListViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUserListViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"needsToReload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"userListViewModel(_:didChangeUsers:needsToReload:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUUserListViewController(im)userListViewModel:didChangeUsers:needsToReload:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"userListViewModel:didChangeUsers:needsToReload:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUser":{"role":"symbol","title":"SBUUser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUser"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUser"}],"url":"\/documentation\/sendbirduikit\/sbuuser"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController":{"role":"symbol","title":"SBUUserListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserListViewController"}],"abstract":[{"type":"text","text":"This class handling members,  operators,  muted\/Participants,  banned,  participants,"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserListViewController"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewModel":{"role":"symbol","title":"SBUUserListViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserListViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserListViewModel"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController/userListViewModel(_:didChangeUsers:needsToReload:)":{"role":"symbol","title":"userListViewModel(_:didChangeUsers:needsToReload:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUUserListViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUserListViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"needsToReload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the users has been changed"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController\/userListViewModel(_:didChangeUsers:needsToReload:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userListViewModel:didChangeUsers:needsToReload:"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller\/userlistviewmodel(_:didchangeusers:needstoreload:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"userListViewModel:didChangeUsers:needsToReload:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userListViewModel:didChangeUsers:needsToReload:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"userListViewModel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUserListViewModel","text":"SBUUserListViewModel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeUsers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBUUser *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"users"},{"kind":"text","text":" "},{"kind":"identifier","text":"needsToReload:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"needsToReload"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/title","value":"SBUUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/fragments","value":[{"kind":"identifier","text":"SBUUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/title","value":"SBUUserListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/fragments","value":[{"kind":"identifier","text":"SBUUserListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewModel\/title","value":"SBUUserListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewModel\/fragments","value":[{"kind":"identifier","text":"SBUUserListViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1userListViewModel(_:didChangeUsers:needsToReload:)\/title","value":"userListViewModel:didChangeUsers:needsToReload:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController~1userListViewModel(_:didChangeUsers:needsToReload:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userListViewModel:didChangeUsers:needsToReload:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}