{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelMembers"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/memberlisttype\/channelmembers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/memberlisttype\/channelmembers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MemberListType\/channelMembers","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MemberListTypeChannelMembers"}],"role":"symbol","title":"MemberListType.channelMembers","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelMembers"}],"symbolKind":"case","externalID":"c:@M@SendbirdUIKit@E@MemberListType@MemberListTypeChannelMembers","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MemberListType"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MemberListType":{"deprecated":true,"role":"symbol","title":"MemberListType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MemberListType"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MemberListType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListType"}],"url":"\/documentation\/sendbirduikit\/memberlisttype"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MemberListType/channelMembers":{"deprecated":true,"role":"symbol","title":"MemberListType.channelMembers","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelMembers"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MemberListType\/channelMembers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MemberListTypeChannelMembers"}],"url":"\/documentation\/sendbirduikit\/memberlisttype\/channelmembers"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MemberListTypeChannelMembers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MemberListTypeChannelMembers"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MemberListTypeChannelMembers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MemberListType\/title","value":"MemberListType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MemberListType\/fragments","value":[{"kind":"identifier","text":"MemberListType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MemberListType~1channelMembers\/title","value":"MemberListTypeChannelMembers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MemberListType~1channelMembers\/fragments","value":[{"kind":"identifier","text":"MemberListTypeChannelMembers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}