{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelListModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModule","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelListModule","text":"SBUBaseChannelListModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModule\/List","preciseIdentifier":"s:13SendbirdUIKit24SBUBaseChannelListModuleC0E0C","text":"List"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUBaseChannelListModule.List"},{"type":"text","text":" object."}]}]},{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An index path locating the row in table view of `listComponent"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannellistviewcontroller\/basechannellistmodule(_:didselectrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannellistviewcontroller\/basechannellistmodule(_:didselectrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewController\/baseChannelListModule(_:didSelectRowAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the channel cell was selected in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelListModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelListModule","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelListModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit24SBUBaseChannelListModuleC0E0C"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"title":"baseChannelListModule(_:didSelectRowAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelListViewController(im)baseChannelListModule:didSelectRowAt:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"baseChannelListModule:didSelectRowAt:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelListModule":{"role":"symbol","title":"SBUBaseChannelListModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelListModule"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelListModule"}],"url":"\/documentation\/sendbirduikit\/sbubasechannellistmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelListModuleList":{"role":"symbol","title":"SBUBaseChannelListModuleList","fragments":[{"kind":"identifier","text":"SBUBaseChannelListModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUBaseChannelListModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbubasechannellistmodulelist"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListViewController/baseChannelListModule(_:didSelectRowAt:)":{"role":"symbol","title":"baseChannelListModule(_:didSelectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelListModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelListModule","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelListModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit24SBUBaseChannelListModuleC0E0C"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the channel cell was selected in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewController\/baseChannelListModule(_:didSelectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseChannelListModule:didSelectRowAt:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistviewcontroller\/basechannellistmodule(_:didselectrowat:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListViewController":{"role":"symbol","title":"SBUOpenChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelListModule/List":{"role":"symbol","title":"SBUBaseChannelListModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUBaseChannelListModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbubasechannellistmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"baseChannelListModule:didSelectRowAt:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelListModule:didSelectRowAt:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"baseChannelListModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelListModuleList","text":"SBUBaseChannelListModuleList"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectRowAt:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelListModule\/title","value":"SBUBaseChannelListModule"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelListModule\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelListModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewController~1baseChannelListModule(_:didSelectRowAt:)\/title","value":"baseChannelListModule:didSelectRowAt:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewController~1baseChannelListModule(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelListModule:didSelectRowAt:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewController\/title","value":"SBUOpenChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}