{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListModule","preciseIdentifier":"s:13SendbirdUIKit24SBUOpenChannelListModuleC","text":"SBUOpenChannelListModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListModule\/List","preciseIdentifier":"s:13SendbirdUIKit24SBUOpenChannelListModuleC0E0C","text":"List"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannellistviewcontroller\/listcomponent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannellistviewcontroller\/listcomponent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewController\/listComponent","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelListModule","preciseIdentifier":"s:13SendbirdUIKit24SBUOpenChannelListModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit24SBUOpenChannelListModuleC0E0C"},{"kind":"text","text":"?"}],"title":"listComponent","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelListViewController(py)listComponent","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"listComponent"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListModule/List":{"role":"symbol","title":"SBUOpenChannelListModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUOpenChannelListModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListModule":{"role":"symbol","title":"SBUOpenChannelListModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelListModule"}],"abstract":[{"type":"text","text":"The class that represents the list of the open channel module"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelListModule"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListViewController/listComponent":{"role":"symbol","title":"listComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelListModule","preciseIdentifier":"s:13SendbirdUIKit24SBUOpenChannelListModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit24SBUOpenChannelListModuleC0E0C"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewController\/listComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"listComponent"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistviewcontroller\/listcomponent"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListViewController":{"role":"symbol","title":"SBUOpenChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListModuleList":{"role":"symbol","title":"SBUOpenChannelListModuleList","fragments":[{"kind":"identifier","text":"SBUOpenChannelListModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUOpenChannelListModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbuopenchannellistmodulelist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"listComponent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"listComponent"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelListModuleList","text":"SBUOpenChannelListModuleList"},{"kind":"text","text":" * "},{"kind":"identifier","text":"listComponent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewController~1listComponent\/title","value":"listComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewController~1listComponent\/fragments","value":[{"kind":"identifier","text":"listComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewController\/title","value":"SBUOpenChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}