{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMessages"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewmodel\/messagecollection(_:context:channel:deletedmessages:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewmodel\/messagecollection(_:context:channel:deletedmessages:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewModel\/messageCollection(_:context:channel:deletedMessages:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MessageCollectionDelegate.messageCollection(_:context:channel:deletedMessages:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:channel:deletedMessages:"}],"role":"symbol","title":"messageCollection(_:context:channel:deletedMessages:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUGroupChannelViewModel(im)messageCollection:context:channel:deletedMessages:","extendedModule":"SendbirdUIKit","modules":[{"name":"SendbirdUIKit"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewModel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewModel\/MessageCollectionDelegate-Implementations"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewModel":{"role":"symbol","title":"SBUGroupChannelViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelViewModel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewModel/messageCollection(_:context:channel:deletedMessages:)":{"role":"symbol","title":"messageCollection(_:context:channel:deletedMessages:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedMessages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewModel\/messageCollection(_:context:channel:deletedMessages:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageCollection:context:channel:deletedMessages:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewmodel\/messagecollection(_:context:channel:deletedmessages:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewModel/MessageCollectionDelegate-Implementations":{"role":"collectionGroup","title":"MessageCollectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewModel\/MessageCollectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/sbugroupchannelviewmodel\/messagecollectiondelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"messageCollection:context:channel:deletedMessages:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:channel:deletedMessages:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"messageCollection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDMessageCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageCollection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collection"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDMessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDGroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"deletedMessages:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBDBaseMessage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messages"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewModel\/title","value":"SBUGroupChannelViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewModel\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewModel~1messageCollection(_:context:channel:deletedMessages:)\/title","value":"messageCollection:context:channel:deletedMessages:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewModel~1messageCollection(_:context:channel:deletedMessages:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageCollection:context:channel:deletedMessages:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}