{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateStyles"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuphotocollectionviewcell\/updatestyles()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuphotocollectionviewcell\/updatestyles()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUPhotoCollectionViewCell\/updateStyles()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function updates styles."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateStyles"},{"kind":"text","text":"()"}],"title":"updateStyles()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUPhotoCollectionViewCell(im)updateStyles","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"updateStyles"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUPhotoCollectionViewCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUPhotoCollectionViewCell/updateStyles()":{"role":"symbol","title":"updateStyles()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateStyles"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function updates styles."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUPhotoCollectionViewCell\/updateStyles()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateStyles"}],"url":"\/documentation\/sendbirduikit\/sbuphotocollectionviewcell\/updatestyles()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUPhotoCollectionViewCell":{"role":"symbol","title":"SBUPhotoCollectionViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUPhotoCollectionViewCell"}],"abstract":[{"type":"text","text":"The collection view cell for "},{"type":"codeVoice","code":"SBUSelectablePhotoViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUPhotoCollectionViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUPhotoCollectionViewCell"}],"url":"\/documentation\/sendbirduikit\/sbuphotocollectionviewcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateStyles"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateStyles"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateStyles"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUPhotoCollectionViewCell~1updateStyles()\/title","value":"updateStyles"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUPhotoCollectionViewCell~1updateStyles()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateStyles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUPhotoCollectionViewCell\/title","value":"SBUPhotoCollectionViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUPhotoCollectionViewCell\/fragments","value":[{"kind":"identifier","text":"SBUPhotoCollectionViewCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}