{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdf"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/messagefiletype\/pdf"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/messagefiletype\/pdf"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageFileType\/pdf","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdf"}],"title":"MessageFileType.pdf","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdUIKit@E@MessageFileType@MessageFileTypePdf","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MessageFileTypePdf"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageFileType"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessageFileType":{"role":"symbol","title":"MessageFileType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageFileType"}],"abstract":[{"type":"text","text":"This is an enumeration to file type in the message."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageFileType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageFileType"}],"url":"\/documentation\/sendbirduikit\/messagefiletype"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessageFileType/pdf":{"role":"symbol","title":"MessageFileType.pdf","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pdf"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageFileType\/pdf","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageFileTypePdf"}],"url":"\/documentation\/sendbirduikit\/messagefiletype\/pdf"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MessageFileTypePdf"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageFileTypePdf"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MessageFileTypePdf"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageFileType\/title","value":"MessageFileType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageFileType\/fragments","value":[{"kind":"identifier","text":"MessageFileType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageFileType~1pdf\/title","value":"MessageFileTypePdf"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageFileType~1pdf\/fragments","value":[{"kind":"identifier","text":"MessageFileTypePdf"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}