{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelModule","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC","text":"SBUBaseChannelModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelModule\/Header","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC6HeaderC","text":"Header"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":" "},{"kind":"internalParam","text":"leftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/basechannelmodule(_:didtapleftitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/basechannelmodule(_:didtapleftitem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/baseChannelModule(_:didTapLeftItem:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelModule","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"title":"baseChannelModule(_:didTapLeftItem:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelViewController(im)baseChannelModule:didTapLeftItem:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"baseChannelModule:didTapLeftItem:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelModule":{"role":"symbol","title":"SBUBaseChannelModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelModule"}],"abstract":[{"type":"text","text":"The class that represents the base of the channel module"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelModule"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/Header":{"role":"symbol","title":"Header","fragments":[{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"text","text":"SBUMessageSearchModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController":{"role":"symbol","title":"SBUGroupChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController/baseChannelModule(_:didTapLeftItem:)":{"role":"symbol","title":"baseChannelModule(_:didTapLeftItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelModule","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/baseChannelModule(_:didTapLeftItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseChannelModule:didTapLeftItem:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/basechannelmodule(_:didtapleftitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelModule/Header":{"role":"symbol","title":"SBUBaseChannelModule.Header","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"codeVoice","code":"SBUBaseChannelModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelModule\/Header","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Header"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelmodule\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"baseChannelModule:didTapLeftItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelModule:didTapLeftItem:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"baseChannelModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)Header","text":"Header"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapLeftItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"leftItem"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/title","value":"SBUGroupChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1baseChannelModule(_:didTapLeftItem:)\/title","value":"baseChannelModule:didTapLeftItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1baseChannelModule(_:didTapLeftItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelModule:didTapLeftItem:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}