{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inputComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC","text":"SBUGroupChannelModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule\/Input","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC5InputC","text":"Input"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapSend"},{"kind":"text","text":" "},{"kind":"internalParam","text":"text"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mentionedMessageTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mentionedUserIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"parentMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"inputComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUGroupChannelModule.Input"},{"type":"text","text":" object."}]}]},{"name":"text","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The normal text."}]}]},{"name":"mentionedMessageTemplate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The mentioned text that is generated by "},{"type":"codeVoice","code":"text"},{"type":"text","text":" and "},{"type":"codeVoice","code":"mentionUsers"},{"type":"text","text":"."}]}]},{"name":"mentionedUserIds","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The mentioned userIds."}]}]},{"name":"parentMessage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The parent message of the message representing "},{"type":"codeVoice","code":"text"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"codeListing","syntax":"swift","code":["print(text) \/\/ \"Hi @Nickname\"","print(mentionedMessageTemplate) \/\/ \"Hi @{UserID}\"","print(mentionedUserIds) \/\/ [\"{UserID}\"]"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/groupchannelmodule(_:didtapsend:mentionedmessagetemplate:mentioneduserids:parentmessage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/groupchannelmodule(_:didtapsend:mentionedmessagetemplate:mentioneduserids:parentmessage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/groupChannelModule(_:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the send button was tapped."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Input","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC5InputC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapSend"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mentionedMessageTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mentionedUserIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"parentMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"?)"}],"title":"groupChannelModule(_:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelViewController(im)groupChannelModule:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"groupChannelModule:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController/groupChannelModule(_:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:)":{"role":"symbol","title":"groupChannelModule(_:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Input","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC5InputC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapSend"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mentionedMessageTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mentionedUserIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"parentMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when the send button was tapped."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/groupChannelModule(_:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelModule:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/groupchannelmodule(_:didtapsend:mentionedmessagetemplate:mentioneduserids:parentmessage:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelModule":{"role":"symbol","title":"SBUGroupChannelModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelModule"}],"abstract":[{"type":"text","text":"The class that represents the group channel module"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelModule"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelModule/Input":{"role":"symbol","title":"SBUGroupChannelModule.Input","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Input"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SBUGroupChannelModule"},{"type":"text","text":"’s component class that represents input"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule\/Input","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Input"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelmodule\/input"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController":{"role":"symbol","title":"SBUGroupChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupChannelModule:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelModule:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupChannelModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelModuleInput","preciseIdentifier":"c:objc(cs)SBUGroupChannelModuleInput"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"inputComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapSend:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"text"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionedMessageTemplate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mentionedMessageTemplate"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionedUserIds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"mentionedUserIds"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDBaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"parentMessage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1groupChannelModule(_:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:)\/title","value":"groupChannelModule:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1groupChannelModule(_:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelModule:didTapSend:mentionedMessageTemplate:mentionedUserIds:parentMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/title","value":"SBUGroupChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}