{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"inputComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC","text":"SBUGroupChannelModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule\/Input","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC5InputC","text":"Input"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldLoadSuggestedMentions"},{"kind":"text","text":" "},{"kind":"internalParam","text":"filterText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"inputComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUGroupChannelModule.Input"},{"type":"text","text":" object."}]}]},{"name":"filterText","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The text that is used as a filter while loading the suggested mentions."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/groupchannelmodule(_:shouldloadsuggestedmentions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/groupchannelmodule(_:shouldloadsuggestedmentions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/groupChannelModule(_:shouldLoadSuggestedMentions:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the suggested mentions should be loaded. Please refer to "},{"type":"codeVoice","code":"loadSuggestedMentions(with:)"},{"type":"text","text":" function in "},{"type":"codeVoice","code":"SBUGroupChannelViewModel"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Input","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC5InputC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldLoadSuggestedMentions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"groupChannelModule(_:shouldLoadSuggestedMentions:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelViewController(im)groupChannelModule:shouldLoadSuggestedMentions:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"groupChannelModule:shouldLoadSuggestedMentions:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController":{"role":"symbol","title":"SBUGroupChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController/groupChannelModule(_:shouldLoadSuggestedMentions:)":{"role":"symbol","title":"groupChannelModule(_:shouldLoadSuggestedMentions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Input","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC5InputC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldLoadSuggestedMentions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the suggested mentions should be loaded. Please refer to "},{"type":"codeVoice","code":"loadSuggestedMentions(with:)"},{"type":"text","text":" function in "},{"type":"codeVoice","code":"SBUGroupChannelViewModel"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/groupChannelModule(_:shouldLoadSuggestedMentions:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelModule:shouldLoadSuggestedMentions:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/groupchannelmodule(_:shouldloadsuggestedmentions:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelModule/Input":{"role":"symbol","title":"SBUGroupChannelModule.Input","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Input"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SBUGroupChannelModule"},{"type":"text","text":"’s component class that represents input"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule\/Input","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Input"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelmodule\/input"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelModule":{"role":"symbol","title":"SBUGroupChannelModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelModule"}],"abstract":[{"type":"text","text":"The class that represents the group channel module"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelModule"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelmodule"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupChannelModule:shouldLoadSuggestedMentions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelModule:shouldLoadSuggestedMentions:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupChannelModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelModuleInput","preciseIdentifier":"c:objc(cs)SBUGroupChannelModuleInput"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"inputComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldLoadSuggestedMentions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"filterText"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/title","value":"SBUGroupChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1groupChannelModule(_:shouldLoadSuggestedMentions:)\/title","value":"groupChannelModule:shouldLoadSuggestedMentions:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1groupChannelModule(_:shouldLoadSuggestedMentions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelModule:shouldLoadSuggestedMentions:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}