{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC","text":"SBUGroupChannelModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule\/List","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC4ListC","text":"List"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLongTapEmoji"},{"kind":"text","text":" "},{"kind":"internalParam","text":"emojiKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseMessageCell","text":"SBUBaseMessageCell"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"emojiKey","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"emoji key"}]}]},{"name":"messageCell","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Message cell object"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/groupchannelmodule(_:didlongtapemoji:messagecell:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/groupchannelmodule(_:didlongtapemoji:messagecell:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/groupChannelModule(_:didLongTapEmoji:messageCell:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when long tapped emoji in the cell."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLongTapEmoji"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUBaseMessageCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseMessageCell"},{"kind":"text","text":")"}],"title":"groupChannelModule(_:didLongTapEmoji:messageCell:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelViewController(im)groupChannelModule:didLongTapEmoji:messageCell:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"groupChannelModule:didLongTapEmoji:messageCell:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell":{"role":"symbol","title":"SBUBaseMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelModule/List":{"role":"symbol","title":"SBUGroupChannelModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUGroupChannelModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelModule":{"role":"symbol","title":"SBUGroupChannelModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelModule"}],"abstract":[{"type":"text","text":"The class that represents the group channel module"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelModule"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController":{"role":"symbol","title":"SBUGroupChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController/groupChannelModule(_:didLongTapEmoji:messageCell:)":{"role":"symbol","title":"groupChannelModule(_:didLongTapEmoji:messageCell:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLongTapEmoji"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUBaseMessageCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseMessageCell"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when long tapped emoji in the cell."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/groupChannelModule(_:didLongTapEmoji:messageCell:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelModule:didLongTapEmoji:messageCell:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/groupchannelmodule(_:didlongtapemoji:messagecell:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelModuleList":{"role":"symbol","title":"SBUGroupChannelModuleList","fragments":[{"kind":"identifier","text":"SBUGroupChannelModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUGroupChannelModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbugroupchannelmodulelist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupChannelModule:didLongTapEmoji:messageCell:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelModule:didLongTapEmoji:messageCell:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupChannelModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelModuleList","text":"SBUGroupChannelModuleList"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didLongTapEmoji:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"emojiKey"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageCell:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseMessageCell","text":"SBUBaseMessageCell"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messageCell"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell\/title","value":"SBUBaseMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUBaseMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/title","value":"SBUGroupChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1groupChannelModule(_:didLongTapEmoji:messageCell:)\/title","value":"groupChannelModule:didLongTapEmoji:messageCell:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1groupChannelModule(_:didLongTapEmoji:messageCell:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelModule:didLongTapEmoji:messageCell:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}