{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Channel object"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the example below for params generation."}]},{"type":"codeListing","syntax":null,"code":["    let params = MessageListParams()","    params.includeMetaArray = true","    params.includeReactions = true","    params.includeThreadInfo = true","    ..."]},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"reverse"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"previousResultSize"},{"type":"text","text":" properties in the "},{"type":"codeVoice","code":"MessageListParams"},{"type":"text","text":" are set in the UIKit. Even though you set that property it will be ignored."}]}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"1.0.11"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/init(channel:messagelistparams:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/init(channel:messagelistparams:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/init(channel:messageListParams:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"If you have channel object, use this initialize function. And, if you have own message list params, please set it. If not set, it is used as the default value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"?)"}],"title":"init(channel:messageListParams:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelViewController(im)initWithChannel:messageListParams:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithChannel:messageListParams:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController":{"role":"symbol","title":"SBUGroupChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController/init(channel:messageListParams:)":{"role":"symbol","title":"init(channel:messageListParams:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"If you have channel object, use this initialize function. And, if you have own message list params, please set it. If not set, it is used as the default value."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/init(channel:messageListParams:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithChannel:messageListParams:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/init(channel:messagelistparams:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithChannel:messageListParams:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannel:messageListParams:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithChannel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDGroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageListParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDMessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messageListParams"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/title","value":"SBUGroupChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1init(channel:messageListParams:)\/title","value":"initWithChannel:messageListParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1init(channel:messageListParams:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannel:messageListParams:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}