{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC","text":"SBUGroupChannelModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule\/Input","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC5InputC","text":"Input"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/inputcomponent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/inputcomponent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/inputComponent","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Input","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC5InputC"},{"kind":"text","text":"?"}],"title":"inputComponent","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelViewController(py)inputComponent","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"inputComponent"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelModule":{"role":"symbol","title":"SBUGroupChannelModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelModule"}],"abstract":[{"type":"text","text":"The class that represents the group channel module"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelModule"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelModule/Input":{"role":"symbol","title":"SBUGroupChannelModule.Input","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Input"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SBUGroupChannelModule"},{"type":"text","text":"’s component class that represents input"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule\/Input","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Input"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelmodule\/input"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController/inputComponent":{"role":"symbol","title":"inputComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUGroupChannelModule","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Input","preciseIdentifier":"s:13SendbirdUIKit21SBUGroupChannelModuleC5InputC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController\/inputComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"inputComponent"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller\/inputcomponent"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController":{"role":"symbol","title":"SBUGroupChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"inputComponent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"inputComponent"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBUGroupChannelModuleInput","preciseIdentifier":"c:objc(cs)SBUGroupChannelModuleInput"},{"kind":"text","text":" * "},{"kind":"identifier","text":"inputComponent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1inputComponent\/title","value":"inputComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController~1inputComponent\/fragments","value":[{"kind":"identifier","text":"inputComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/title","value":"SBUGroupChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}