{"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewmodel\/openchanneldelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewmodel\/openchanneldelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModel\/OpenChannelDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModel\/channel(_:userDidEnter:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModel\/channel(_:userDidExit:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SendbirdUIKit"}],"role":"collectionGroup","title":"OpenChannelDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModel"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewModel":{"role":"symbol","title":"SBUOpenChannelSettingsViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewModel"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewModel/channel(_:userDidEnter:)":{"role":"symbol","title":"channel(_:userDidEnter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModel\/channel(_:userDidEnter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userDidEnter:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewmodel\/channel(_:userdidenter:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewModel/channel(_:userDidExit:)":{"role":"symbol","title":"channel(_:userDidExit:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidExit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModel\/channel(_:userDidExit:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userDidExit:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewmodel\/channel(_:userdidexit:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModel\/channel(_:userDidEnter:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModel\/channel(_:userDidExit:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewModel\/title","value":"SBUOpenChannelSettingsViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewModel\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewModel~1channel(_:userDidEnter:)\/title","value":"channel:userDidEnter:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewModel~1channel(_:userDidEnter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidEnter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewModel~1channel(_:userDidExit:)\/title","value":"channel:userDidExit:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewModel~1channel(_:userDidExit:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidExit:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}