{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewModel","text":"SBURegisterOperatorViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegisterOperatorIds"},{"kind":"text","text":" "},{"kind":"internalParam","text":"operatorIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatorviewmodel(_:didregisteroperatorids:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatorviewmodel(_:didregisteroperatorids:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorViewModel(_:didRegisterOperatorIds:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when it has registered operators with their IDs."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegisterOperatorIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"title":"registerOperatorViewModel(_:didRegisterOperatorIds:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewController(im)registerOperatorViewModel:didRegisterOperatorIds:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"registerOperatorViewModel:didRegisterOperatorIds:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorViewModel(_:didRegisterOperatorIds:)":{"role":"symbol","title":"registerOperatorViewModel(_:didRegisterOperatorIds:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegisterOperatorIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Called when it has registered operators with their IDs."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorViewModel(_:didRegisterOperatorIds:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorViewModel:didRegisterOperatorIds:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatorviewmodel(_:didregisteroperatorids:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController":{"role":"symbol","title":"SBURegisterOperatorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewModel":{"role":"symbol","title":"SBURegisterOperatorViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewModel"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerOperatorViewModel:didRegisterOperatorIds:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorViewModel:didRegisterOperatorIds:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerOperatorViewModel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewModel","text":"SBURegisterOperatorViewModel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":" "},{"kind":"identifier","text":"didRegisterOperatorIds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"operatorIds"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorViewModel(_:didRegisterOperatorIds:)\/title","value":"registerOperatorViewModel:didRegisterOperatorIds:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorViewModel(_:didRegisterOperatorIds:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorViewModel:didRegisterOperatorIds:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/title","value":"SBURegisterOperatorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/fragments","value":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewModel\/title","value":"SBURegisterOperatorViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewModel\/fragments","value":[{"kind":"identifier","text":"SBURegisterOperatorViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}