{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC","text":"SBURegisterOperatorModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModule\/Header","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC6HeaderC","text":"Header"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":" "},{"kind":"internalParam","text":"leftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"component","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUInviteUserModule.Header"},{"type":"text","text":" object"}]}]},{"name":"leftItem","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormodule(_:didtapleftitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormodule(_:didtapleftitem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didTapLeftItem:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" was selected."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"title":"registerOperatorModule(_:didTapLeftItem:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewController(im)registerOperatorModule:didTapLeftItem:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"registerOperatorModule:didTapLeftItem:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController":{"role":"symbol","title":"SBURegisterOperatorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorModule":{"role":"symbol","title":"SBURegisterOperatorModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorModule"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorModule"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatormodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorModule(_:didTapLeftItem:)":{"role":"symbol","title":"registerOperatorModule(_:didTapLeftItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" was selected."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didTapLeftItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorModule:didTapLeftItem:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormodule(_:didtapleftitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/Header":{"role":"symbol","title":"Header","fragments":[{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"text","text":"SBUMessageSearchModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorModule/Header":{"role":"symbol","title":"SBURegisterOperatorModule.Header","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"codeVoice","code":"SBURegisterOperatorModule"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This class consists of titleView, leftBarButton, and rightBarButton."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModule\/Header","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Header"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatormodule\/header"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerOperatorModule:didTapLeftItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorModule:didTapLeftItem:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerOperatorModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)Header","text":"Header"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapLeftItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"leftItem"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/title","value":"SBURegisterOperatorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/fragments","value":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didTapLeftItem:)\/title","value":"registerOperatorModule:didTapLeftItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didTapLeftItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorModule:didTapLeftItem:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}