{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerSelectedUsers"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registerselectedusers()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registerselectedusers()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerSelectedUsers()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function calls "},{"type":"codeVoice","code":"registerAsOperators"},{"type":"text","text":" function."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerSelectedUsers"},{"kind":"text","text":"()"}],"title":"registerSelectedUsers()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewController(im)registerSelectedUsers","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"registerSelectedUsers"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController":{"role":"symbol","title":"SBURegisterOperatorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerSelectedUsers()":{"role":"symbol","title":"registerSelectedUsers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerSelectedUsers"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function calls "},{"type":"codeVoice","code":"registerAsOperators"},{"type":"text","text":" function."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerSelectedUsers()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerSelectedUsers"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registerselectedusers()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerSelectedUsers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerSelectedUsers"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerSelectedUsers"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/title","value":"SBURegisterOperatorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/fragments","value":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerSelectedUsers()\/title","value":"registerSelectedUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerSelectedUsers()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerSelectedUsers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}