{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/setupviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/setupviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/setupViews()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function setups views."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"title":"setupViews()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewController(im)setupViews","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"setupViews"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/setupViews()":{"role":"symbol","title":"setupViews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function setups views."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/setupViews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupViews"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/setupviews()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController":{"role":"symbol","title":"SBURegisterOperatorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setupViews"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1setupViews()\/title","value":"setupViews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1setupViews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/title","value":"SBURegisterOperatorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/fragments","value":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}