{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannelWithSelectedUsers"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/createchannelwithselectedusers()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/createchannelwithselectedusers()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController\/createChannelWithSelectedUsers()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function creates channel using the "},{"type":"codeVoice","code":"selectedUserList"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannelWithSelectedUsers"},{"kind":"text","text":"()"}],"title":"createChannelWithSelectedUsers()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUCreateChannelViewController(im)createChannelWithSelectedUsers","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"createChannelWithSelectedUsers"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelViewController":{"role":"symbol","title":"SBUCreateChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelViewController/createChannelWithSelectedUsers()":{"role":"symbol","title":"createChannelWithSelectedUsers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannelWithSelectedUsers"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function creates channel using the "},{"type":"codeVoice","code":"selectedUserList"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController\/createChannelWithSelectedUsers()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createChannelWithSelectedUsers"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/createchannelwithselectedusers()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createChannelWithSelectedUsers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createChannelWithSelectedUsers"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"createChannelWithSelectedUsers"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController\/title","value":"SBUCreateChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUCreateChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController~1createChannelWithSelectedUsers()\/title","value":"createChannelWithSelectedUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController~1createChannelWithSelectedUsers()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createChannelWithSelectedUsers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}