{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannelModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelModule","preciseIdentifier":"s:13SendbirdUIKit22SBUCreateChannelModuleC","text":"SBUCreateChannelModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelModule\/Header","preciseIdentifier":"s:13SendbirdUIKit22SBUCreateChannelModuleC6HeaderC","text":"Header"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":" "},{"kind":"internalParam","text":"leftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"component","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUCreateChannelModule.Header"},{"type":"text","text":" object"}]}]},{"name":"leftItem","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/createchannelmodule(_:didtapleftitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/createchannelmodule(_:didtapleftitem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController\/createChannelModule(_:didTapLeftItem:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" was selected."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUCreateChannelModule","preciseIdentifier":"s:13SendbirdUIKit22SBUCreateChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit22SBUCreateChannelModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"title":"createChannelModule(_:didTapLeftItem:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUCreateChannelViewController(im)createChannelModule:didTapLeftItem:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"createChannelModule:didTapLeftItem:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelViewController":{"role":"symbol","title":"SBUCreateChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelViewController/createChannelModule(_:didTapLeftItem:)":{"role":"symbol","title":"createChannelModule(_:didTapLeftItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUCreateChannelModule","preciseIdentifier":"s:13SendbirdUIKit22SBUCreateChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit22SBUCreateChannelModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" was selected."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController\/createChannelModule(_:didTapLeftItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createChannelModule:didTapLeftItem:"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/createchannelmodule(_:didtapleftitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelModule":{"role":"symbol","title":"SBUCreateChannelModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateChannelModule"}],"abstract":[{"type":"text","text":"The class that represents the module for creating a new channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateChannelModule"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelModule/Header":{"role":"symbol","title":"SBUCreateChannelModule.Header","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"codeVoice","code":"SBUCreateChannelModule"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This class consists of titleView, leftBarButton, and rightBarButton."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelModule\/Header","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Header"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelmodule\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/Header":{"role":"symbol","title":"Header","fragments":[{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"text","text":"SBUMessageSearchModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/header"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createChannelModule:didTapLeftItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createChannelModule:didTapLeftItem:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"createChannelModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)Header","text":"Header"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapLeftItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"leftItem"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController\/title","value":"SBUCreateChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUCreateChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController~1createChannelModule(_:didTapLeftItem:)\/title","value":"createChannelModule:didTapLeftItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController~1createChannelModule(_:didTapLeftItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createChannelModule:didTapLeftItem:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}