{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissAndMoveToChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Created channel"}]}]},{"name":"messageListParams","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"messageListParams"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.2.6"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/dismissandmovetochannel(_:messagelistparams:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/dismissandmovetochannel(_:messagelistparams:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController\/dismissAndMoveToChannel(_:messageListParams:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function dismisses "},{"type":"codeVoice","code":"createViewController"},{"type":"text","text":" and moves to created channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissAndMoveToChannel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"?)"}],"title":"dismissAndMoveToChannel(_:messageListParams:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUCreateChannelViewController(im)dismissAndMoveToChannel:messageListParams:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"dismissAndMoveToChannel:messageListParams:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelViewController":{"role":"symbol","title":"SBUCreateChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelViewController/dismissAndMoveToChannel(_:messageListParams:)":{"role":"symbol","title":"dismissAndMoveToChannel(_:messageListParams:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissAndMoveToChannel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"This function dismisses "},{"type":"codeVoice","code":"createViewController"},{"type":"text","text":" and moves to created channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController\/dismissAndMoveToChannel(_:messageListParams:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dismissAndMoveToChannel:messageListParams:"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/dismissandmovetochannel(_:messagelistparams:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dismissAndMoveToChannel:messageListParams:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissAndMoveToChannel:messageListParams:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"dismissAndMoveToChannel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDBaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageListParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDMessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messageListParams"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController\/title","value":"SBUCreateChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUCreateChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController~1dismissAndMoveToChannel(_:messageListParams:)\/title","value":"dismissAndMoveToChannel:messageListParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController~1dismissAndMoveToChannel(_:messageListParams:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dismissAndMoveToChannel:messageListParams:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}