{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClickCreate"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/onclickcreate()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/onclickcreate()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController\/onClickCreate()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onClickCreate"}],"role":"symbol","title":"onClickCreate()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClickCreate"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUCreateChannelViewController(im)onClickCreate","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelViewController/onClickCreate()":{"deprecated":true,"role":"symbol","title":"onClickCreate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onClickCreate"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController\/onClickCreate()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onClickCreate"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller\/onclickcreate()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelViewController":{"role":"symbol","title":"SBUCreateChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onClickCreate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onClickCreate"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onClickCreate"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController~1onClickCreate()\/title","value":"onClickCreate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController~1onClickCreate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onClickCreate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController\/title","value":"SBUCreateChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUCreateChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}