{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelInfoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUChannelInfoHeaderView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUChannelInfoHeaderView","text":"SBUChannelInfoHeaderView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/channelinfoview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/channelinfoview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController\/channelInfoView","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"channelInfoView"}],"role":"symbol","title":"channelInfoView","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelInfoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUChannelInfoHeaderView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUChannelInfoHeaderView"}],"symbolKind":"property","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUOpenChannelViewController(py)channelInfoView","extendedModule":"SendbirdUIKit","platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This property has been moved to `SBUOpenChannelModule.Header`."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewController/channelInfoView":{"deprecated":true,"role":"symbol","title":"channelInfoView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelInfoView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUChannelInfoHeaderView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUChannelInfoHeaderView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController\/channelInfoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelInfoView"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/channelinfoview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUChannelInfoHeaderView":{"role":"symbol","title":"SBUChannelInfoHeaderView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUChannelInfoHeaderView"}],"abstract":[{"type":"text","text":"A view contains a channel information such as cover image, channel name and info button."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUChannelInfoHeaderView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUChannelInfoHeaderView"}],"url":"\/documentation\/sendbirduikit\/sbuchannelinfoheaderview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewController":{"role":"symbol","title":"SBUOpenChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"channelInfoView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"channelInfoView"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUChannelInfoHeaderView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUChannelInfoHeaderView","text":"SBUChannelInfoHeaderView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"channelInfoView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController~1channelInfoView\/title","value":"channelInfoView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController~1channelInfoView\/fragments","value":[{"kind":"identifier","text":"channelInfoView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUChannelInfoHeaderView\/title","value":"SBUChannelInfoHeaderView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUChannelInfoHeaderView\/fragments","value":[{"kind":"identifier","text":"SBUChannelInfoHeaderView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController\/title","value":"SBUOpenChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}