{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelModule","preciseIdentifier":"s:13SendbirdUIKit20SBUOpenChannelModuleC","text":"SBUOpenChannelModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelModule\/Media","preciseIdentifier":"s:13SendbirdUIKit20SBUOpenChannelModuleC5MediaC","text":"Media"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/mediacomponent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/mediacomponent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController\/mediaComponent","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelModule","preciseIdentifier":"s:13SendbirdUIKit20SBUOpenChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Media","preciseIdentifier":"s:13SendbirdUIKit20SBUOpenChannelModuleC5MediaC"},{"kind":"text","text":"?"}],"title":"mediaComponent","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelViewController(py)mediaComponent","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"mediaComponent"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewController/mediaComponent":{"role":"symbol","title":"mediaComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"mediaComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelModule","preciseIdentifier":"s:13SendbirdUIKit20SBUOpenChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Media","preciseIdentifier":"s:13SendbirdUIKit20SBUOpenChannelModuleC5MediaC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController\/mediaComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"mediaComponent"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/mediacomponent"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelModule/Media":{"role":"symbol","title":"SBUOpenChannelModule.Media","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Media"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"SBUOpenChannelModule"},{"type":"text","text":"’s component class that represents media."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelModule\/Media","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Media"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelmodule\/media"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelModule":{"role":"symbol","title":"SBUOpenChannelModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelModule"}],"abstract":[{"type":"text","text":"The class that represents the open channel module"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelModule"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewController":{"role":"symbol","title":"SBUOpenChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mediaComponent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"mediaComponent"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Media","preciseIdentifier":"c:objc(cs)Media"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mediaComponent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController~1mediaComponent\/title","value":"mediaComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController~1mediaComponent\/fragments","value":[{"kind":"identifier","text":"mediaComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController\/title","value":"SBUOpenChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}