{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayMediaView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"overlaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"overlaying","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If it’s "},{"type":"codeVoice","code":"true"},{"type":"text","text":", "},{"type":"codeVoice","code":"mediaViewRatio"},{"type":"text","text":" will be set to "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":". If it’s "},{"type":"codeVoice","code":"false"},{"type":"text","text":", "},{"type":"codeVoice","code":"mediaViewRatio"},{"type":"text","text":" will be set to "},{"type":"codeVoice","code":"1 - messageListRatio"},{"type":"text","text":"."}]}]},{"name":"messageListRatio","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A relative ratio value of  message list to entire screen."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"codeListing","syntax":null,"code":["\/\/ Enable overlay mode","self.overlayMediaView(true, messageListRatio: 0.4)","","\/\/ Disable overlay mode","self.overlayMediaView(false, messageListRatio: 0.3)    \/\/ mediaViewRatio is 0.7"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/overlaymediaview(_:messagelistratio:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/overlaymediaview(_:messagelistratio:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController\/overlayMediaView(_:messageListRatio:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Overlays the media view."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayMediaView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"title":"overlayMediaView(_:messageListRatio:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelViewController(im)overlayMediaView:messageListRatio:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"overlayMediaView:messageListRatio:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewController/overlayMediaView(_:messageListRatio:)":{"role":"symbol","title":"overlayMediaView(_:messageListRatio:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayMediaView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Overlays the media view."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController\/overlayMediaView(_:messageListRatio:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"overlayMediaView:messageListRatio:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/overlaymediaview(_:messagelistratio:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewController":{"role":"symbol","title":"SBUOpenChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"overlayMediaView:messageListRatio:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"overlayMediaView:messageListRatio:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"overlayMediaView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"overlaying"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageListRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":")"},{"kind":"internalParam","text":"messageListRatio"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController~1overlayMediaView(_:messageListRatio:)\/title","value":"overlayMediaView:messageListRatio:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController~1overlayMediaView(_:messageListRatio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"overlayMediaView:messageListRatio:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController\/title","value":"SBUOpenChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}