{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userMessageCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelBaseMessageCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelBaseMessageCell","text":"SBUOpenChannelBaseMessageCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nib"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/register(usermessagecell:nib:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/register(usermessagecell:nib:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController\/register(userMessageCell:nib:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"registerWithUserMessageCell:nib:"}],"role":"symbol","title":"register(userMessageCell:nib:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userMessageCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelBaseMessageCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelBaseMessageCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nib"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUOpenChannelViewController(im)registerWithUserMessageCell:nib:","extendedModule":"SendbirdUIKit","platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This function has been moved to `SBUOpenChannelModule.List`."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelBaseMessageCell":{"role":"symbol","title":"SBUOpenChannelBaseMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelBaseMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelBaseMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelBaseMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelbasemessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewController/register(userMessageCell:nib:)":{"deprecated":true,"role":"symbol","title":"register(userMessageCell:nib:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userMessageCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelBaseMessageCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelBaseMessageCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nib"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController\/register(userMessageCell:nib:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerWithUserMessageCell:nib:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller\/register(usermessagecell:nib:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewController":{"role":"symbol","title":"SBUOpenChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerWithUserMessageCell:nib:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerWithUserMessageCell:nib:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerWithUserMessageCell:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelBaseMessageCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelBaseMessageCell","text":"SBUOpenChannelBaseMessageCell"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"userMessageCell"},{"kind":"text","text":" "},{"kind":"identifier","text":"nib:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UINib","preciseIdentifier":"c:objc(cs)UINib"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"nib"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelBaseMessageCell\/title","value":"SBUOpenChannelBaseMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelBaseMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelBaseMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController~1register(userMessageCell:nib:)\/title","value":"registerWithUserMessageCell:nib:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController~1register(userMessageCell:nib:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerWithUserMessageCell:nib:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController\/title","value":"SBUOpenChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}