{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidEnter"},{"kind":"text","text":" "},{"kind":"internalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewmodel\/channel(_:userdidenter:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewmodel\/channel(_:userdidenter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel\/channel(_:userDidEnter:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"OpenChannelDelegate.channel(_:userDidEnter:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"channel:userDidEnter:"}],"role":"symbol","title":"channel(_:userDidEnter:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUOpenChannelViewModel(im)channel:userDidEnter:","extendedModule":"SendbirdUIKit","modules":[{"name":"SendbirdUIKit"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel\/OpenChannelDelegate-Implementations"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewModel/channel(_:userDidEnter:)":{"role":"symbol","title":"channel(_:userDidEnter:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidEnter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel\/channel(_:userDidEnter:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userDidEnter:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewmodel\/channel(_:userdidenter:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewModel":{"role":"symbol","title":"SBUOpenChannelViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelViewModel"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewModel/OpenChannelDelegate-Implementations":{"role":"collectionGroup","title":"OpenChannelDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel\/OpenChannelDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/sbuopenchannelviewmodel\/openchanneldelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"channel:userDidEnter:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidEnter:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"channel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDOpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidEnter:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDUser","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"user"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewModel~1channel(_:userDidEnter:)\/title","value":"channel:userDidEnter:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewModel~1channel(_:userDidEnter:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidEnter:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewModel\/title","value":"SBUOpenChannelViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewModel\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}