{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidExit"},{"kind":"text","text":" "},{"kind":"internalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewmodel\/channel(_:userdidexit:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelviewmodel\/channel(_:userdidexit:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel\/channel(_:userDidExit:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"OpenChannelDelegate.channel(_:userDidExit:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidExit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"title":"channel(_:userDidExit:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUOpenChannelViewModel(im)channel:userDidExit:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"channel:userDidExit:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel\/OpenChannelDelegate-Implementations"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewModel/OpenChannelDelegate-Implementations":{"role":"collectionGroup","title":"OpenChannelDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel\/OpenChannelDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/sbuopenchannelviewmodel\/openchanneldelegate-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewModel/channel(_:userDidExit:)":{"role":"symbol","title":"channel(_:userDidExit:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userDidExit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel\/channel(_:userDidExit:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:userDidExit:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewmodel\/channel(_:userdidexit:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewModel":{"role":"symbol","title":"SBUOpenChannelViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelViewModel"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"channel:userDidExit:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidExit:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"channel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDOpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidExit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDUser","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUser"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"user"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewModel~1channel(_:userDidExit:)\/title","value":"channel:userDidExit:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewModel~1channel(_:userDidExit:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:userDidExit:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewModel\/title","value":"SBUOpenChannelViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewModel\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}