{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelMessageWebView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelMessageWebView","text":"SBUOpenChannelMessageWebView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelusermessagecell\/webview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelusermessagecell\/webview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelUserMessageCell\/webView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelMessageWebView"},{"type":"text","text":" which represents a preview of the web link"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelMessageWebView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelMessageWebView"}],"title":"webView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelUserMessageCell(py)webView","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"webView"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelUserMessageCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelUserMessageCell":{"role":"symbol","title":"SBUOpenChannelUserMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelUserMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelUserMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelUserMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelusermessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelMessageWebView":{"role":"symbol","title":"SBUOpenChannelMessageWebView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelMessageWebView"}],"abstract":[{"type":"text","text":"A view shows preview of web link on the message in the open channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelMessageWebView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelMessageWebView"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelmessagewebview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelUserMessageCell/webView":{"role":"symbol","title":"webView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelMessageWebView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelMessageWebView"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelMessageWebView"},{"type":"text","text":" which represents a preview of the web link"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelUserMessageCell\/webView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelusermessagecell\/webview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"webView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"webView"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelMessageWebView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelMessageWebView","text":"SBUOpenChannelMessageWebView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"webView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelUserMessageCell\/title","value":"SBUOpenChannelUserMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelUserMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelUserMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelMessageWebView\/title","value":"SBUOpenChannelMessageWebView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelMessageWebView\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelMessageWebView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelUserMessageCell~1webView\/title","value":"webView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelUserMessageCell~1webView\/fragments","value":[{"kind":"identifier","text":"webView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}