{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/mediaresourcetype\/document"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/mediaresourcetype\/document"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MediaResourceType\/document","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"}],"title":"MediaResourceType.document","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdUIKit@E@MediaResourceType@MediaResourceTypeDocument","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MediaResourceTypeDocument"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MediaResourceType"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MediaResourceType/document":{"role":"symbol","title":"MediaResourceType.document","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MediaResourceType\/document","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MediaResourceTypeDocument"}],"url":"\/documentation\/sendbirduikit\/mediaresourcetype\/document"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MediaResourceType":{"role":"symbol","title":"MediaResourceType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MediaResourceType"}],"abstract":[{"type":"text","text":"This is an enumeration used to select a media resource type."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MediaResourceType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MediaResourceType"}],"url":"\/documentation\/sendbirduikit\/mediaresourcetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MediaResourceTypeDocument"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MediaResourceTypeDocument"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MediaResourceTypeDocument"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MediaResourceType~1document\/title","value":"MediaResourceTypeDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MediaResourceType~1document\/fragments","value":[{"kind":"identifier","text":"MediaResourceTypeDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MediaResourceType\/title","value":"MediaResourceType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MediaResourceType\/fragments","value":[{"kind":"identifier","text":"MediaResourceType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}