{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapQuotedMessageView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuquotedbasemessageview\/didtapquotedmessageview(sender:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuquotedbasemessageview\/didtapquotedmessageview(sender:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUQuotedBaseMessageView\/didTapQuotedMessageView(sender:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The action invokes  "},{"type":"codeVoice","code":"SBUQuotedMessageViewDelegate didTapQuotedMessageView(_:)"},{"type":"text","text":" method and scrolls to parent message cell."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapQuotedMessageView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"title":"didTapQuotedMessageView(sender:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUQuotedBaseMessageView(im)didTapQuotedMessageViewWithSender:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"didTapQuotedMessageViewWithSender:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUQuotedBaseMessageView"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUQuotedBaseMessageView/didTapQuotedMessageView(sender:)":{"role":"symbol","title":"didTapQuotedMessageView(sender:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapQuotedMessageView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sender"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The action invokes  "},{"type":"codeVoice","code":"SBUQuotedMessageViewDelegate didTapQuotedMessageView(_:)"},{"type":"text","text":" method and scrolls to parent message cell."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUQuotedBaseMessageView\/didTapQuotedMessageView(sender:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didTapQuotedMessageViewWithSender:"}],"url":"\/documentation\/sendbirduikit\/sbuquotedbasemessageview\/didtapquotedmessageview(sender:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUQuotedBaseMessageView":{"role":"symbol","title":"SBUQuotedBaseMessageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUQuotedBaseMessageView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUQuotedBaseMessageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUQuotedBaseMessageView"}],"url":"\/documentation\/sendbirduikit\/sbuquotedbasemessageview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"didTapQuotedMessageViewWithSender:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapQuotedMessageViewWithSender:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didTapQuotedMessageViewWithSender:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sender"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUQuotedBaseMessageView~1didTapQuotedMessageView(sender:)\/title","value":"didTapQuotedMessageViewWithSender:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUQuotedBaseMessageView~1didTapQuotedMessageView(sender:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapQuotedMessageViewWithSender:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUQuotedBaseMessageView\/title","value":"SBUQuotedBaseMessageView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUQuotedBaseMessageView\/fragments","value":[{"kind":"identifier","text":"SBUQuotedBaseMessageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}