{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextUserList"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser","text":"SBUUser"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"next user list"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"aside","style":"important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want to use this function, please set the "},{"type":"codeVoice","code":"SBUBaseSelectUserViewModelDataSource"},{"type":"text","text":" in your class."}]}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"1.1.1"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubaseselectuserviewcontroller\/nextuserlist()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubaseselectuserviewcontroller\/nextuserlist()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewController\/nextUserList()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When creating and using a user list directly, overriding this function and return the next user list."},{"type":"text","text":" "},{"type":"text","text":"Make this function return the next list each time it is called."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextUserList"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"]?"}],"title":"nextUserList()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseSelectUserViewController(im)nextUserList","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"nextUserList"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUser":{"role":"symbol","title":"SBUUser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUser"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUser"}],"url":"\/documentation\/sendbirduikit\/sbuuser"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserViewController/nextUserList()":{"role":"symbol","title":"nextUserList()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nextUserList"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"When creating and using a user list directly, overriding this function and return the next user list."},{"type":"text","text":" "},{"type":"text","text":"Make this function return the next list each time it is called."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewController\/nextUserList()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"nextUserList"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectuserviewcontroller\/nextuserlist()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserViewController":{"role":"symbol","title":"SBUBaseSelectUserViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserViewController"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectuserviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"nextUserList"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nextUserList"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<SBUUser *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"nextUserList"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/title","value":"SBUUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/fragments","value":[{"kind":"identifier","text":"SBUUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseSelectUserViewController~1nextUserList()\/title","value":"nextUserList"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseSelectUserViewController~1nextUserList()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nextUserList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseSelectUserViewController\/title","value":"SBUBaseSelectUserViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseSelectUserViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseSelectUserViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}