{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/channelmemberlisttype\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/channelmemberlisttype\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelMemberListType\/none","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"ChannelMemberListTypeNone"}],"role":"symbol","title":"ChannelMemberListType.none","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"symbolKind":"case","externalID":"c:@M@SendbirdUIKit@E@ChannelMemberListType@ChannelMemberListTypeNone","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelMemberListType"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelMemberListType":{"deprecated":true,"role":"symbol","title":"ChannelMemberListType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelMemberListType"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelMemberListType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelMemberListType"}],"url":"\/documentation\/sendbirduikit\/channelmemberlisttype"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelMemberListType/none":{"deprecated":true,"role":"symbol","title":"ChannelMemberListType.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelMemberListType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelMemberListTypeNone"}],"url":"\/documentation\/sendbirduikit\/channelmemberlisttype\/none"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ChannelMemberListTypeNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChannelMemberListTypeNone"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ChannelMemberListTypeNone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelMemberListType\/title","value":"ChannelMemberListType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelMemberListType\/fragments","value":[{"kind":"identifier","text":"ChannelMemberListType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelMemberListType~1none\/title","value":"ChannelMemberListTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelMemberListType~1none\/fragments","value":[{"kind":"identifier","text":"ChannelMemberListTypeNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}