{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSearchModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchModule","preciseIdentifier":"s:13SendbirdUIKit22SBUMessageSearchModuleC","text":"SBUMessageSearchModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchModule\/List","preciseIdentifier":"s:13SendbirdUIKit22SBUMessageSearchModuleC4ListC","text":"List"},{"kind":"text","text":", "},{"kind":"externalParam","text":"searchResultsInTableView"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of "},{"type":"codeVoice","code":"BaseMessage"},{"type":"text","text":" object."}]}]},{"kind":"parameters","parameters":[{"name":"listComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUMessageSearchModule.List"},{"type":"text","text":" object."}]}]},{"name":"tableView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"UITableView"},{"type":"text","text":" object from list component."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbumessagesearchviewcontroller\/messagesearchmodule(_:searchresultsintableview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbumessagesearchviewcontroller\/messagesearchmodule(_:searchresultsintableview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchViewController\/messageSearchModule(_:searchResultsInTableView:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Ask the data source to return the search result list."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSearchModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUMessageSearchModule","preciseIdentifier":"s:13SendbirdUIKit22SBUMessageSearchModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit22SBUMessageSearchModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"searchResultsInTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"]"}],"title":"messageSearchModule(_:searchResultsInTableView:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUMessageSearchViewController(im)messageSearchModule:searchResultsInTableView:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"messageSearchModule:searchResultsInTableView:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageSearchModule":{"role":"symbol","title":"SBUMessageSearchModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageSearchModule"}],"abstract":[{"type":"text","text":"The class that represents the message search module."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageSearchModule"}],"url":"\/documentation\/sendbirduikit\/sbumessagesearchmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageSearchViewController/messageSearchModule(_:searchResultsInTableView:)":{"role":"symbol","title":"messageSearchModule(_:searchResultsInTableView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSearchModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUMessageSearchModule","preciseIdentifier":"s:13SendbirdUIKit22SBUMessageSearchModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit22SBUMessageSearchModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"searchResultsInTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Ask the data source to return the search result list."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchViewController\/messageSearchModule(_:searchResultsInTableView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageSearchModule:searchResultsInTableView:"}],"url":"\/documentation\/sendbirduikit\/sbumessagesearchviewcontroller\/messagesearchmodule(_:searchresultsintableview:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageSearchModule/List":{"role":"symbol","title":"SBUMessageSearchModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUMessageSearchModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbumessagesearchmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageSearchViewController":{"role":"symbol","title":"SBUMessageSearchViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageSearchViewController"}],"abstract":[{"type":"text","text":"ViewController handling a message search."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageSearchViewController"}],"url":"\/documentation\/sendbirduikit\/sbumessagesearchviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageSearchModuleList":{"role":"symbol","title":"SBUMessageSearchModuleList","fragments":[{"kind":"identifier","text":"SBUMessageSearchModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUMessageSearchModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessagesearchmodulelist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"messageSearchModule:searchResultsInTableView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageSearchModule:searchResultsInTableView:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<SBDBaseMessage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"messageSearchModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUMessageSearchModuleList","text":"SBUMessageSearchModuleList"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"searchResultsInTableView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageSearchViewController~1messageSearchModule(_:searchResultsInTableView:)\/title","value":"messageSearchModule:searchResultsInTableView:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageSearchViewController~1messageSearchModule(_:searchResultsInTableView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageSearchModule:searchResultsInTableView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageSearchViewController\/title","value":"SBUMessageSearchViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageSearchViewController\/fragments","value":[{"kind":"identifier","text":"SBUMessageSearchViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}