{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseViewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewModel","text":"SBUBaseChannelSettingsViewModel"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/baseviewmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/baseviewmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController\/baseViewModel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseViewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUBaseChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewModel"},{"kind":"text","text":"?"}],"title":"baseViewModel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewController(py)baseViewModel","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"baseViewModel"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewController":{"role":"symbol","title":"SBUBaseChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewModel":{"role":"symbol","title":"SBUBaseChannelSettingsViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewModel"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewController/baseViewModel":{"role":"symbol","title":"baseViewModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseViewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUBaseChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController\/baseViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseViewModel"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/baseviewmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"baseViewModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"baseViewModel"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewModel","text":"SBUBaseChannelSettingsViewModel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"baseViewModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/title","value":"SBUBaseChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewModel\/title","value":"SBUBaseChannelSettingsViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewModel\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController~1baseViewModel\/title","value":"baseViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController~1baseViewModel\/fragments","value":[{"kind":"identifier","text":"baseViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}