{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelSettingsViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewModel","text":"SBUBaseChannelSettingsViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldDismissForChannelSettings"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"viewModel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUBaseChannelSettingsViewModel"},{"type":"text","text":" object"}]}]},{"name":"channel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"channel object. If you want to move to the channel view, put the channel object or empty the channel object to go to the channel list."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/basechannelsettingsviewmodel(_:shoulddismissforchannelsettings:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/basechannelsettingsviewmodel(_:shoulddismissforchannelsettings:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController\/baseChannelSettingsViewModel(_:shouldDismissForChannelSettings:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the channel settings should dismiss"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelSettingsViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldDismissForChannelSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?)"}],"title":"baseChannelSettingsViewModel(_:shouldDismissForChannelSettings:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewController(im)baseChannelSettingsViewModel:shouldDismissForChannelSettings:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"baseChannelSettingsViewModel:shouldDismissForChannelSettings:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewController":{"role":"symbol","title":"SBUBaseChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewController/baseChannelSettingsViewModel(_:shouldDismissForChannelSettings:)":{"role":"symbol","title":"baseChannelSettingsViewModel(_:shouldDismissForChannelSettings:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelSettingsViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldDismissForChannelSettings"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when the channel settings should dismiss"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController\/baseChannelSettingsViewModel(_:shouldDismissForChannelSettings:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseChannelSettingsViewModel:shouldDismissForChannelSettings:"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/basechannelsettingsviewmodel(_:shoulddismissforchannelsettings:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewModel":{"role":"symbol","title":"SBUBaseChannelSettingsViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewModel"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"baseChannelSettingsViewModel:shouldDismissForChannelSettings:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelSettingsViewModel:shouldDismissForChannelSettings:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"baseChannelSettingsViewModel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewModel","text":"SBUBaseChannelSettingsViewModel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldDismissForChannelSettings:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDBaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/title","value":"SBUBaseChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController~1baseChannelSettingsViewModel(_:shouldDismissForChannelSettings:)\/title","value":"baseChannelSettingsViewModel:shouldDismissForChannelSettings:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController~1baseChannelSettingsViewModel(_:shouldDismissForChannelSettings:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelSettingsViewModel:shouldDismissForChannelSettings:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewModel\/title","value":"SBUBaseChannelSettingsViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewModel\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}