{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeChannelName"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/changechannelname()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/changechannelname()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController\/changeChannelName()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function shows the channel name change popup."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeChannelName"},{"kind":"text","text":"()"}],"title":"changeChannelName()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewController(im)changeChannelName","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"changeChannelName"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewController":{"role":"symbol","title":"SBUBaseChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewController/changeChannelName()":{"role":"symbol","title":"changeChannelName()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"changeChannelName"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function shows the channel name change popup."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController\/changeChannelName()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"changeChannelName"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/changechannelname()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"changeChannelName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeChannelName"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"changeChannelName"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/title","value":"SBUBaseChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController~1changeChannelName()\/title","value":"changeChannelName"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController~1changeChannelName()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"changeChannelName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}