{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"coverImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/updatechannel(channelname:coverimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/updatechannel(channelname:coverimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController\/updateChannel(channelName:coverImage:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"updateChannelWithChannelName:coverImage:"}],"role":"symbol","title":"updateChannel(channelName:coverImage:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"coverImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewController(im)updateChannelWithChannelName:coverImage:","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This function has been moved to the `SBUBaseChannelSettingsViewModel`."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewController/updateChannel(channelName:coverImage:)":{"deprecated":true,"role":"symbol","title":"updateChannel(channelName:coverImage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"coverImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController\/updateChannel(channelName:coverImage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateChannelWithChannelName:coverImage:"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller\/updatechannel(channelname:coverimage:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewController":{"role":"symbol","title":"SBUBaseChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateChannelWithChannelName:coverImage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelWithChannelName:coverImage:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateChannelWithChannelName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelName"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"coverImage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController~1updateChannel(channelName:coverImage:)\/title","value":"updateChannelWithChannelName:coverImage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController~1updateChannel(channelName:coverImage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelWithChannelName:coverImage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/title","value":"SBUBaseChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}