{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelListModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModule","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelListModule","text":"SBUBaseChannelListModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModule\/List","preciseIdentifier":"s:13SendbirdUIKit24SBUBaseChannelListModuleC0E0C","text":"List"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelsInTableView"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The array of "},{"type":"codeVoice","code":"BaseChannel"},{"type":"text","text":" object."}]}]},{"kind":"parameters","parameters":[{"name":"listComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUOpenChannelListModule.List"},{"type":"text","text":" object."}]}]},{"name":"tableView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"UITableView"},{"type":"text","text":" object from list component."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/basechannellistmodule(_:channelsintableview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/basechannellistmodule(_:channelsintableview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/baseChannelListModule(_:channelsInTableView:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Ask the data source to return the channel list."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelListModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelListModule","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelListModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit24SBUBaseChannelListModuleC0E0C"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelsInTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"]?"}],"title":"baseChannelListModule(_:channelsInTableView:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListViewController(im)baseChannelListModule:channelsInTableView:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"baseChannelListModule:channelsInTableView:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelListModule":{"role":"symbol","title":"SBUBaseChannelListModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelListModule"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelListModule"}],"url":"\/documentation\/sendbirduikit\/sbubasechannellistmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController":{"role":"symbol","title":"SBUGroupChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController/baseChannelListModule(_:channelsInTableView:)":{"role":"symbol","title":"baseChannelListModule(_:channelsInTableView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelListModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelListModule","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelListModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit24SBUBaseChannelListModuleC0E0C"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelsInTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Ask the data source to return the channel list."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/baseChannelListModule(_:channelsInTableView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseChannelListModule:channelsInTableView:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/basechannellistmodule(_:channelsintableview:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelListModule/List":{"role":"symbol","title":"SBUBaseChannelListModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUBaseChannelListModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbubasechannellistmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelListModuleList":{"role":"symbol","title":"SBUBaseChannelListModuleList","fragments":[{"kind":"identifier","text":"SBUBaseChannelListModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUBaseChannelListModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbubasechannellistmodulelist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"baseChannelListModule:channelsInTableView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelListModule:channelsInTableView:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<SBDBaseChannel *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"baseChannelListModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelListModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelListModuleList","text":"SBUBaseChannelListModuleList"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelsInTableView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelListModule\/title","value":"SBUBaseChannelListModule"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelListModule\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelListModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/title","value":"SBUGroupChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1baseChannelListModule(_:channelsInTableView:)\/title","value":"baseChannelListModule:channelsInTableView:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1baseChannelListModule(_:channelsInTableView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelListModule:channelsInTableView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}