{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelListModuleDidSelectRetry"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListModule","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC","text":"SBUGroupChannelListModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListModule\/List","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC0E0C","text":"List"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUGroupChannelListModule.List"},{"type":"text","text":" object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/channellistmoduledidselectretry(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/channellistmoduledidselectretry(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/channelListModuleDidSelectRetry(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the retry button was selected from the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelListModuleDidSelectRetry"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelListModule","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC0E0C"},{"kind":"text","text":")"}],"title":"channelListModuleDidSelectRetry(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListViewController(im)channelListModuleDidSelectRetry:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"channelListModuleDidSelectRetry:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListModule/List":{"role":"symbol","title":"SBUGroupChannelListModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUGroupChannelListModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController/channelListModuleDidSelectRetry(_:)":{"role":"symbol","title":"channelListModuleDidSelectRetry(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelListModuleDidSelectRetry"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelListModule","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC0E0C"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the retry button was selected from the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/channelListModuleDidSelectRetry(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelListModuleDidSelectRetry:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/channellistmoduledidselectretry(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListModuleList":{"role":"symbol","title":"SBUGroupChannelListModuleList","fragments":[{"kind":"identifier","text":"SBUGroupChannelListModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUGroupChannelListModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbugroupchannellistmodulelist"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController":{"role":"symbol","title":"SBUGroupChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListModule":{"role":"symbol","title":"SBUGroupChannelListModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListModule"}],"abstract":[{"type":"text","text":"The class that represents the list of the group channel module"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListModule"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistmodule"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"channelListModuleDidSelectRetry:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelListModuleDidSelectRetry:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"channelListModuleDidSelectRetry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListModuleList","text":"SBUGroupChannelListModuleList"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1channelListModuleDidSelectRetry(_:)\/title","value":"channelListModuleDidSelectRetry:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1channelListModuleDidSelectRetry(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelListModuleDidSelectRetry:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/title","value":"SBUGroupChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}