{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelListViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListViewModel","text":"SBUGroupChannelListViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLeaveChannel"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"viewModel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUGroupChannelListViewModel"},{"type":"text","text":" object."}]}]},{"name":"channel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The channel that the current user has been left."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/groupchannellistviewmodel(_:didleavechannel:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/groupchannellistviewmodel(_:didleavechannel:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/groupChannelListViewModel(_:didLeaveChannel:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the current user has left a channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelListViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLeaveChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"title":"groupChannelListViewModel(_:didLeaveChannel:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListViewController(im)groupChannelListViewModel:didLeaveChannel:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"groupChannelListViewModel:didLeaveChannel:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModel":{"role":"symbol","title":"SBUGroupChannelListViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewModel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController":{"role":"symbol","title":"SBUGroupChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController/groupChannelListViewModel(_:didLeaveChannel:)":{"role":"symbol","title":"groupChannelListViewModel(_:didLeaveChannel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelListViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelListViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didLeaveChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the current user has left a channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/groupChannelListViewModel(_:didLeaveChannel:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelListViewModel:didLeaveChannel:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/groupchannellistviewmodel(_:didleavechannel:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupChannelListViewModel:didLeaveChannel:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelListViewModel:didLeaveChannel:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupChannelListViewModel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListViewModel","text":"SBUGroupChannelListViewModel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":" "},{"kind":"identifier","text":"didLeaveChannel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDGroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel\/title","value":"SBUGroupChannelListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/title","value":"SBUGroupChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1groupChannelListViewModel(_:didLeaveChannel:)\/title","value":"groupChannelListViewModel:didLeaveChannel:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1groupChannelListViewModel(_:didLeaveChannel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelListViewModel:didLeaveChannel:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}