{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListModule","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC","text":"SBUGroupChannelListModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListModule\/Header","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC6HeaderC","text":"Header"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/headercomponent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/headercomponent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/headerComponent","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUGroupChannelListModule","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC6HeaderC"},{"kind":"text","text":"?"}],"title":"headerComponent","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListViewController(py)headerComponent","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"headerComponent"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListModule/Header":{"role":"symbol","title":"SBUGroupChannelListModule.Header","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represents the header of "},{"type":"codeVoice","code":"SBUGroupChannelListModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListModule\/Header","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Header"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistmodule\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController/headerComponent":{"role":"symbol","title":"headerComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUGroupChannelListModule","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit25SBUGroupChannelListModuleC6HeaderC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/headerComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"headerComponent"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/headercomponent"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListModule":{"role":"symbol","title":"SBUGroupChannelListModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListModule"}],"abstract":[{"type":"text","text":"The class that represents the list of the group channel module"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListModule"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/Header":{"role":"symbol","title":"Header","fragments":[{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"text","text":"SBUMessageSearchModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController":{"role":"symbol","title":"SBUGroupChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"headerComponent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"headerComponent"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)Header","text":"Header"},{"kind":"text","text":" * "},{"kind":"identifier","text":"headerComponent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1headerComponent\/title","value":"headerComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1headerComponent\/fragments","value":[{"kind":"identifier","text":"headerComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/title","value":"SBUGroupChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}