{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelListQuery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channelListQuery","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Your own "},{"type":"codeVoice","code":"GroupChannelListQuery"},{"type":"text","text":" object"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the example below for query generation."}]},{"type":"codeListing","syntax":null,"code":["    let params = GroupChannelListQueryParams()","    params.includeEmptyChannel = false","    params.includeFrozenChannel = true","    let query = GroupChannel.createMyGroupChannelListQuery(params: params)","    ..."]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"1.0.11"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/init(channellistquery:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/init(channellistquery:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/init(channelListQuery:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"You can initialize the class through this function."},{"type":"text","text":" "},{"type":"text","text":"If you have "},{"type":"codeVoice","code":"channelListQuery"},{"type":"text","text":", please set it. If not set, it is used as default value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelListQuery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery"},{"kind":"text","text":"?)"}],"title":"init(channelListQuery:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListViewController(im)initWithChannelListQuery:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithChannelListQuery:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController/init(channelListQuery:)":{"role":"symbol","title":"init(channelListQuery:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelListQuery"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"You can initialize the class through this function."},{"type":"text","text":" "},{"type":"text","text":"If you have "},{"type":"codeVoice","code":"channelListQuery"},{"type":"text","text":", please set it. If not set, it is used as default value."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/init(channelListQuery:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithChannelListQuery:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/init(channellistquery:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController":{"role":"symbol","title":"SBUGroupChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithChannelListQuery:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannelListQuery:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithChannelListQuery:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDGroupChannelListQuery","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelListQuery"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelListQuery"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1init(channelListQuery:)\/title","value":"initWithChannelListQuery:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1init(channelListQuery:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannelListQuery:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/title","value":"SBUGroupChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}