{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftBarButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/leftbarbutton"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/leftbarbutton"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/leftBarButton","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"leftBarButton"}],"role":"symbol","title":"leftBarButton","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftBarButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUGroupChannelListViewController(py)leftBarButton","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This property has been moved to the `SBUGroupChannelListModule.Header`."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController/leftBarButton":{"deprecated":true,"role":"symbol","title":"leftBarButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftBarButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/leftBarButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"leftBarButton"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/leftbarbutton"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController":{"role":"symbol","title":"SBUGroupChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"leftBarButton"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"leftBarButton"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":" * "},{"kind":"identifier","text":"leftBarButton"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1leftBarButton\/title","value":"leftBarButton"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1leftBarButton\/fragments","value":[{"kind":"identifier","text":"leftBarButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/title","value":"SBUGroupChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}