{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"channelURL","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"channel url for use in channelViewController."}]}]},{"name":"messageListParams","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If there is a messageListParams set directly for use in Channel, set it up here"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want to use a custom channelViewController, override it and implement it."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/showchannel(channelurl:messagelistparams:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/showchannel(channelurl:messagelistparams:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/showChannel(channelURL:messageListParams:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is a function that shows the channelViewController."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"?)"}],"title":"showChannel(channelURL:messageListParams:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelListViewController(im)showChannelWithChannelURL:messageListParams:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"showChannelWithChannelURL:messageListParams:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController/showChannel(channelURL:messageListParams:)":{"role":"symbol","title":"showChannel(channelURL:messageListParams:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageListParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"This is a function that shows the channelViewController."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/showChannel(channelURL:messageListParams:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showChannelWithChannelURL:messageListParams:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/showchannel(channelurl:messagelistparams:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController":{"role":"symbol","title":"SBUGroupChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showChannelWithChannelURL:messageListParams:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showChannelWithChannelURL:messageListParams:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showChannelWithChannelURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageListParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDMessageListParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageListParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messageListParams"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1showChannel(channelURL:messageListParams:)\/title","value":"showChannelWithChannelURL:messageListParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1showChannel(channelURL:messageListParams:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showChannelWithChannelURL:messageListParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/title","value":"SBUGroupChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}