{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"upsertChannels"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"channels"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"needReload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/upsertchannels(_:needreload:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/upsertchannels(_:needreload:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/upsertChannels(_:needReload:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"upsertChannels:needReload:"}],"role":"symbol","title":"upsertChannels(_:needReload:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"upsertChannels"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"needReload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUGroupChannelListViewController(im)upsertChannels:needReload:","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This function has been moved to the `SBUGroupChannelListViewModel`."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController/upsertChannels(_:needReload:)":{"deprecated":true,"role":"symbol","title":"upsertChannels(_:needReload:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"upsertChannels"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"needReload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController\/upsertChannels(_:needReload:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"upsertChannels:needReload:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller\/upsertchannels(_:needreload:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController":{"role":"symbol","title":"SBUGroupChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"upsertChannels:needReload:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"upsertChannels:needReload:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"upsertChannels:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBDGroupChannel *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channels"},{"kind":"text","text":" "},{"kind":"identifier","text":"needReload:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"needReload"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1upsertChannels(_:needReload:)\/title","value":"upsertChannels:needReload:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController~1upsertChannels(_:needReload:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"upsertChannels:needReload:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/title","value":"SBUGroupChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}