{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/channeledittype\/name"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/channeledittype\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/name","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"}],"title":"ChannelEditType.name","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdUIKit@E@ChannelEditType@ChannelEditTypeName","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChannelEditTypeName"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelEditType":{"role":"symbol","title":"ChannelEditType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelEditType"}],"abstract":[{"type":"text","text":"This is an enumeration used to select the channel editing type."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelEditType"}],"url":"\/documentation\/sendbirduikit\/channeledittype"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelEditType/name":{"role":"symbol","title":"ChannelEditType.name","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelEditTypeName"}],"url":"\/documentation\/sendbirduikit\/channeledittype\/name"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ChannelEditTypeName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChannelEditTypeName"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ChannelEditTypeName"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelEditType\/title","value":"ChannelEditType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelEditType\/fragments","value":[{"kind":"identifier","text":"ChannelEditType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelEditType~1name\/title","value":"ChannelEditTypeName"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelEditType~1name\/fragments","value":[{"kind":"identifier","text":"ChannelEditTypeName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}