# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SendBirdUIKit-Sample' do
  use_modular_headers!
  pod 'SendBirdSDK', '~> 3.1.13'
end

target 'NotificationService' do
  use_modular_headers!
  pod 'SendBirdSDK', '~> 3.1.13'
end
