{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC","text":"SBUOpenChannelSettingsModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModule\/List","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC4ListC","text":"List"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/listcomponent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/listcomponent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/listComponent","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC4ListC"},{"kind":"text","text":"?"}],"title":"listComponent","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelSettingsViewController(py)listComponent","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"listComponent"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/listComponent":{"role":"symbol","title":"listComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC4ListC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/listComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"listComponent"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/listcomponent"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsModule":{"role":"symbol","title":"SBUOpenChannelSettingsModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsModule"}],"abstract":[{"type":"text","text":"The class that represents the open channel setting module."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsModule"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsModule/List":{"role":"symbol","title":"SBUOpenChannelSettingsModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUOpenChannelSettingsModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsModuleList":{"role":"symbol","title":"SBUOpenChannelSettingsModuleList","fragments":[{"kind":"identifier","text":"SBUOpenChannelSettingsModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUOpenChannelSettingsModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsmodulelist"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController":{"role":"symbol","title":"SBUOpenChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"listComponent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"listComponent"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelSettingsModuleList","text":"SBUOpenChannelSettingsModuleList"},{"kind":"text","text":" * "},{"kind":"identifier","text":"listComponent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1listComponent\/title","value":"listComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1listComponent\/fragments","value":[{"kind":"identifier","text":"listComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController\/title","value":"SBUOpenChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}