{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"filteredUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser","text":"SBUUser"},{"kind":"text","text":"] { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbusuggestedmentionlist\/filteredusers"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSuggestedMentionList\/filteredUsers","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"filteredUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"]"}],"title":"filteredUsers","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13SendbirdUIKit23SBUSuggestedMentionListC13filteredUsersSayAA7SBUUserCGvp","modules":[{"name":"SendbirdUIKit"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSuggestedMentionList"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUser":{"role":"symbol","title":"SBUUser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUser"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUser"}],"url":"\/documentation\/sendbirduikit\/sbuuser"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUSuggestedMentionList":{"role":"symbol","title":"SBUSuggestedMentionList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUSuggestedMentionList"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSuggestedMentionList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUSuggestedMentionList"}],"url":"\/documentation\/sendbirduikit\/sbusuggestedmentionlist"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUSuggestedMentionList/filteredUsers":{"role":"symbol","title":"filteredUsers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"filteredUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSuggestedMentionList\/filteredUsers","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbusuggestedmentionlist\/filteredusers"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/title","value":"SBUUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/fragments","value":[{"kind":"identifier","text":"SBUUser"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSuggestedMentionList\/title","value":"SBUSuggestedMentionList"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUSuggestedMentionList\/fragments","value":[{"kind":"identifier","text":"SBUSuggestedMentionList"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}