{"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannellistviewmodel\/basechanneldelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannellistviewmodel\/basechanneldelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/BaseChannelDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channel(_:didUpdate:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasChanged(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasDeleted(_:channelType:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasFrozen(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasUnfrozen(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SendbirdUIKit"}],"role":"collectionGroup","title":"BaseChannelDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListViewModel/channelWasDeleted(_:channelType:)":{"role":"symbol","title":"channelWasDeleted(_:channelType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasDeleted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasDeleted(_:channelType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelWasDeleted:channelType:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistviewmodel\/channelwasdeleted(_:channeltype:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListViewModel/channel(_:didUpdate:)":{"role":"symbol","title":"channel(_:didUpdate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channel(_:didUpdate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel:didUpdateMessage:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistviewmodel\/channel(_:didupdate:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListViewModel":{"role":"symbol","title":"SBUOpenChannelListViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelListViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelListViewModel"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListViewModel/channelWasFrozen(_:)":{"role":"symbol","title":"channelWasFrozen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasFrozen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasFrozen(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelWasFrozen:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistviewmodel\/channelwasfrozen(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListViewModel/channelWasChanged(_:)":{"role":"symbol","title":"channelWasChanged(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasChanged"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasChanged(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelWasChanged:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistviewmodel\/channelwaschanged(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelListViewModel/channelWasUnfrozen(_:)":{"role":"symbol","title":"channelWasUnfrozen(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelWasUnfrozen"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasUnfrozen(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelWasUnfrozen:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannellistviewmodel\/channelwasunfrozen(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channel(_:didUpdate:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasChanged(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasDeleted(_:channelType:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasFrozen(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelListViewModel\/channelWasUnfrozen(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel~1channelWasDeleted(_:channelType:)\/title","value":"channelWasDeleted:channelType:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel~1channelWasDeleted(_:channelType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasDeleted:channelType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel~1channel(_:didUpdate:)\/title","value":"channel:didUpdateMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel~1channel(_:didUpdate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channel:didUpdateMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel\/title","value":"SBUOpenChannelListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelListViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel~1channelWasFrozen(_:)\/title","value":"channelWasFrozen:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel~1channelWasFrozen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasFrozen:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel~1channelWasChanged(_:)\/title","value":"channelWasChanged:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel~1channelWasChanged(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasChanged:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel~1channelWasUnfrozen(_:)\/title","value":"channelWasUnfrozen:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelListViewModel~1channelWasUnfrozen(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelWasUnfrozen:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}