{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView","text":"SBUStackView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelcell\/infostackview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelcell\/infostackview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/infoStackView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A vertical stack view to configure layouts of labels and icons that represent the channel information."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"title":"infoStackView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelCell(py)infoStackView","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"infoStackView"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell":{"role":"symbol","title":"SBUGroupChannelCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelCell"}],"abstract":[{"type":"codeVoice","code":"UITableViewCell"},{"type":"text","text":" of the table view that represents the list of group channels."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelCell"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/infoStackView":{"role":"symbol","title":"infoStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"abstract":[{"type":"text","text":"A vertical stack view to configure layouts of labels and icons that represent the channel information."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/infoStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"infoStackView"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/infostackview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUStackView":{"role":"symbol","title":"SBUStackView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUStackView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUStackView"}],"url":"\/documentation\/sendbirduikit\/sbustackview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"infoStackView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"infoStackView"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView","text":"SBUStackView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"infoStackView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell\/title","value":"SBUGroupChannelCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1infoStackView\/title","value":"infoStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1infoStackView\/fragments","value":[{"kind":"identifier","text":"infoStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUStackView\/title","value":"SBUStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUStackView\/fragments","value":[{"kind":"identifier","text":"SBUStackView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}