{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reactionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReactionView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUMessageReactionView","text":"SBUMessageReactionView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbucontentbasemessagecell\/reactionview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbucontentbasemessagecell\/reactionview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell\/reactionView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReactionView"},{"type":"text","text":" that shows reactions on the message."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reactionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUMessageReactionView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUMessageReactionView"}],"title":"reactionView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUContentBaseMessageCell(py)reactionView","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"reactionView"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUContentBaseMessageCell/reactionView":{"role":"symbol","title":"reactionView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reactionView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUMessageReactionView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUMessageReactionView"}],"abstract":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReactionView"},{"type":"text","text":" that shows reactions on the message."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell\/reactionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"reactionView"}],"url":"\/documentation\/sendbirduikit\/sbucontentbasemessagecell\/reactionview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReactionView":{"role":"symbol","title":"SBUMessageReactionView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageReactionView"}],"abstract":[{"type":"text","text":"Emoji reaction box"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReactionView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageReactionView"}],"url":"\/documentation\/sendbirduikit\/sbumessagereactionview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUContentBaseMessageCell":{"role":"symbol","title":"SBUContentBaseMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUContentBaseMessageCell"}],"abstract":[{"type":"text","text":"It is a base class used in message cell with contents."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUContentBaseMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbucontentbasemessagecell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"reactionView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"reactionView"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReactionView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUMessageReactionView","text":"SBUMessageReactionView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"reactionView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUContentBaseMessageCell~1reactionView\/title","value":"reactionView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUContentBaseMessageCell~1reactionView\/fragments","value":[{"kind":"identifier","text":"reactionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReactionView\/title","value":"SBUMessageReactionView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReactionView\/fragments","value":[{"kind":"identifier","text":"SBUMessageReactionView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUContentBaseMessageCell\/title","value":"SBUContentBaseMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUContentBaseMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUContentBaseMessageCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}