{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbucontentbasemessagecell\/setupviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbucontentbasemessagecell\/setupviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell\/setupViews()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function handles the initialization of views."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"title":"setupViews()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUContentBaseMessageCell(im)setupViews","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"setupViews"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUContentBaseMessageCell/setupViews()":{"role":"symbol","title":"setupViews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of views."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell\/setupViews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupViews"}],"url":"\/documentation\/sendbirduikit\/sbucontentbasemessagecell\/setupviews()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUContentBaseMessageCell":{"role":"symbol","title":"SBUContentBaseMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUContentBaseMessageCell"}],"abstract":[{"type":"text","text":"It is a base class used in message cell with contents."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUContentBaseMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbucontentbasemessagecell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setupViews"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUContentBaseMessageCell~1setupViews()\/title","value":"setupViews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUContentBaseMessageCell~1setupViews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUContentBaseMessageCell\/title","value":"SBUContentBaseMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUContentBaseMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUContentBaseMessageCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}