{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"? { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelcell\/channel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelcell\/channel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell\/channel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?"}],"title":"channel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelCell(py)channel","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"channel"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelCell/channel":{"role":"symbol","title":"channel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell\/channel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelcell\/channel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelCell":{"role":"symbol","title":"SBUBaseChannelCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelCell"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"channel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"channel"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SBDBaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"channel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelCell~1channel\/title","value":"channel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelCell~1channel\/fragments","value":[{"kind":"identifier","text":"channel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelCell\/title","value":"SBUBaseChannelCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelCell\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}