{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/createviewmodel(channel:channelurl:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/createviewmodel(channel:channelurl:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController\/createViewModel(channel:channelURL:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"createViewModel(channel:channelURL:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelPushSettingsViewController(im)createViewModelWithChannel:channelURL:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"createViewModelWithChannel:channelURL:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewController":{"role":"symbol","title":"SBUGroupChannelPushSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewController/createViewModel(channel:channelURL:)":{"role":"symbol","title":"createViewModel(channel:channelURL:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController\/createViewModel(channel:channelURL:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createViewModelWithChannel:channelURL:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/createviewmodel(channel:channelurl:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createViewModelWithChannel:channelURL:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createViewModelWithChannel:channelURL:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"createViewModelWithChannel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDBaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channel"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"channelURL"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController\/title","value":"SBUGroupChannelPushSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController~1createViewModel(channel:channelURL:)\/title","value":"createViewModelWithChannel:channelURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController~1createViewModel(channel:channelURL:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createViewModelWithChannel:channelURL:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}