{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelPushSettingsViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelPushSettingsViewModel","text":"SBUGroupChannelPushSettingsViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeNotification"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pushTriggerOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelPushTriggerOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"viewModel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUGroupChannelPushSettingsViewModel"},{"type":"text","text":" object."}]}]},{"name":"pushTriggerOption","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"GroupChannelPushTriggerOption"},{"type":"text","text":" object to change."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/groupchannelpushsettingsviewmodel(_:didchangenotification:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/groupchannelpushsettingsviewmodel(_:didchangenotification:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController\/groupChannelPushSettingsViewModel(_:didChangeNotification:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when changed push notification option"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelPushSettingsViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelPushSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelPushSettingsViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelPushTriggerOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption"},{"kind":"text","text":")"}],"title":"groupChannelPushSettingsViewModel(_:didChangeNotification:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelPushSettingsViewController(im)groupChannelPushSettingsViewModel:didChangeNotification:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"groupChannelPushSettingsViewModel:didChangeNotification:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewController":{"role":"symbol","title":"SBUGroupChannelPushSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewController/groupChannelPushSettingsViewModel(_:didChangeNotification:)":{"role":"symbol","title":"groupChannelPushSettingsViewModel(_:didChangeNotification:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelPushSettingsViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelPushSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelPushSettingsViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelPushTriggerOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when changed push notification option"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController\/groupChannelPushSettingsViewModel(_:didChangeNotification:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelPushSettingsViewModel:didChangeNotification:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/groupchannelpushsettingsviewmodel(_:didchangenotification:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewModel":{"role":"symbol","title":"SBUGroupChannelPushSettingsViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewModel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupChannelPushSettingsViewModel:didChangeNotification:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelPushSettingsViewModel:didChangeNotification:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupChannelPushSettingsViewModel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelPushSettingsViewModel","text":"SBUGroupChannelPushSettingsViewModel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeNotification:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBDGroupChannelPushTriggerOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption"},{"kind":"text","text":")"},{"kind":"internalParam","text":"pushTriggerOption"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController\/title","value":"SBUGroupChannelPushSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController~1groupChannelPushSettingsViewModel(_:didChangeNotification:)\/title","value":"groupChannelPushSettingsViewModel:didChangeNotification:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController~1groupChannelPushSettingsViewModel(_:didChangeNotification:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelPushSettingsViewModel:didChangeNotification:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewModel\/title","value":"SBUGroupChannelPushSettingsViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewModel\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}