{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelPushSettingsModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsModule","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC","text":"SBUGroupChannelPushSettingsModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsModule\/Header","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC6HeaderC","text":"Header"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapRightItem"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rightItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"component","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUGroupChannelPushSettingsModule.Header"},{"type":"text","text":" object"}]}]},{"name":"rightItem","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected "},{"type":"codeVoice","code":"rightBarButton"},{"type":"text","text":" object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/groupchannelpushsettingsmodule(_:didtaprightitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/groupchannelpushsettingsmodule(_:didtaprightitem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController\/groupChannelPushSettingsModule(_:didTapRightItem:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"rightBarButton"},{"type":"text","text":" was selected."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelPushSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelPushSettingsModule","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapRightItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"title":"groupChannelPushSettingsModule(_:didTapRightItem:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelPushSettingsViewController(im)groupChannelPushSettingsModule:didTapRightItem:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"groupChannelPushSettingsModule:didTapRightItem:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewController/groupChannelPushSettingsModule(_:didTapRightItem:)":{"role":"symbol","title":"groupChannelPushSettingsModule(_:didTapRightItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelPushSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelPushSettingsModule","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapRightItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"rightBarButton"},{"type":"text","text":" was selected."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController\/groupChannelPushSettingsModule(_:didTapRightItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelPushSettingsModule:didTapRightItem:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/groupchannelpushsettingsmodule(_:didtaprightitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsModule":{"role":"symbol","title":"SBUGroupChannelPushSettingsModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelPushSettingsModule"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsModule"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsModule/Header":{"role":"symbol","title":"SBUGroupChannelPushSettingsModule.Header","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"codeVoice","code":"SBUGroupChannelPushSettingsModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsModule\/Header","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Header"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsmodule\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewController":{"role":"symbol","title":"SBUGroupChannelPushSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/Header":{"role":"symbol","title":"Header","fragments":[{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"text","text":"SBUMessageSearchModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/header"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupChannelPushSettingsModule:didTapRightItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelPushSettingsModule:didTapRightItem:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupChannelPushSettingsModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)Header","text":"Header"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapRightItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"rightItem"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController~1groupChannelPushSettingsModule(_:didTapRightItem:)\/title","value":"groupChannelPushSettingsModule:didTapRightItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController~1groupChannelPushSettingsModule(_:didTapRightItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelPushSettingsModule:didTapRightItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController\/title","value":"SBUGroupChannelPushSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}