{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelPushSettingsModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsModule","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC","text":"SBUGroupChannelPushSettingsModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsModule\/List","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC4ListC","text":"List"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeNotification"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pushTriggerOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelPushTriggerOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUGroupChannelPushSettingsModule.List"},{"type":"text","text":" object."}]}]},{"name":"pushTriggerOption","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"GroupChannelPushTriggerOption"},{"type":"text","text":" object to change."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/groupchannelpushsettingsmodule(_:didchangenotification:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/groupchannelpushsettingsmodule(_:didchangenotification:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController\/groupChannelPushSettingsModule(_:didChangeNotification:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when changed push notification option"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelPushSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelPushSettingsModule","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelPushTriggerOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption"},{"kind":"text","text":")"}],"title":"groupChannelPushSettingsModule(_:didChangeNotification:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelPushSettingsViewController(im)groupChannelPushSettingsModule:didChangeNotification:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"groupChannelPushSettingsModule:didChangeNotification:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsModule/List":{"role":"symbol","title":"SBUGroupChannelPushSettingsModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUGroupChannelPushSettingsModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsModuleList":{"role":"symbol","title":"SBUGroupChannelPushSettingsModuleList","fragments":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUGroupChannelPushSettingsModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsmodulelist"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewController/groupChannelPushSettingsModule(_:didChangeNotification:)":{"role":"symbol","title":"groupChannelPushSettingsModule(_:didChangeNotification:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelPushSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelPushSettingsModule","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit33SBUGroupChannelPushSettingsModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeNotification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelPushTriggerOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when changed push notification option"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController\/groupChannelPushSettingsModule(_:didChangeNotification:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelPushSettingsModule:didChangeNotification:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller\/groupchannelpushsettingsmodule(_:didchangenotification:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewController":{"role":"symbol","title":"SBUGroupChannelPushSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsModule":{"role":"symbol","title":"SBUGroupChannelPushSettingsModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelPushSettingsModule"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsModule"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupChannelPushSettingsModule:didChangeNotification:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelPushSettingsModule:didChangeNotification:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupChannelPushSettingsModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelPushSettingsModuleList","text":"SBUGroupChannelPushSettingsModuleList"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeNotification:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"SBDGroupChannelPushTriggerOption","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDGroupChannelPushTriggerOption"},{"kind":"text","text":")"},{"kind":"internalParam","text":"pushTriggerOption"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController~1groupChannelPushSettingsModule(_:didChangeNotification:)\/title","value":"groupChannelPushSettingsModule:didChangeNotification:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController~1groupChannelPushSettingsModule(_:didChangeNotification:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelPushSettingsModule:didChangeNotification:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController\/title","value":"SBUGroupChannelPushSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}