{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelSettingsModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit29SBUGroupChannelSettingsModuleC","text":"SBUGroupChannelSettingsModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsModule\/List","preciseIdentifier":"s:13SendbirdUIKit29SBUGroupChannelSettingsModuleC4ListC","text":"List"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUGroupChannelSettingsModule.List"},{"type":"text","text":" object."}]}]},{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An index path locating the row in table view of `listComponent"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewcontroller\/groupchannelsettingsmodule(_:didselectrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewcontroller\/groupchannelsettingsmodule(_:didselectrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewController\/groupChannelSettingsModule(_:didSelectRowAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the setting item cell was selected in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit29SBUGroupChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit29SBUGroupChannelSettingsModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"title":"groupChannelSettingsModule(_:didSelectRowAt:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelSettingsViewController(im)groupChannelSettingsModule:didSelectRowAt:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"groupChannelSettingsModule:didSelectRowAt:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelSettingsViewController":{"role":"symbol","title":"SBUGroupChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelSettingsViewController/groupChannelSettingsModule(_:didSelectRowAt:)":{"role":"symbol","title":"groupChannelSettingsModule(_:didSelectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupChannelSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUGroupChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit29SBUGroupChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit29SBUGroupChannelSettingsModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the setting item cell was selected in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewController\/groupChannelSettingsModule(_:didSelectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupChannelSettingsModule:didSelectRowAt:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewcontroller\/groupchannelsettingsmodule(_:didselectrowat:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelSettingsModule/List":{"role":"symbol","title":"SBUGroupChannelSettingsModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUGroupChannelSettingsModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelsettingsmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelSettingsModuleList":{"role":"symbol","title":"SBUGroupChannelSettingsModuleList","fragments":[{"kind":"identifier","text":"SBUGroupChannelSettingsModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUGroupChannelSettingsModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbugroupchannelsettingsmodulelist"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelSettingsModule":{"role":"symbol","title":"SBUGroupChannelSettingsModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelSettingsModule"}],"abstract":[{"type":"text","text":"The class that represents the group channel setting module."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelSettingsModule"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelsettingsmodule"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"groupChannelSettingsModule:didSelectRowAt:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelSettingsModule:didSelectRowAt:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"groupChannelSettingsModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelSettingsModuleList","text":"SBUGroupChannelSettingsModuleList"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSelectRowAt:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewController\/title","value":"SBUGroupChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewController~1groupChannelSettingsModule(_:didSelectRowAt:)\/title","value":"groupChannelSettingsModule:didSelectRowAt:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewController~1groupChannelSettingsModule(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupChannelSettingsModule:didSelectRowAt:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}