{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelSettingsViewModel","text":"SBUGroupChannelSettingsViewModel"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewcontroller\/viewmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewcontroller\/viewmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewController\/viewModel","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUGroupChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelSettingsViewModel"},{"kind":"text","text":"?"}],"title":"viewModel","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelSettingsViewController(py)viewModel","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"viewModel"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelSettingsViewController/viewModel":{"role":"symbol","title":"viewModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUGroupChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelSettingsViewModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewController\/viewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewModel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewcontroller\/viewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelSettingsViewModel":{"role":"symbol","title":"SBUGroupChannelSettingsViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelSettingsViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelSettingsViewModel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelSettingsViewController":{"role":"symbol","title":"SBUGroupChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"viewModel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"viewModel"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelSettingsViewModel","text":"SBUGroupChannelSettingsViewModel"},{"kind":"text","text":" * "},{"kind":"identifier","text":"viewModel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewController~1viewModel\/title","value":"viewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewController~1viewModel\/fragments","value":[{"kind":"identifier","text":"viewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewModel\/title","value":"SBUGroupChannelSettingsViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewModel\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelSettingsViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewController\/title","value":"SBUGroupChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelSettingsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}