{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseSelectedUserViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseSelectUserViewModel","text":"SBUBaseSelectUserViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateSelectedUsers"},{"kind":"text","text":" "},{"kind":"internalParam","text":"selectedUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser","text":"SBUUser"},{"kind":"text","text":"]?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/baseselecteduserviewmodel(_:didupdateselectedusers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/baseselecteduserviewmodel(_:didupdateselectedusers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController\/baseSelectedUserViewModel(_:didUpdateSelectedUsers:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseSelectedUserViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseSelectUserViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseSelectUserViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateSelectedUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"]?)"}],"title":"baseSelectedUserViewModel(_:didUpdateSelectedUsers:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUInviteUserViewController(im)baseSelectedUserViewModel:didUpdateSelectedUsers:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"baseSelectedUserViewModel:didUpdateSelectedUsers:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserViewController":{"role":"symbol","title":"SBUInviteUserViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUInviteUserViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUInviteUserViewController"}],"url":"\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserViewController/baseSelectedUserViewModel(_:didUpdateSelectedUsers:)":{"role":"symbol","title":"baseSelectedUserViewModel(_:didUpdateSelectedUsers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseSelectedUserViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseSelectUserViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseSelectUserViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateSelectedUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController\/baseSelectedUserViewModel(_:didUpdateSelectedUsers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseSelectedUserViewModel:didUpdateSelectedUsers:"}],"url":"\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/baseselecteduserviewmodel(_:didupdateselectedusers:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserViewModel":{"role":"symbol","title":"SBUBaseSelectUserViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserViewModel"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectuserviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUser":{"role":"symbol","title":"SBUUser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUser"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUser"}],"url":"\/documentation\/sendbirduikit\/sbuuser"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"baseSelectedUserViewModel:didUpdateSelectedUsers:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseSelectedUserViewModel:didUpdateSelectedUsers:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"baseSelectedUserViewModel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseSelectUserViewModel","text":"SBUBaseSelectUserViewModel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":" "},{"kind":"identifier","text":"didUpdateSelectedUsers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBUUser *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"selectedUsers"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController\/title","value":"SBUInviteUserViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController\/fragments","value":[{"kind":"identifier","text":"SBUInviteUserViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController~1baseSelectedUserViewModel(_:didUpdateSelectedUsers:)\/title","value":"baseSelectedUserViewModel:didUpdateSelectedUsers:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController~1baseSelectedUserViewModel(_:didUpdateSelectedUsers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseSelectedUserViewModel:didUpdateSelectedUsers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseSelectUserViewModel\/title","value":"SBUBaseSelectUserViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseSelectUserViewModel\/fragments","value":[{"kind":"identifier","text":"SBUBaseSelectUserViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/title","value":"SBUUser"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUser\/fragments","value":[{"kind":"identifier","text":"SBUUser"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}