{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"inviteUserModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC","text":"SBUInviteUserModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule\/List","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC4ListC","text":"List"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDetectPreloadingPosition"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUInviteUserModule.List"},{"type":"text","text":" object."}]}]},{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An index path locating the row in table view of `listComponent"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/inviteusermodule(_:diddetectpreloadingposition:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/inviteusermodule(_:diddetectpreloadingposition:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController\/inviteUserModule(_:didDetectPreloadingPosition:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the tableView detected preloading position in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"inviteUserModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUInviteUserModule","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDetectPreloadingPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"title":"inviteUserModule(_:didDetectPreloadingPosition:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUInviteUserViewController(im)inviteUserModule:didDetectPreloadingPosition:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"inviteUserModule:didDetectPreloadingPosition:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserModule":{"role":"symbol","title":"SBUInviteUserModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUInviteUserModule"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUInviteUserModule"}],"url":"\/documentation\/sendbirduikit\/sbuinviteusermodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserViewController":{"role":"symbol","title":"SBUInviteUserViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUInviteUserViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUInviteUserViewController"}],"url":"\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserModule/List":{"role":"symbol","title":"SBUInviteUserModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUInviteUserModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbuinviteusermodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserModuleList":{"role":"symbol","title":"SBUInviteUserModuleList","fragments":[{"kind":"identifier","text":"SBUInviteUserModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUInviteUserModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbuinviteusermodulelist"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserViewController/inviteUserModule(_:didDetectPreloadingPosition:)":{"role":"symbol","title":"inviteUserModule(_:didDetectPreloadingPosition:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"inviteUserModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUInviteUserModule","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDetectPreloadingPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the tableView detected preloading position in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController\/inviteUserModule(_:didDetectPreloadingPosition:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"inviteUserModule:didDetectPreloadingPosition:"}],"url":"\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/inviteusermodule(_:diddetectpreloadingposition:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"inviteUserModule:didDetectPreloadingPosition:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"inviteUserModule:didDetectPreloadingPosition:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"inviteUserModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUInviteUserModuleList","text":"SBUInviteUserModuleList"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDetectPreloadingPosition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController\/title","value":"SBUInviteUserViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController\/fragments","value":[{"kind":"identifier","text":"SBUInviteUserViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController~1inviteUserModule(_:didDetectPreloadingPosition:)\/title","value":"inviteUserModule:didDetectPreloadingPosition:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController~1inviteUserModule(_:didDetectPreloadingPosition:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"inviteUserModule:didDetectPreloadingPosition:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}