{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"inviteUserModuleDidSelectRetry"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC","text":"SBUInviteUserModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule\/List","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC4ListC","text":"List"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUInviteUserModule.List"},{"type":"text","text":" object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/inviteusermoduledidselectretry(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/inviteusermoduledidselectretry(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController\/inviteUserModuleDidSelectRetry(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the retry button was selected from the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"inviteUserModuleDidSelectRetry"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUInviteUserModule","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC4ListC"},{"kind":"text","text":")"}],"title":"inviteUserModuleDidSelectRetry(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUInviteUserViewController(im)inviteUserModuleDidSelectRetry:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"inviteUserModuleDidSelectRetry:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserViewController/inviteUserModuleDidSelectRetry(_:)":{"role":"symbol","title":"inviteUserModuleDidSelectRetry(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"inviteUserModuleDidSelectRetry"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUInviteUserModule","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC4ListC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the retry button was selected from the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController\/inviteUserModuleDidSelectRetry(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"inviteUserModuleDidSelectRetry:"}],"url":"\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/inviteusermoduledidselectretry(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserModule":{"role":"symbol","title":"SBUInviteUserModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUInviteUserModule"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUInviteUserModule"}],"url":"\/documentation\/sendbirduikit\/sbuinviteusermodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserModule/List":{"role":"symbol","title":"SBUInviteUserModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUInviteUserModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbuinviteusermodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserViewController":{"role":"symbol","title":"SBUInviteUserViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUInviteUserViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUInviteUserViewController"}],"url":"\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserModuleList":{"role":"symbol","title":"SBUInviteUserModuleList","fragments":[{"kind":"identifier","text":"SBUInviteUserModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUInviteUserModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbuinviteusermodulelist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"inviteUserModuleDidSelectRetry:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"inviteUserModuleDidSelectRetry:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"inviteUserModuleDidSelectRetry:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUInviteUserModuleList","text":"SBUInviteUserModuleList"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController~1inviteUserModuleDidSelectRetry(_:)\/title","value":"inviteUserModuleDidSelectRetry:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController~1inviteUserModuleDidSelectRetry(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"inviteUserModuleDidSelectRetry:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController\/title","value":"SBUInviteUserViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController\/fragments","value":[{"kind":"identifier","text":"SBUInviteUserViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}