{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC","text":"SBUInviteUserModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule\/List","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC4ListC","text":"List"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/listcomponent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/listcomponent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController\/listComponent","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUInviteUserModule","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC4ListC"},{"kind":"text","text":"?"}],"title":"listComponent","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUInviteUserViewController(py)listComponent","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"listComponent"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserViewController/listComponent":{"role":"symbol","title":"listComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUInviteUserModule","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit19SBUInviteUserModuleC4ListC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController\/listComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"listComponent"}],"url":"\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller\/listcomponent"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserModule":{"role":"symbol","title":"SBUInviteUserModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUInviteUserModule"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUInviteUserModule"}],"url":"\/documentation\/sendbirduikit\/sbuinviteusermodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserViewController":{"role":"symbol","title":"SBUInviteUserViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUInviteUserViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUInviteUserViewController"}],"url":"\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserModule/List":{"role":"symbol","title":"SBUInviteUserModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUInviteUserModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbuinviteusermodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserModuleList":{"role":"symbol","title":"SBUInviteUserModuleList","fragments":[{"kind":"identifier","text":"SBUInviteUserModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUInviteUserModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbuinviteusermodulelist"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"listComponent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"listComponent"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUInviteUserModuleList","text":"SBUInviteUserModuleList"},{"kind":"text","text":" * "},{"kind":"identifier","text":"listComponent"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController~1listComponent\/title","value":"listComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController~1listComponent\/fragments","value":[{"kind":"identifier","text":"listComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController\/title","value":"SBUInviteUserViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController\/fragments","value":[{"kind":"identifier","text":"SBUInviteUserViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}