{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelViewModel","text":"SBUBaseChannelViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeMessageList"},{"kind":"text","text":" "},{"kind":"internalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"needsToReload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initialLoad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/basechannelviewmodel(_:didchangemessagelist:needstoreload:initialload:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/basechannelviewmodel(_:didchangemessagelist:needstoreload:initialload:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/baseChannelViewModel(_:didChangeMessageList:needsToReload:initialLoad:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when the messages has been changed. If they’re the first loaded messages, "},{"type":"codeVoice","code":"initialLoad"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeMessageList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"needsToReload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initialLoad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"baseChannelViewModel(_:didChangeMessageList:needsToReload:initialLoad:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelViewController(im)baseChannelViewModel:didChangeMessageList:needsToReload:initialLoad:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"baseChannelViewModel:didChangeMessageList:needsToReload:initialLoad:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController/baseChannelViewModel(_:didChangeMessageList:needsToReload:initialLoad:)":{"role":"symbol","title":"baseChannelViewModel(_:didChangeMessageList:needsToReload:initialLoad:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeMessageList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"needsToReload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"initialLoad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the messages has been changed. If they’re the first loaded messages, "},{"type":"codeVoice","code":"initialLoad"},{"type":"text","text":" is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/baseChannelViewModel(_:didChangeMessageList:needsToReload:initialLoad:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseChannelViewModel:didChangeMessageList:needsToReload:initialLoad:"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/basechannelviewmodel(_:didchangemessagelist:needstoreload:initialload:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewModel":{"role":"symbol","title":"SBUBaseChannelViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewModel"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController":{"role":"symbol","title":"SBUBaseChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"baseChannelViewModel:didChangeMessageList:needsToReload:initialLoad:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelViewModel:didChangeMessageList:needsToReload:initialLoad:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"baseChannelViewModel:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelViewModel","text":"SBUBaseChannelViewModel"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewModel"},{"kind":"text","text":" "},{"kind":"identifier","text":"didChangeMessageList:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<SBDBaseMessage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messages"},{"kind":"text","text":" "},{"kind":"identifier","text":"needsToReload:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"needsToReload"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialLoad:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"initialLoad"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1baseChannelViewModel(_:didChangeMessageList:needsToReload:initialLoad:)\/title","value":"baseChannelViewModel:didChangeMessageList:needsToReload:initialLoad:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1baseChannelViewModel(_:didChangeMessageList:needsToReload:initialLoad:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelViewModel:didChangeMessageList:needsToReload:initialLoad:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewModel\/title","value":"SBUBaseChannelViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewModel\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/title","value":"SBUBaseChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}