{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelModule","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC","text":"SBUBaseChannelModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelModule\/List","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC4ListC","text":"List"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasNextInTableView"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether the "},{"type":"codeVoice","code":"tableView"},{"type":"text","text":" has next data."}]}]},{"kind":"parameters","parameters":[{"name":"listComponent","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUBaseChannelModule.List"},{"type":"text","text":" object."}]}]},{"name":"tableView","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"UITableView"},{"type":"text","text":" object from list component."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/basechannelmodule(_:hasnextintableview:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/basechannelmodule(_:hasnextintableview:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/baseChannelModule(_:hasNextInTableView:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Ask the data source to return whether the "},{"type":"codeVoice","code":"tableView"},{"type":"text","text":" has next data."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelModule","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasNextInTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"baseChannelModule(_:hasNextInTableView:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelViewController(im)baseChannelModule:hasNextInTableView:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"baseChannelModule:hasNextInTableView:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelModuleList":{"role":"symbol","title":"SBUBaseChannelModuleList","fragments":[{"kind":"identifier","text":"SBUBaseChannelModuleList"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"text","text":"SBUBaseChannelModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelModuleList","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbubasechannelmodulelist"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController":{"role":"symbol","title":"SBUBaseChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelModule":{"role":"symbol","title":"SBUBaseChannelModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelModule"}],"abstract":[{"type":"text","text":"The class that represents the base of the channel module"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelModule"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelModule/List":{"role":"symbol","title":"SBUBaseChannelModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUBaseChannelModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController/baseChannelModule(_:hasNextInTableView:)":{"role":"symbol","title":"baseChannelModule(_:hasNextInTableView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelModule","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit20SBUBaseChannelModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hasNextInTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Ask the data source to return whether the "},{"type":"codeVoice","code":"tableView"},{"type":"text","text":" has next data."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/baseChannelModule(_:hasNextInTableView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseChannelModule:hasNextInTableView:"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/basechannelmodule(_:hasnextintableview:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"baseChannelModule:hasNextInTableView:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelModule:hasNextInTableView:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"baseChannelModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelModuleList","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelModuleList","text":"SBUBaseChannelModuleList"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"listComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasNextInTableView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/title","value":"SBUBaseChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1baseChannelModule(_:hasNextInTableView:)\/title","value":"baseChannelModule:hasNextInTableView:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1baseChannelModule(_:hasNextInTableView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelModule:hasNextInTableView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}