{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/messagelist"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/messagelist"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/messageList","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"messageList"}],"role":"symbol","title":"messageList","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"]"}],"symbolKind":"property","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUBaseChannelViewController(py)messageList","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This property has been moved to `SBUBaseChannelViewModel`"}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController/messageList":{"deprecated":true,"role":"symbol","title":"messageList","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageList"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/messageList","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageList"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/messagelist"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController":{"role":"symbol","title":"SBUBaseChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"messageList"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"messageList"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<SBDBaseMessage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"messageList"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1messageList\/title","value":"messageList"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1messageList\/fragments","value":[{"kind":"identifier","text":"messageList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/title","value":"SBUBaseChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}