{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"fileMessage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"fileMessage object"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/openfile(filemessage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/openfile(filemessage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/openFile(fileMessage:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function opens a file according to the file type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":")"}],"title":"openFile(fileMessage:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelViewController(im)openFileWithFileMessage:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"openFileWithFileMessage:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController/openFile(fileMessage:)":{"role":"symbol","title":"openFile(fileMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function opens a file according to the file type."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/openFile(fileMessage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openFileWithFileMessage:"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/openfile(filemessage:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController":{"role":"symbol","title":"SBUBaseChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"openFileWithFileMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openFileWithFileMessage:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"openFileWithFileMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDFileMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"fileMessage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1openFile(fileMessage:)\/title","value":"openFileWithFileMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1openFile(fileMessage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openFileWithFileMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/title","value":"SBUBaseChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}