{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parentMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/sendfilemessage(messageparams:parentmessage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/sendfilemessage(messageparams:parentmessage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/sendFileMessage(messageParams:parentMessage:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"sendFileMessageWithMessageParams:parentMessage:"}],"role":"symbol","title":"sendFileMessage(messageParams:parentMessage:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parentMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUBaseChannelViewController(im)sendFileMessageWithMessageParams:parentMessage:","extendedModule":"SendbirdUIKit","platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This function has been moved to `SBUBaseChannelViewModel`. Use `sendFileMessage(messageParams:parentMessage:)` of `SBUBaseChannelViewModel` instead."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController/sendFileMessage(messageParams:parentMessage:)":{"deprecated":true,"role":"symbol","title":"sendFileMessage(messageParams:parentMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendFileMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams"},{"kind":"text","text":", "},{"kind":"externalParam","text":"parentMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/sendFileMessage(messageParams:parentMessage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sendFileMessageWithMessageParams:parentMessage:"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/sendfilemessage(messageparams:parentmessage:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController":{"role":"symbol","title":"SBUBaseChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sendFileMessageWithMessageParams:parentMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendFileMessageWithMessageParams:parentMessage:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendFileMessageWithMessageParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDFileMessageCreateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDFileMessageCreateParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messageParams"},{"kind":"text","text":" "},{"kind":"identifier","text":"parentMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDBaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"parentMessage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1sendFileMessage(messageParams:parentMessage:)\/title","value":"sendFileMessageWithMessageParams:parentMessage:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1sendFileMessage(messageParams:parentMessage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sendFileMessageWithMessageParams:parentMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/title","value":"SBUBaseChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}