{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showMenuViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"cell","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Message cell"}]}]},{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Message object"}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is used when the reaction feature is activated."},{"type":"text","text":" "},{"type":"text","text":"This function configures the menu items using the "},{"type":"codeVoice","code":"message"},{"type":"text","text":" object."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"3.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/showmenuviewcontroller(_:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/showmenuviewcontroller(_:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/showMenuViewController(_:message:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This function shows cell’s menu."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"showMenuViewController:message:"}],"role":"symbol","title":"showMenuViewController(_:message:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showMenuViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelViewController(im)showMenuViewController:message:","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please use `showMessageMenuSheet(for:cell:)` in `SBUBaseChannelModule.List` instead."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController":{"role":"symbol","title":"SBUBaseChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController/showMenuViewController(_:message:)":{"deprecated":true,"role":"symbol","title":"showMenuViewController(_:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showMenuViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function shows cell’s menu."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/showMenuViewController(_:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showMenuViewController:message:"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/showmenuviewcontroller(_:message:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showMenuViewController:message:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showMenuViewController:message:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showMenuViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"cell"},{"kind":"text","text":" "},{"kind":"identifier","text":"message:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDBaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/title","value":"SBUBaseChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1showMenuViewController(_:message:)\/title","value":"showMenuViewController:message:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1showMenuViewController(_:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showMenuViewController:message:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}