{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessageUpdateParams"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/updateusermessage(message:messageparams:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/updateusermessage(message:messageparams:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/updateUserMessage(message:messageParams:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"updateUserMessageWithMessage:messageParams:"}],"role":"symbol","title":"updateUserMessage(message:messageParams:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessageUpdateParams"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUBaseChannelViewController(im)updateUserMessageWithMessage:messageParams:","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This function has been moved to `SBUBaseChannelViewModel`."}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController":{"role":"symbol","title":"SBUBaseChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController/updateUserMessage(message:messageParams:)":{"deprecated":true,"role":"symbol","title":"updateUserMessage(message:messageParams:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"messageParams"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessageUpdateParams"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/updateUserMessage(message:messageParams:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateUserMessageWithMessage:messageParams:"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/updateusermessage(message:messageparams:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateUserMessageWithMessage:messageParams:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateUserMessageWithMessage:messageParams:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateUserMessageWithMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDUserMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageParams:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDUserMessageUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDUserMessageUpdateParams"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"messageParams"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/title","value":"SBUBaseChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1updateUserMessage(message:messageParams:)\/title","value":"updateUserMessageWithMessage:messageParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1updateUserMessage(message:messageParams:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateUserMessageWithMessage:messageParams:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}