{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/viewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/viewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/viewWillDisappear(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"viewWillDisappear(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelViewController(im)viewWillDisappear:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController":{"role":"symbol","title":"SBUBaseChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController/viewWillDisappear(_:)":{"role":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController\/viewWillDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller\/viewwilldisappear(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewWillDisappear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/title","value":"SBUBaseChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}