{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/messagegroupposition\/top"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/messagegroupposition\/top"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageGroupPosition\/top","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"}],"title":"MessageGroupPosition.top","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdUIKit@E@MessageGroupPosition@MessageGroupPositionTop","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MessageGroupPositionTop"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageGroupPosition"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessageGroupPosition":{"role":"symbol","title":"MessageGroupPosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageGroupPosition"}],"abstract":[{"type":"text","text":"This is an enumeration used to select the message position in group messages."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageGroupPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageGroupPosition"}],"url":"\/documentation\/sendbirduikit\/messagegroupposition"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessageGroupPosition/top":{"role":"symbol","title":"MessageGroupPosition.top","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageGroupPosition\/top","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageGroupPositionTop"}],"url":"\/documentation\/sendbirduikit\/messagegroupposition\/top"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MessageGroupPositionTop"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageGroupPositionTop"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MessageGroupPositionTop"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageGroupPosition\/title","value":"MessageGroupPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageGroupPosition\/fragments","value":[{"kind":"identifier","text":"MessageGroupPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageGroupPosition~1top\/title","value":"MessageGroupPositionTop"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageGroupPosition~1top\/fragments","value":[{"kind":"identifier","text":"MessageGroupPositionTop"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}