{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"edit"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/messageedititem\/edit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/messageedititem\/edit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageEditItem\/edit","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"MessageEditItemEdit"}],"role":"symbol","title":"MessageEditItem.edit","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"edit"}],"symbolKind":"case","externalID":"c:@M@SendbirdUIKit@E@MessageEditItem@MessageEditItemEdit","modules":[{"name":"SendbirdUIKit"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageEditItem"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Please refer to `setupMenuItems()` function in `SBUBaseChannelModule.List` or `SBUMenuSheetViewController`"}]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessageEditItem/edit":{"deprecated":true,"role":"symbol","title":"MessageEditItem.edit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"edit"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageEditItem\/edit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageEditItemEdit"}],"url":"\/documentation\/sendbirduikit\/messageedititem\/edit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessageEditItem":{"deprecated":true,"role":"symbol","title":"MessageEditItem","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageEditItem"}],"abstract":[{"type":"text","text":"This is an enumeration used to the message edit type."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessageEditItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageEditItem"}],"url":"\/documentation\/sendbirduikit\/messageedititem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MessageEditItemEdit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageEditItemEdit"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"MessageEditItemEdit"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageEditItem~1edit\/title","value":"MessageEditItemEdit"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageEditItem~1edit\/fragments","value":[{"kind":"identifier","text":"MessageEditItemEdit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageEditItem\/title","value":"MessageEditItem"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessageEditItem\/fragments","value":[{"kind":"identifier","text":"MessageEditItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}