{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelEditType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/channeledittype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/channeledittype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is an enumeration used to select the channel editing type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelEditType"}],"title":"ChannelEditType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdUIKit@E@ChannelEditType","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChannelEditType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/image","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/name"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/Equatable-Implementations","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelEditType/image":{"role":"symbol","title":"ChannelEditType.image","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/image","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelEditTypeImage"}],"url":"\/documentation\/sendbirduikit\/channeledittype\/image"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelEditType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/channeledittype\/init(rawvalue:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelEditType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/channeledittype\/equatable-implementations"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.uikit\/SY"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelEditType":{"role":"symbol","title":"ChannelEditType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelEditType"}],"abstract":[{"type":"text","text":"This is an enumeration used to select the channel editing type."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelEditType"}],"url":"\/documentation\/sendbirduikit\/channeledittype"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelEditType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/channeledittype\/rawrepresentable-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/ChannelEditType/name":{"role":"symbol","title":"ChannelEditType.name","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/name","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChannelEditTypeName"}],"url":"\/documentation\/sendbirduikit\/channeledittype\/name"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"ChannelEditType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChannelEditType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChannelEditType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/image","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/ChannelEditType\/name"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelEditType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelEditType~1image\/title","value":"ChannelEditTypeImage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelEditType~1image\/fragments","value":[{"kind":"identifier","text":"ChannelEditTypeImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelEditType\/title","value":"ChannelEditType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelEditType\/fragments","value":[{"kind":"identifier","text":"ChannelEditType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelEditType~1name\/title","value":"ChannelEditTypeName"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1ChannelEditType~1name\/fragments","value":[{"kind":"identifier","text":"ChannelEditTypeName"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}