{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/logtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/logtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/all","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/error","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/info","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/none","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/warning"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/Equatable-Implementations","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogType"}],"title":"LogType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdUIKit@E@LogType","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"LogType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.uikit\/SY"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/LogType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/logtype\/rawrepresentable-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/LogType/warning":{"role":"symbol","title":"LogType.warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/warning","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogTypeWarning"}],"url":"\/documentation\/sendbirduikit\/logtype\/warning"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/LogType/info":{"role":"symbol","title":"LogType.info","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/info","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogTypeInfo"}],"url":"\/documentation\/sendbirduikit\/logtype\/info"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/LogType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/logtype\/init(rawvalue:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/LogType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/logtype\/equatable-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/LogType":{"role":"symbol","title":"LogType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogType"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogType"}],"url":"\/documentation\/sendbirduikit\/logtype"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/LogType/none":{"role":"symbol","title":"LogType.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogTypeNone"}],"url":"\/documentation\/sendbirduikit\/logtype\/none"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/LogType/all":{"role":"symbol","title":"LogType.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogTypeAll"}],"url":"\/documentation\/sendbirduikit\/logtype\/all"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/LogType/error":{"role":"symbol","title":"LogType.error","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogTypeError"}],"url":"\/documentation\/sendbirduikit\/logtype\/error"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"LogType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LogType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LogType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/all","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/error","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/info","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/none","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/LogType\/warning"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"uint8_t","preciseIdentifier":"c:@T@uint8_t"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType~1warning\/title","value":"LogTypeWarning"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType~1warning\/fragments","value":[{"kind":"identifier","text":"LogTypeWarning"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType~1info\/title","value":"LogTypeInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType~1info\/fragments","value":[{"kind":"identifier","text":"LogTypeInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType\/title","value":"LogType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType\/fragments","value":[{"kind":"identifier","text":"LogType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType~1none\/title","value":"LogTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType~1none\/fragments","value":[{"kind":"identifier","text":"LogTypeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType~1all\/title","value":"LogTypeAll"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType~1all\/fragments","value":[{"kind":"identifier","text":"LogTypeAll"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType~1error\/title","value":"LogTypeError"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1LogType~1error\/fragments","value":[{"kind":"identifier","text":"LogTypeError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}