{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePosition"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/messageposition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/messageposition"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is an enumeration used to select the message position."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePosition"}],"title":"MessagePosition","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdUIKit@E@MessagePosition","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MessagePosition"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/center","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/left","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/right"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/Equatable-Implementations","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessagePosition/left":{"role":"symbol","title":"MessagePosition.left","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/left","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePositionLeft"}],"url":"\/documentation\/sendbirduikit\/messageposition\/left"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessagePosition/center":{"role":"symbol","title":"MessagePosition.center","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"center"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/center","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePositionCenter"}],"url":"\/documentation\/sendbirduikit\/messageposition\/center"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessagePosition/right":{"role":"symbol","title":"MessagePosition.right","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/right","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePositionRight"}],"url":"\/documentation\/sendbirduikit\/messageposition\/right"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessagePosition/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/messageposition\/equatable-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessagePosition/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/messageposition\/rawrepresentable-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessagePosition/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/messageposition\/init(rawvalue:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/MessagePosition":{"role":"symbol","title":"MessagePosition","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePosition"}],"abstract":[{"type":"text","text":"This is an enumeration used to select the message position."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagePosition"}],"url":"\/documentation\/sendbirduikit\/messageposition"},"doc://com.sendbird.uikit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.uikit\/SY"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"MessagePosition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessagePosition"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MessagePosition"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/center","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/left","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/MessagePosition\/right"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagePosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessagePosition~1left\/title","value":"MessagePositionLeft"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessagePosition~1left\/fragments","value":[{"kind":"identifier","text":"MessagePositionLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessagePosition~1center\/title","value":"MessagePositionCenter"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessagePosition~1center\/fragments","value":[{"kind":"identifier","text":"MessagePositionCenter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessagePosition~1right\/title","value":"MessagePositionRight"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessagePosition~1right\/fragments","value":[{"kind":"identifier","text":"MessagePositionRight"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessagePosition\/title","value":"MessagePosition"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1MessagePosition\/fragments","value":[{"kind":"identifier","text":"MessagePosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}