{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewMessageInfoItemType"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2.0.0"}]}],"type":"aside","name":"Since"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/newmessageinfoitemtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/newmessageinfoitemtype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is an enumeration for new message info item type."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewMessageInfoItemType"}],"title":"NewMessageInfoItemType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdUIKit@E@NewMessageInfoItemType","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"NewMessageInfoItemType"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/button","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/tooltip"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/Equatable-Implementations","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/NewMessageInfoItemType/tooltip":{"role":"symbol","title":"NewMessageInfoItemType.tooltip","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooltip"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/tooltip","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NewMessageInfoItemTypeTooltip"}],"url":"\/documentation\/sendbirduikit\/newmessageinfoitemtype\/tooltip"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/NewMessageInfoItemType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/newmessageinfoitemtype\/equatable-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/NewMessageInfoItemType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/newmessageinfoitemtype\/init(rawvalue:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/NewMessageInfoItemType/button":{"role":"symbol","title":"NewMessageInfoItemType.button","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"button"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/button","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NewMessageInfoItemTypeButton"}],"url":"\/documentation\/sendbirduikit\/newmessageinfoitemtype\/button"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/NewMessageInfoItemType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/newmessageinfoitemtype\/rawrepresentable-implementations"},"doc://com.sendbird.uikit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.uikit\/SY"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/NewMessageInfoItemType":{"role":"symbol","title":"NewMessageInfoItemType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewMessageInfoItemType"}],"abstract":[{"type":"text","text":"This is an enumeration for new message info item type."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NewMessageInfoItemType"}],"url":"\/documentation\/sendbirduikit\/newmessageinfoitemtype"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"NewMessageInfoItemType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"NewMessageInfoItemType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NewMessageInfoItemType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/button","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/NewMessageInfoItemType\/tooltip"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewMessageInfoItemType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1NewMessageInfoItemType~1tooltip\/title","value":"NewMessageInfoItemTypeTooltip"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1NewMessageInfoItemType~1tooltip\/fragments","value":[{"kind":"identifier","text":"NewMessageInfoItemTypeTooltip"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1NewMessageInfoItemType~1button\/title","value":"NewMessageInfoItemTypeButton"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1NewMessageInfoItemType~1button\/fragments","value":[{"kind":"identifier","text":"NewMessageInfoItemTypeButton"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1NewMessageInfoItemType\/title","value":"NewMessageInfoItemType"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1NewMessageInfoItemType\/fragments","value":[{"kind":"identifier","text":"NewMessageInfoItemType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}