{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBDesignable"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUAdminMessageCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuadminmessagecell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuadminmessagecell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding","doc:\/\/com.sendbird.uikit\/objc(pl)NSObject","doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageCellProtocol","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","doc:\/\/com.sendbird.uikit\/s7CVarArgP","doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/s8SendableP","doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace","doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/messageLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/configure(_:hideDateView:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/configure(with:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/layoutSubviews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/setSelected(_:animated:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/setupLayouts()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/setupViews()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUAdminMessageCell"}],"title":"SBUAdminMessageCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUAdminMessageCell","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUAdminMessageCell"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions"},"doc://com.sendbird.uikit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSObject"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer"},"doc://com.sendbird.uikit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer"},"doc://com.sendbird.uikit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment"},"doc://com.sendbird.uikit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem"},"doc://com.sendbird.uikit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.sendbird.uikit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP"},"doc://com.sendbird.uikit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell/setSelected(_:animated:)":{"role":"symbol","title":"setSelected(_:animated:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSelected"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/setSelected(_:animated:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSelected:animated:"}],"url":"\/documentation\/sendbirduikit\/sbuadminmessagecell\/setselected(_:animated:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell/messageLabel":{"role":"symbol","title":"messageLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/messageLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageLabel"}],"url":"\/documentation\/sendbirduikit\/sbuadminmessagecell\/messagelabel"},"doc://com.sendbird.uikit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.sendbird.uikit\/s8SendableP"},"doc://com.sendbird.uikit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell/configure(_:hideDateView:)":{"deprecated":true,"role":"symbol","title":"configure(_:hideDateView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AdminMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDAdminMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/configure(_:hideDateView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configure:hideDateView:"}],"url":"\/documentation\/sendbirduikit\/sbuadminmessagecell\/configure(_:hidedateview:)"},"doc://com.sendbird.uikit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUViewLifeCycle":{"role":"symbol","title":"SBUViewLifeCycle","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUViewLifeCycle"}],"abstract":[{"type":"text","text":"The protocol to manage the life cylce of some views. It defines setting views, styles, auto layouts and actions."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUViewLifeCycle"}],"url":"\/documentation\/sendbirduikit\/sbuviewlifecycle"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell/setupViews()":{"role":"symbol","title":"setupViews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of views."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/setupViews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupViews"}],"url":"\/documentation\/sendbirduikit\/sbuadminmessagecell\/setupviews()"},"doc://com.sendbird.uikit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.uikit\/s7CVarArgP"},"doc://com.sendbird.uikit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance"},"doc://com.sendbird.uikit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.sendbird.uikit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem"},"doc://com.sendbird.uikit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment"},"doc://com.sendbird.uikit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace"},"doc://com.sendbird.uikit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/sendbirduikit\/sbuadminmessagecell\/initwithcoder:"},"doc://com.sendbird.uikit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageCellProtocol":{"role":"symbol","title":"SBUMessageCellProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageCellProtocol"}],"abstract":[{"type":"text","text":"The protocol to configure message cells. It conforms to "},{"type":"codeVoice","code":"SBUViewLifeCycle"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageCellProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageCellProtocol"}],"url":"\/documentation\/sendbirduikit\/sbumessagecellprotocol"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell/configure(with:)":{"role":"symbol","title":"configure(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUBaseMessageCellParams","preciseIdentifier":"s:13SendbirdUIKit24SBUBaseMessageCellParamsC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function configure a cell using informations."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/configure(with:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbuadminmessagecell\/configure(with:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/sendbirduikit\/sbuadminmessagecell\/layoutsubviews()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell":{"role":"symbol","title":"SBUBaseMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell":{"role":"symbol","title":"SBUAdminMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUAdminMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUAdminMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbuadminmessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell/setupLayouts()":{"role":"symbol","title":"setupLayouts()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLayouts"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of autolayouts."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/setupLayouts()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupLayouts"}],"url":"\/documentation\/sendbirduikit\/sbuadminmessagecell\/setuplayouts()"},"doc://com.sendbird.uikit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell/initWithStyle:reuseIdentifier:":{"role":"symbol","title":"initWithStyle:reuseIdentifier:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/initWithStyle:reuseIdentifier:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/sendbirduikit\/sbuadminmessagecell\/initwithstyle:reuseidentifier:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBUAdminMessageCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBUAdminMessageCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBUAdminMessageCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/messageLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/configure(_:hideDateView:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/initWithCoder:","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/initWithStyle:reuseIdentifier:","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/layoutSubviews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/setSelected(_:animated:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/setupLayouts()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell\/setupViews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUAdminMessageCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseMessageCell","text":"SBUBaseMessageCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1setSelected(_:animated:)\/title","value":"setSelected:animated:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1setSelected(_:animated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSelected:animated:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1messageLabel\/title","value":"messageLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1messageLabel\/fragments","value":[{"kind":"identifier","text":"messageLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1configure(_:hideDateView:)\/title","value":"configure:hideDateView:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1configure(_:hideDateView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configure:hideDateView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/title","value":"SBUViewLifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/fragments","value":[{"kind":"identifier","text":"SBUViewLifeCycle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1setupViews()\/title","value":"setupViews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1setupViews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell\/title","value":"SBUBaseMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUBaseMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell\/title","value":"SBUAdminMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUAdminMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1setupLayouts()\/title","value":"setupLayouts"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell~1setupLayouts()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupLayouts"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}