{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@IBDesignable"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseMessageCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbubasemessagecell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbubasemessagecell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUTableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding","doc:\/\/com.sendbird.uikit\/objc(pl)NSObject","doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageCellProtocol","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","doc:\/\/com.sendbird.uikit\/s7CVarArgP","doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/s8SendableP","doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace","doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/dateView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/groupPosition","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/message","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/messageContentView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/position","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/receiptState","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/stackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/stackViewTopConstraint","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/theme"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/configure(highlightInfo:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/configure(message:position:hideDateView:groupPosition:receiptState:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/configure(with:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/prepareForReuse()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupActions()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupLayouts()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupStyles()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupViews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/updateTopAnchorConstraint()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseMessageCell"}],"title":"SBUBaseMessageCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUBaseMessageCell","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUBaseMessageCell"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/stackViewTopConstraint":{"role":"symbol","title":"stackViewTopConstraint","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackViewTopConstraint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/stackViewTopConstraint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stackViewTopConstraint"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/stackviewtopconstraint"},"doc://com.sendbird.uikit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/configure(highlightInfo:)":{"role":"symbol","title":"configure(highlightInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"highlightInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUHighlightMessageInfo","preciseIdentifier":"s:13SendbirdUIKit23SBUHighlightMessageInfoV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Adds highlight attribute to the message"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/configure(highlightInfo:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/configure(highlightinfo:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUAdminMessageCell":{"role":"symbol","title":"SBUAdminMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUAdminMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUAdminMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbuadminmessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/initWithStyle:reuseIdentifier:":{"role":"symbol","title":"initWithStyle:reuseIdentifier:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/initWithStyle:reuseIdentifier:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/initwithstyle:reuseidentifier:"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/receiptState":{"role":"symbol","title":"receiptState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiptState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUMessageReceiptState","preciseIdentifier":"c:@M@SendbirdUIKit@E@SBUMessageReceiptState"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/receiptState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"receiptState"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/receiptstate"},"doc://com.sendbird.uikit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.uikit\/s7CVarArgP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/setupActions()":{"role":"symbol","title":"setupActions()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupActions"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of actions."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupActions()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupActions"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/setupactions()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageCellProtocol":{"role":"symbol","title":"SBUMessageCellProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageCellProtocol"}],"abstract":[{"type":"text","text":"The protocol to configure message cells. It conforms to "},{"type":"codeVoice","code":"SBUViewLifeCycle"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageCellProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageCellProtocol"}],"url":"\/documentation\/sendbirduikit\/sbumessagecellprotocol"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/dateView":{"role":"symbol","title":"dateView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/dateView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dateView"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/dateview"},"doc://com.sendbird.uikit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.sendbird.uikit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/message","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"message"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/message"},"doc://com.sendbird.uikit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUContentBaseMessageCell":{"role":"symbol","title":"SBUContentBaseMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUContentBaseMessageCell"}],"abstract":[{"type":"text","text":"It is a base class used in message cell with contents."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUContentBaseMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbucontentbasemessagecell"},"doc://com.sendbird.uikit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer"},"doc://com.sendbird.uikit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate"},"doc://com.sendbird.uikit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/groupPosition":{"role":"symbol","title":"groupPosition","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageGroupPosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessageGroupPosition"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/groupPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupPosition"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/groupposition"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/setupStyles()":{"role":"symbol","title":"setupStyles()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupStyles"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupStyles()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupStyles"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/setupstyles()"},"doc://com.sendbird.uikit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSObject"},"doc://com.sendbird.uikit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/setupViews()":{"role":"symbol","title":"setupViews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of views."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupViews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupViews"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/setupviews()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/updateTopAnchorConstraint()":{"role":"symbol","title":"updateTopAnchorConstraint()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateTopAnchorConstraint"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/updateTopAnchorConstraint()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateTopAnchorConstraint"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/updatetopanchorconstraint()"},"doc://com.sendbird.uikit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification"},"doc://com.sendbird.uikit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUTableViewCell":{"role":"symbol","title":"SBUTableViewCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUTableViewCell"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UITableViewCell"},{"type":"text","text":" conforming to "},{"type":"codeVoice","code":"SBUViewLifeCycle"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUTableViewCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUTableViewCell"}],"url":"\/documentation\/sendbirduikit\/sbutableviewcell"},"doc://com.sendbird.uikit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUViewLifeCycle":{"role":"symbol","title":"SBUViewLifeCycle","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUViewLifeCycle"}],"abstract":[{"type":"text","text":"The protocol to manage the life cylce of some views. It defines setting views, styles, auto layouts and actions."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUViewLifeCycle"}],"url":"\/documentation\/sendbirduikit\/sbuviewlifecycle"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell":{"role":"symbol","title":"SBUBaseMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/prepareForReuse()":{"role":"symbol","title":"prepareForReuse()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForReuse"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/prepareForReuse()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareForReuse"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/prepareforreuse()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/setupLayouts()":{"role":"symbol","title":"setupLayouts()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLayouts"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of autolayouts."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupLayouts()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupLayouts"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/setuplayouts()"},"doc://com.sendbird.uikit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/initwithcoder:"},"doc://com.sendbird.uikit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"},"doc://com.sendbird.uikit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.sendbird.uikit\/s8SendableP"},"doc://com.sendbird.uikit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/position":{"role":"symbol","title":"position","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessagePosition"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/position","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"position"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/position"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/configure(message:position:hideDateView:groupPosition:receiptState:)":{"deprecated":true,"role":"symbol","title":"configure(message:position:hideDateView:groupPosition:receiptState:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessagePosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageGroupPosition","preciseIdentifier":"c:@M@SendbirdUIKit@E@MessageGroupPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"receiptState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUMessageReceiptState","preciseIdentifier":"c:@M@SendbirdUIKit@E@SBUMessageReceiptState"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function configure a cell using informations."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/configure(message:position:hideDateView:groupPosition:receiptState:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configureWithMessage:position:hideDateView:groupPosition:receiptState:"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/configure(message:position:hidedateview:groupposition:receiptstate:)"},"doc://com.sendbird.uikit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions"},"doc://com.sendbird.uikit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.sendbird.uikit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/messageContentView":{"role":"symbol","title":"messageContentView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageContentView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/messageContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageContentView"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/messagecontentview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/stackView":{"role":"symbol","title":"stackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIStackView","preciseIdentifier":"c:objc(cs)UIStackView"}],"abstract":[{"type":"text","text":"A stack view that contains "},{"type":"codeVoice","code":"dateView"},{"type":"text","text":" and "},{"type":"codeVoice","code":"messageContentView"},{"type":"text","text":" "},{"type":"text","text":"The default value is "},{"type":"codeVoice","code":"SBUStackView"},{"type":"text","text":" with "},{"type":"codeVoice","code":".vertical"},{"type":"text","text":" axis and spacing value "},{"type":"codeVoice","code":"16"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/stackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stackView"}],"url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/stackview"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/theme":{"role":"symbol","title":"theme","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUMessageCellTheme","preciseIdentifier":"s:13SendbirdUIKit19SBUMessageCellThemeC"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/theme","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/theme"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseMessageCell/configure(with:)":{"role":"symbol","title":"configure(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUBaseMessageCellParams","preciseIdentifier":"s:13SendbirdUIKit24SBUBaseMessageCellParamsC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function configure a cell using informations."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/configure(with:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbubasemessagecell\/configure(with:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBUBaseMessageCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBUBaseMessageCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBUBaseMessageCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/dateView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/groupPosition","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/message","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/messageContentView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/position","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/receiptState","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/stackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/stackViewTopConstraint"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/configure(message:position:hideDateView:groupPosition:receiptState:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/initWithCoder:","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/initWithStyle:reuseIdentifier:","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/prepareForReuse()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupActions()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupLayouts()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupStyles()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/setupViews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseMessageCell\/updateTopAnchorConstraint()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUTableViewCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUAdminMessageCell","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUContentBaseMessageCell"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseMessageCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUTableViewCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUTableViewCell","text":"SBUTableViewCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1stackViewTopConstraint\/title","value":"stackViewTopConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1stackViewTopConstraint\/fragments","value":[{"kind":"identifier","text":"stackViewTopConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell\/title","value":"SBUAdminMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUAdminMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUAdminMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1receiptState\/title","value":"receiptState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1receiptState\/fragments","value":[{"kind":"identifier","text":"receiptState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1setupActions()\/title","value":"setupActions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1setupActions()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupActions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1dateView\/title","value":"dateView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1dateView\/fragments","value":[{"kind":"identifier","text":"dateView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1message\/title","value":"message"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1message\/fragments","value":[{"kind":"identifier","text":"message"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUContentBaseMessageCell\/title","value":"SBUContentBaseMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUContentBaseMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUContentBaseMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1groupPosition\/title","value":"groupPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1groupPosition\/fragments","value":[{"kind":"identifier","text":"groupPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1setupStyles()\/title","value":"setupStyles"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1setupStyles()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupStyles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1setupViews()\/title","value":"setupViews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1setupViews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1updateTopAnchorConstraint()\/title","value":"updateTopAnchorConstraint"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1updateTopAnchorConstraint()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateTopAnchorConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUTableViewCell\/title","value":"SBUTableViewCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUTableViewCell\/fragments","value":[{"kind":"identifier","text":"SBUTableViewCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/title","value":"SBUViewLifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/fragments","value":[{"kind":"identifier","text":"SBUViewLifeCycle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell\/title","value":"SBUBaseMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUBaseMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1prepareForReuse()\/title","value":"prepareForReuse"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1prepareForReuse()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForReuse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1setupLayouts()\/title","value":"setupLayouts"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1setupLayouts()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupLayouts"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1position\/title","value":"position"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1position\/fragments","value":[{"kind":"identifier","text":"position"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1configure(message:position:hideDateView:groupPosition:receiptState:)\/title","value":"configureWithMessage:position:hideDateView:groupPosition:receiptState:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1configure(message:position:hideDateView:groupPosition:receiptState:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configureWithMessage:position:hideDateView:groupPosition:receiptState:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1messageContentView\/title","value":"messageContentView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1messageContentView\/fragments","value":[{"kind":"identifier","text":"messageContentView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1stackView\/title","value":"stackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseMessageCell~1stackView\/fragments","value":[{"kind":"identifier","text":"stackView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}