{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCommonViewModelDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonDelegate","preciseIdentifier":"s:13SendbirdUIKit17SBUCommonDelegateP","text":"SBUCommonDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbucommonviewmodeldelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewModelDelegate"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate\/connectionStateDidChange(_:)-7s03n","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate\/didReceiveError(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate\/shouldUpdateLoadingState(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCommonViewModelDelegate"}],"title":"SBUCommonViewModelDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:13SendbirdUIKit26SBUCommonViewModelDelegateP","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUCommonViewModelDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModelDelegate":{"role":"symbol","title":"SBUGroupChannelListViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserViewController":{"role":"symbol","title":"SBUBaseSelectUserViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserViewController"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectuserviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewModelDelegate":{"role":"symbol","title":"SBUBaseChannelSettingsViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelSettingsViewModelDelegate":{"role":"symbol","title":"SBUGroupChannelSettingsViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelSettingsViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelSettingsViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewController":{"role":"symbol","title":"SBUGroupChannelListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUModerationsViewController":{"role":"symbol","title":"SBUModerationsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUModerationsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUModerationsViewController"}],"url":"\/documentation\/sendbirduikit\/sbumoderationsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewController":{"role":"symbol","title":"SBUBaseChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelViewController":{"role":"symbol","title":"SBUCreateChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewModelDelegate":{"role":"symbol","title":"SBUGroupChannelPushSettingsViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewModelDelegate":{"role":"symbol","title":"SBUOpenChannelViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewController":{"role":"symbol","title":"SBUGroupChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewModelDelegate":{"role":"symbol","title":"SBUOpenChannelSettingsViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCommonViewModelDelegate/connectionStateDidChange(_:)-7s03n":{"defaultImplementations":1,"role":"symbol","title":"connectionStateDidChange(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionStateDidChange"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate\/connectionStateDidChange(_:)-7s03n","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirduikit\/sbucommonviewmodeldelegate\/connectionstatedidchange(_:)-7s03n"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCommonViewModelDelegate":{"role":"symbol","title":"SBUCommonViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCommonViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCommonViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbucommonviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserViewModelDelegate":{"role":"symbol","title":"SBUBaseSelectUserViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectuserviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageSearchViewModelDelegate":{"role":"symbol","title":"SBUMessageSearchViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageSearchViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageSearchViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbumessagesearchviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCreateChannelViewModelDelegate":{"role":"symbol","title":"SBUCreateChannelViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCreateChannelViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCreateChannelViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCreateChannelViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbucreatechannelviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewController":{"role":"symbol","title":"SBUBaseChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelPushSettingsViewController":{"role":"symbol","title":"SBUGroupChannelPushSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelPushSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelpushsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelSettingsViewController":{"role":"symbol","title":"SBUGroupChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCommonDelegate":{"role":"symbol","title":"SBUCommonDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCommonDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCommonDelegate"}],"url":"\/documentation\/sendbirduikit\/sbucommondelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController":{"role":"symbol","title":"SBURegisterOperatorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelViewModelDelegate":{"role":"symbol","title":"SBUBaseChannelViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelViewModelDelegate"}],"abstract":[{"type":"text","text":"Methods for notifying the data updates from the "},{"type":"codeVoice","code":"SBUBaseChannelViewModel"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewModelDelegate":{"role":"symbol","title":"SBURegisterOperatorViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelViewController":{"role":"symbol","title":"SBUOpenChannelViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelViewController"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUModerationsViewModelDelegate":{"role":"symbol","title":"SBUModerationsViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUModerationsViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUModerationsViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbumoderationsviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserViewModelDelegate":{"role":"symbol","title":"SBUInviteUserViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUInviteUserViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUInviteUserViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbuinviteuserviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCommonViewModelDelegate/shouldUpdateLoadingState(_:)":{"role":"symbol","title":"shouldUpdateLoadingState(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldUpdateLoadingState"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate\/shouldUpdateLoadingState(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirduikit\/sbucommonviewmodeldelegate\/shouldupdateloadingstate(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewController":{"role":"symbol","title":"SBUUserListViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserListViewController"}],"abstract":[{"type":"text","text":"This class handling members,  operators,  muted\/Participants,  banned,  participants,"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserListViewController"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCommonViewModelDelegate/didReceiveError(_:)":{"role":"symbol","title":"didReceiveError(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBError","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBError"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate\/didReceiveError(_:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbucommonviewmodeldelegate\/didreceiveerror(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageSearchViewController":{"role":"symbol","title":"SBUMessageSearchViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageSearchViewController"}],"abstract":[{"type":"text","text":"ViewController handling a message search."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageSearchViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageSearchViewController"}],"url":"\/documentation\/sendbirduikit\/sbumessagesearchviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController":{"role":"symbol","title":"SBUOpenChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUUserListViewModelDelegate":{"role":"symbol","title":"SBUUserListViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUUserListViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUUserListViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUUserListViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbuuserlistviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelViewModelDelegate":{"role":"symbol","title":"SBUGroupChannelViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUInviteUserViewController":{"role":"symbol","title":"SBUInviteUserViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUInviteUserViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUInviteUserViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUInviteUserViewController"}],"url":"\/documentation\/sendbirduikit\/sbuinviteuserviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseSelectUserViewController\/title","value":"SBUBaseSelectUserViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseSelectUserViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseSelectUserViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/title","value":"SBUGroupChannelListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController\/title","value":"SBUModerationsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController\/fragments","value":[{"kind":"identifier","text":"SBUModerationsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/title","value":"SBUBaseChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController\/title","value":"SBUCreateChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUCreateChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUCreateChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/title","value":"SBUGroupChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/title","value":"SBUBaseChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController\/title","value":"SBUGroupChannelPushSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelPushSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelPushSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewController\/title","value":"SBUGroupChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/title","value":"SBURegisterOperatorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/fragments","value":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController\/title","value":"SBUOpenChannelViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelViewController\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/title","value":"SBUUserListViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUUserListViewController\/fragments","value":[{"kind":"identifier","text":"SBUUserListViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageSearchViewController\/title","value":"SBUMessageSearchViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageSearchViewController\/fragments","value":[{"kind":"identifier","text":"SBUMessageSearchViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController\/title","value":"SBUOpenChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController\/title","value":"SBUInviteUserViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUInviteUserViewController\/fragments","value":[{"kind":"identifier","text":"SBUInviteUserViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}