{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannelcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding","doc:\/\/com.sendbird.uikit\/objc(pl)NSObject","doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","doc:\/\/com.sendbird.uikit\/s7CVarArgP","doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/s8SendableP","doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace","doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"UITableViewCell"},{"type":"text","text":" of the table view that represents the list of group channels."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelCell"}],"title":"SBUGroupChannelCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUGroupChannelCell","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelCell"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/broadcastIcon","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/contentStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/coverImage","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/coverImageSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/freezeState","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/infoIconSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/infoStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/kCoverImageSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/kInfoIconSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/kUnreadCountSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/lastUpdatedTimeLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/memberCountLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/messageLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/messageSpacer","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/messageStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/notificationState","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/separatorLine","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/stateImageView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/theme","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/titleLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/titleSpacer","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/titleStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/unreadCount","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/unreadCountSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/unreadMentionLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/awakeFromNib()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/buildLastUpdatedDate()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/configure(channel:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/layoutSubviews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/prepareForReuse()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupActions()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupLayouts()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupStyles()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupViews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/updateMessageLabel()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/updateStateImageView()"]}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/prepareForReuse()":{"role":"symbol","title":"prepareForReuse()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepareForReuse"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/prepareForReuse()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepareForReuse"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/prepareforreuse()"},"doc://com.sendbird.uikit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUViewLifeCycle":{"role":"symbol","title":"SBUViewLifeCycle","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUViewLifeCycle"}],"abstract":[{"type":"text","text":"The protocol to manage the life cylce of some views. It defines setting views, styles, auto layouts and actions."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUViewLifeCycle"}],"url":"\/documentation\/sendbirduikit\/sbuviewlifecycle"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/stateImageView":{"role":"symbol","title":"stateImageView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"stateImageView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view that represents read\/delivery receipt state of the last message that was sent by the current user."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/stateImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"stateImageView"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/stateimageview"},"doc://com.sendbird.uikit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/notificationState":{"role":"symbol","title":"notificationState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"notificationState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view that indicates the notification state of the channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/notificationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"notificationState"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/notificationstate"},"doc://com.sendbird.uikit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace"},"doc://com.sendbird.uikit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/setupActions()":{"role":"symbol","title":"setupActions()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupActions"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of actions."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupActions()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupActions"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/setupactions()"},"doc://com.sendbird.uikit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/coverImageSize":{"role":"symbol","title":"coverImageSize","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"A value used in the size of "},{"type":"codeVoice","code":"coverImage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/coverImageSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coverImageSize"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/coverimagesize"},"doc://com.sendbird.uikit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer"},"doc://com.sendbird.uikit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.sendbird.uikit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.sendbird.uikit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.sendbird.uikit\/s8SendableP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/unreadCountSize":{"role":"symbol","title":"unreadCountSize","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadCountSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"A value used in the height of "},{"type":"codeVoice","code":"unreadCount"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/unreadCountSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unreadCountSize"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/unreadcountsize"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/lastUpdatedTimeLabel":{"role":"symbol","title":"lastUpdatedTimeLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lastUpdatedTimeLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that represents the time when the channel is updated last. e.g. the time when the last message was sent at."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/lastUpdatedTimeLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"lastUpdatedTimeLabel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/lastupdatedtimelabel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/coverImage":{"role":"symbol","title":"coverImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUCoverImageView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUCoverImageView"}],"abstract":[{"type":"text","text":"The image view that shows the channel cover image."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/coverImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coverImage"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/coverimage"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/setupStyles()":{"role":"symbol","title":"setupStyles()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupStyles"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of styles."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupStyles()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupStyles"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/setupstyles()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/buildLastUpdatedDate()":{"role":"symbol","title":"buildLastUpdatedDate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildLastUpdatedDate"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"This function builds last message updated date."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/buildLastUpdatedDate()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"buildLastUpdatedDate"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/buildlastupdateddate()"},"doc://com.sendbird.uikit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/setupLayouts()":{"role":"symbol","title":"setupLayouts()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLayouts"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of autolayouts."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupLayouts()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupLayouts"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/setuplayouts()"},"doc://com.sendbird.uikit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment"},"doc://com.sendbird.uikit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer"},"doc://com.sendbird.uikit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSObject"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/updateMessageLabel()":{"role":"symbol","title":"updateMessageLabel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateMessageLabel"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Updates message label when someone is typing. To show typing indicator, set "},{"type":"codeVoice","code":"SBUGlobals.isChannelListTypingIndicatorEnabled"},{"type":"text","text":" to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/updateMessageLabel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateMessageLabel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/updatemessagelabel()"},"doc://com.sendbird.uikit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/initWithStyle:reuseIdentifier:":{"role":"symbol","title":"initWithStyle:reuseIdentifier:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/initWithStyle:reuseIdentifier:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/initwithstyle:reuseidentifier:"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/unreadCount":{"role":"symbol","title":"unreadCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"abstract":[{"type":"text","text":"The button that shows the number of the unread messages."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/unreadCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unreadCount"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/unreadcount"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/messageStackView":{"role":"symbol","title":"messageStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"abstract":[{"type":"text","text":"A horizontal stack view to configure layouts of the "},{"type":"codeVoice","code":"messageLabel"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"unreadCount"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/messageStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageStackView"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/messagestackview"},"doc://com.sendbird.uikit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions"},"doc://com.sendbird.uikit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/infoStackView":{"role":"symbol","title":"infoStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"abstract":[{"type":"text","text":"A vertical stack view to configure layouts of labels and icons that represent the channel information."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/infoStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"infoStackView"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/infostackview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/unreadMentionLabel":{"role":"symbol","title":"unreadMentionLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unreadMentionLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that shows the unread mention messages."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/unreadMentionLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unreadMentionLabel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/unreadmentionlabel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell":{"role":"symbol","title":"SBUGroupChannelCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelCell"}],"abstract":[{"type":"codeVoice","code":"UITableViewCell"},{"type":"text","text":" of the table view that represents the list of group channels."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelCell"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell"},"doc://com.sendbird.uikit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/titleSpacer":{"role":"symbol","title":"titleSpacer","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleSpacer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"A spacer used in "},{"type":"codeVoice","code":"titleStackView"},{"type":"text","text":" to provide spacing between "},{"type":"codeVoice","code":"titleLabel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"lastUpdatedTimeLabel"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/titleSpacer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleSpacer"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/titlespacer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/initwithcoder:"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/kInfoIconSize":{"deprecated":true,"role":"symbol","title":"kInfoIconSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kInfoIconSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/kInfoIconSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kInfoIconSize"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/kinfoiconsize"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/theme":{"role":"symbol","title":"theme","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUChannelCellTheme","preciseIdentifier":"s:13SendbirdUIKit19SBUChannelCellThemeC"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/theme","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/theme"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/updateStateImageView()":{"role":"symbol","title":"updateStateImageView()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateStateImageView"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Updates the image view that represents read\/delivery receipt state. The image view is displayed when the last message was sent by the current user. To show the state image view, set "},{"type":"codeVoice","code":"SBUGlobals.isChannelListMessageReceiptStateEnabled"},{"type":"text","text":" to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/updateStateImageView()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateStateImageView"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/updatestateimageview()"},"doc://com.sendbird.uikit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP"},"doc://com.sendbird.uikit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification"},"doc://com.sendbird.uikit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.uikit\/s7CVarArgP"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/layoutsubviews()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that represents the channel name."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/titleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/titlelabel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/awakefromnib()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/broadcastIcon":{"role":"symbol","title":"broadcastIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"broadcastIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view that shows the broadcast icon."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/broadcastIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"broadcastIcon"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/broadcasticon"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/kUnreadCountSize":{"deprecated":true,"role":"symbol","title":"kUnreadCountSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kUnreadCountSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/kUnreadCountSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kUnreadCountSize"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/kunreadcountsize"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelCell":{"role":"symbol","title":"SBUBaseChannelCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelCell"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelcell"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/messageSpacer":{"role":"symbol","title":"messageSpacer","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageSpacer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"A spacer used in "},{"type":"codeVoice","code":"messageStackView"},{"type":"text","text":" to provide spacing between "},{"type":"codeVoice","code":"messageLabel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"unreadCount"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/messageSpacer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageSpacer"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/messagespacer"},"doc://com.sendbird.uikit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/configure(channel:)":{"role":"symbol","title":"configure(channel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function configure a cell using "},{"type":"codeVoice","code":"GroupChannel"},{"type":"text","text":" information."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/configure(channel:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configureWithChannel:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/configure(channel:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/infoIconSize":{"role":"symbol","title":"infoIconSize","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoIconSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"A value used in the size of icon image views."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/infoIconSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"infoIconSize"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/infoiconsize"},"doc://com.sendbird.uikit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/freezeState":{"role":"symbol","title":"freezeState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"freezeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view that indicates the freezing state of the channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/freezeState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"freezeState"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/freezestate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/contentStackView":{"role":"symbol","title":"contentStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"abstract":[{"type":"text","text":"A horizontal stack view to configure layouts of the entire view properties."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/contentStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentStackView"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/contentstackview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/messageLabel":{"role":"symbol","title":"messageLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that shows the last message in up to 2 lines of text."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/messageLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageLabel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/messagelabel"},"doc://com.sendbird.uikit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/kCoverImageSize":{"deprecated":true,"role":"symbol","title":"kCoverImageSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"kCoverImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/kCoverImageSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kCoverImageSize"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/kcoverimagesize"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/titleStackView":{"role":"symbol","title":"titleStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"abstract":[{"type":"text","text":"A horizontal stack view to configure layouts of the "},{"type":"codeVoice","code":"titleLabel"},{"type":"text","text":", "},{"type":"codeVoice","code":"lastUpdatedTimeLabel"},{"type":"text","text":" and icons."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/titleStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleStackView"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/titlestackview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/setupViews()":{"role":"symbol","title":"setupViews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of views."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupViews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupViews"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/setupviews()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/memberCountLabel":{"role":"symbol","title":"memberCountLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberCountLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that represents the number of members in the channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/memberCountLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memberCountLabel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/membercountlabel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelCell/separatorLine":{"role":"symbol","title":"separatorLine","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"separatorLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"A view that is used as a separator between the channel cells."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/separatorLine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"separatorLine"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelcell\/separatorline"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBUGroupChannelCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBUGroupChannelCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/broadcastIcon","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/contentStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/coverImage","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/coverImageSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/freezeState","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/infoIconSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/infoStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/kCoverImageSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/kInfoIconSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/kUnreadCountSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/lastUpdatedTimeLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/memberCountLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/messageLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/messageSpacer","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/messageStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/notificationState","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/separatorLine","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/stateImageView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/titleLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/titleSpacer","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/titleStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/unreadCount","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/unreadCountSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/unreadMentionLabel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/awakeFromNib()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/buildLastUpdatedDate()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/configure(channel:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/initWithCoder:","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/initWithStyle:reuseIdentifier:","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/layoutSubviews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/prepareForReuse()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupActions()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupLayouts()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupStyles()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/setupViews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/updateMessageLabel()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelCell\/updateStateImageView()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelCell","text":"SBUBaseChannelCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1prepareForReuse()\/title","value":"prepareForReuse"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1prepareForReuse()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prepareForReuse"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/title","value":"SBUViewLifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/fragments","value":[{"kind":"identifier","text":"SBUViewLifeCycle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1stateImageView\/title","value":"stateImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1stateImageView\/fragments","value":[{"kind":"identifier","text":"stateImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1notificationState\/title","value":"notificationState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1notificationState\/fragments","value":[{"kind":"identifier","text":"notificationState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1setupActions()\/title","value":"setupActions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1setupActions()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupActions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1coverImageSize\/title","value":"coverImageSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1coverImageSize\/fragments","value":[{"kind":"identifier","text":"coverImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1unreadCountSize\/title","value":"unreadCountSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1unreadCountSize\/fragments","value":[{"kind":"identifier","text":"unreadCountSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1lastUpdatedTimeLabel\/title","value":"lastUpdatedTimeLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1lastUpdatedTimeLabel\/fragments","value":[{"kind":"identifier","text":"lastUpdatedTimeLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1coverImage\/title","value":"coverImage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1coverImage\/fragments","value":[{"kind":"identifier","text":"coverImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1setupStyles()\/title","value":"setupStyles"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1setupStyles()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupStyles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1buildLastUpdatedDate()\/title","value":"buildLastUpdatedDate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1buildLastUpdatedDate()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"buildLastUpdatedDate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1setupLayouts()\/title","value":"setupLayouts"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1setupLayouts()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupLayouts"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1updateMessageLabel()\/title","value":"updateMessageLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1updateMessageLabel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateMessageLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1unreadCount\/title","value":"unreadCount"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1unreadCount\/fragments","value":[{"kind":"identifier","text":"unreadCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1messageStackView\/title","value":"messageStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1messageStackView\/fragments","value":[{"kind":"identifier","text":"messageStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1infoStackView\/title","value":"infoStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1infoStackView\/fragments","value":[{"kind":"identifier","text":"infoStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1unreadMentionLabel\/title","value":"unreadMentionLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1unreadMentionLabel\/fragments","value":[{"kind":"identifier","text":"unreadMentionLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell\/title","value":"SBUGroupChannelCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1titleSpacer\/title","value":"titleSpacer"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1titleSpacer\/fragments","value":[{"kind":"identifier","text":"titleSpacer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1kInfoIconSize\/title","value":"kInfoIconSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1kInfoIconSize\/fragments","value":[{"kind":"identifier","text":"kInfoIconSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1updateStateImageView()\/title","value":"updateStateImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1updateStateImageView()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateStateImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1broadcastIcon\/title","value":"broadcastIcon"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1broadcastIcon\/fragments","value":[{"kind":"identifier","text":"broadcastIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1kUnreadCountSize\/title","value":"kUnreadCountSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1kUnreadCountSize\/fragments","value":[{"kind":"identifier","text":"kUnreadCountSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelCell\/title","value":"SBUBaseChannelCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelCell\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1messageSpacer\/title","value":"messageSpacer"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1messageSpacer\/fragments","value":[{"kind":"identifier","text":"messageSpacer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1configure(channel:)\/title","value":"configureWithChannel:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1configure(channel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configureWithChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1infoIconSize\/title","value":"infoIconSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1infoIconSize\/fragments","value":[{"kind":"identifier","text":"infoIconSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1freezeState\/title","value":"freezeState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1freezeState\/fragments","value":[{"kind":"identifier","text":"freezeState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1contentStackView\/title","value":"contentStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1contentStackView\/fragments","value":[{"kind":"identifier","text":"contentStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1messageLabel\/title","value":"messageLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1messageLabel\/fragments","value":[{"kind":"identifier","text":"messageLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1kCoverImageSize\/title","value":"kCoverImageSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1kCoverImageSize\/fragments","value":[{"kind":"identifier","text":"kCoverImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1titleStackView\/title","value":"titleStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1titleStackView\/fragments","value":[{"kind":"identifier","text":"titleStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1setupViews()\/title","value":"setupViews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1setupViews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1memberCountLabel\/title","value":"memberCountLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1memberCountLabel\/fragments","value":[{"kind":"identifier","text":"memberCountLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1separatorLine\/title","value":"separatorLine"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelCell~1separatorLine\/fragments","value":[{"kind":"identifier","text":"separatorLine"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}