{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBULinkClickableTextView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbulinkclickabletextview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbulinkclickabletextview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/objc(cs)UITextView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding","doc:\/\/com.sendbird.uikit\/objc(pl)NSObject","doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate","doc:\/\/com.sendbird.uikit\/s7CVarArgP","doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/s8SendableP","doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIContentSizeCategoryAdjusting","doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace","doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFindInteractionDelegate","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemScrollableContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIKeyInput","doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.sendbird.uikit\/objc(pl)UITextDraggable","doc:\/\/com.sendbird.uikit\/objc(pl)UITextDroppable","doc:\/\/com.sendbird.uikit\/objc(pl)UITextInput","doc:\/\/com.sendbird.uikit\/objc(pl)UITextInputTraits","doc:\/\/com.sendbird.uikit\/objc(pl)UITextPasteConfigurationSupporting","doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/selectedTextRange"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/hitTest(_:with:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBULinkClickableTextView"}],"title":"SBULinkClickableTextView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdUIKit@objc(cs)SBULinkClickableTextView","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBULinkClickableTextView"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/objc(pl)UITextDroppable":{"type":"unresolvable","title":"UIKit.UITextDroppable","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITextDroppable"},"doc://com.sendbird.uikit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBULinkClickableTextView/selectedTextRange":{"role":"symbol","title":"selectedTextRange","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedTextRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextRange","preciseIdentifier":"c:objc(cs)UITextRange"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/selectedTextRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"selectedTextRange"}],"url":"\/documentation\/sendbirduikit\/sbulinkclickabletextview\/selectedtextrange"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions"},"doc://com.sendbird.uikit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem"},"doc://com.sendbird.uikit/objc(pl)UITextDraggable":{"type":"unresolvable","title":"UIKit.UITextDraggable","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITextDraggable"},"doc://com.sendbird.uikit/objc(pl)UIContentSizeCategoryAdjusting":{"type":"unresolvable","title":"UIKit.UIContentSizeCategoryAdjusting","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIContentSizeCategoryAdjusting"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBULinkClickableTextView/initWithFrame:textContainer:":{"role":"symbol","title":"initWithFrame:textContainer:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:textContainer:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/initWithFrame:textContainer:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:textContainer:"}],"url":"\/documentation\/sendbirduikit\/sbulinkclickabletextview\/initwithframe:textcontainer:"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer"},"doc://com.sendbird.uikit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSObject"},"doc://com.sendbird.uikit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.uikit\/s7CVarArgP"},"doc://com.sendbird.uikit/objc(pl)UITextPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UITextPasteConfigurationSupporting","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITextPasteConfigurationSupporting"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBULinkClickableTextView/hitTest(_:with:)":{"role":"symbol","title":"hitTest(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hitTest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/hitTest(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hitTest:withEvent:"}],"url":"\/documentation\/sendbirduikit\/sbulinkclickabletextview\/hittest(_:with:)"},"doc://com.sendbird.uikit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace"},"doc://com.sendbird.uikit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.sendbird.uikit/objc(pl)UIKeyInput":{"type":"unresolvable","title":"UIKit.UIKeyInput","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIKeyInput"},"doc://com.sendbird.uikit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem"},"doc://com.sendbird.uikit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"},"doc://com.sendbird.uikit/objc(pl)UIFocusItemScrollableContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemScrollableContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemScrollableContainer"},"doc://com.sendbird.uikit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification"},"doc://com.sendbird.uikit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBULinkClickableTextView":{"role":"symbol","title":"SBULinkClickableTextView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBULinkClickableTextView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBULinkClickableTextView"}],"url":"\/documentation\/sendbirduikit\/sbulinkclickabletextview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBULinkClickableTextView/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/sendbirduikit\/sbulinkclickabletextview\/initwithcoder:"},"doc://com.sendbird.uikit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.sendbird.uikit\/s8SendableP"},"doc://com.sendbird.uikit/objc(pl)UIFindInteractionDelegate":{"type":"unresolvable","title":"UIKit.UIFindInteractionDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFindInteractionDelegate"},"doc://com.sendbird.uikit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance"},"doc://com.sendbird.uikit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.uikit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.sendbird.uikit/objc(pl)UITextInput":{"type":"unresolvable","title":"UIKit.UITextInput","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITextInput"},"doc://com.sendbird.uikit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer"},"doc://com.sendbird.uikit/objc(pl)UITextInputTraits":{"type":"unresolvable","title":"UIKit.UITextInputTraits","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITextInputTraits"},"doc://com.sendbird.uikit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem"},"doc://com.sendbird.uikit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment"},"doc://com.sendbird.uikit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding"},"doc://com.sendbird.uikit/objc(cs)UITextView":{"type":"unresolvable","title":"UITextView","identifier":"doc:\/\/com.sendbird.uikit\/objc(cs)UITextView"},"doc://com.sendbird.uikit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment"},"doc://com.sendbird.uikit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBULinkClickableTextView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBULinkClickableTextView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBULinkClickableTextView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/selectedTextRange"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/hitTest(_:with:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/initWithCoder:","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULinkClickableTextView\/initWithFrame:textContainer:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.sendbird.uikit\/objc(cs)UITextView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBULinkClickableTextView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBULinkClickableTextView~1selectedTextRange\/title","value":"selectedTextRange"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBULinkClickableTextView~1selectedTextRange\/fragments","value":[{"kind":"identifier","text":"selectedTextRange"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBULinkClickableTextView~1hitTest(_:with:)\/title","value":"hitTest:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBULinkClickableTextView~1hitTest(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hitTest:withEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBULinkClickableTextView\/title","value":"SBULinkClickableTextView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBULinkClickableTextView\/fragments","value":[{"kind":"identifier","text":"SBULinkClickableTextView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}