{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageDateView"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbumessagedateview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbumessagedateview"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding","doc:\/\/com.sendbird.uikit\/objc(pl)NSObject","doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","doc:\/\/com.sendbird.uikit\/s7CVarArgP","doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/s8SendableP","doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace","doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/dateLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/theme"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/configure(timestamp:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/setupLayouts()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/setupStyles()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/setupViews()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageDateView"}],"title":"SBUMessageDateView","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUMessageDateView","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUMessageDateView"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUViewLifeCycle":{"role":"symbol","title":"SBUViewLifeCycle","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUViewLifeCycle"}],"abstract":[{"type":"text","text":"The protocol to manage the life cylce of some views. It defines setting views, styles, auto layouts and actions."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUViewLifeCycle"}],"url":"\/documentation\/sendbirduikit\/sbuviewlifecycle"},"doc://com.sendbird.uikit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageDateView/setupViews()":{"role":"symbol","title":"setupViews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/setupViews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupViews"}],"url":"\/documentation\/sendbirduikit\/sbumessagedateview\/setupviews()"},"doc://com.sendbird.uikit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageDateView/theme":{"role":"symbol","title":"theme","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUMessageCellTheme","preciseIdentifier":"s:13SendbirdUIKit19SBUMessageCellThemeC"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/theme","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessagedateview\/theme"},"doc://com.sendbird.uikit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment"},"doc://com.sendbird.uikit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.uikit\/s7CVarArgP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageDateView/configure(timestamp:)":{"role":"symbol","title":"configure(timestamp:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"timestamp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/configure(timestamp:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessagedateview\/configure(timestamp:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageDateView/setupLayouts()":{"role":"symbol","title":"setupLayouts()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLayouts"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/setupLayouts()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupLayouts"}],"url":"\/documentation\/sendbirduikit\/sbumessagedateview\/setuplayouts()"},"doc://com.sendbird.uikit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.sendbird.uikit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageDateView/initWithFrame:":{"role":"symbol","title":"initWithFrame:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/initWithFrame:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/sendbirduikit\/sbumessagedateview\/initwithframe:"},"doc://com.sendbird.uikit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP"},"doc://com.sendbird.uikit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.sendbird.uikit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem"},"doc://com.sendbird.uikit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions"},"doc://com.sendbird.uikit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer"},"doc://com.sendbird.uikit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUView":{"role":"symbol","title":"SBUView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUView"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"UIView"},{"type":"text","text":" conforming to "},{"type":"codeVoice","code":"SBUViewLifeCycle"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUView"}],"url":"\/documentation\/sendbirduikit\/sbuview"},"doc://com.sendbird.uikit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.sendbird.uikit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem"},"doc://com.sendbird.uikit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate"},"doc://com.sendbird.uikit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageDateView/dateLabel":{"role":"symbol","title":"dateLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/dateLabel","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessagedateview\/datelabel"},"doc://com.sendbird.uikit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSObject"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageDateView/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sendbirduikit\/sbumessagedateview\/init"},"doc://com.sendbird.uikit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageDateView":{"role":"symbol","title":"SBUMessageDateView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageDateView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageDateView"}],"url":"\/documentation\/sendbirduikit\/sbumessagedateview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.sendbird.uikit\/s8SendableP"},"doc://com.sendbird.uikit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageDateView/setupStyles()":{"role":"symbol","title":"setupStyles()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupStyles"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/setupStyles()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupStyles"}],"url":"\/documentation\/sendbirduikit\/sbumessagedateview\/setupstyles()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBUMessageDateView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBUMessageDateView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBUMessageDateView"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/init","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/initWithFrame:","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/setupLayouts()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/setupStyles()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageDateView\/setupViews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageDateView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUView","text":"SBUView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/title","value":"SBUViewLifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/fragments","value":[{"kind":"identifier","text":"SBUViewLifeCycle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageDateView~1setupViews()\/title","value":"setupViews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageDateView~1setupViews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageDateView~1setupLayouts()\/title","value":"setupLayouts"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageDateView~1setupLayouts()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupLayouts"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUView\/title","value":"SBUView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUView\/fragments","value":[{"kind":"identifier","text":"SBUView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageDateView\/title","value":"SBUMessageDateView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageDateView\/fragments","value":[{"kind":"identifier","text":"SBUMessageDateView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageDateView~1setupStyles()\/title","value":"setupStyles"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageDateView~1setupStyles()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupStyles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}