{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageInputMode"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbumessageinputmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbumessageinputmode"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/edit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/none","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/quoteReply"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/Equatable-Implementations","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageInputMode"}],"title":"SBUMessageInputMode","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdUIKit@E@SBUMessageInputMode","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUMessageInputMode"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputMode/none":{"role":"symbol","title":"SBUMessageInputMode.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"The default mode"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageInputModeNone"}],"url":"\/documentation\/sendbirduikit\/sbumessageinputmode\/none"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputMode/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessageinputmode\/rawrepresentable-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputMode/edit":{"role":"symbol","title":"SBUMessageInputMode.edit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"edit"}],"abstract":[{"type":"text","text":"The editing mode"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/edit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageInputModeEdit"}],"url":"\/documentation\/sendbirduikit\/sbumessageinputmode\/edit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputMode/quoteReply":{"role":"symbol","title":"SBUMessageInputMode.quoteReply","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"quoteReply"}],"abstract":[{"type":"text","text":"The quote replying mode"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/quoteReply","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageInputModeQuoteReply"}],"url":"\/documentation\/sendbirduikit\/sbumessageinputmode\/quotereply"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputMode/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessageinputmode\/init(rawvalue:)"},"doc://com.sendbird.uikit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.uikit\/SY"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputMode":{"role":"symbol","title":"SBUMessageInputMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageInputMode"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageInputMode"}],"url":"\/documentation\/sendbirduikit\/sbumessageinputmode"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputMode/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessageinputmode\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBUMessageInputMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBUMessageInputMode"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBUMessageInputMode"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/edit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/none","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/quoteReply"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageInputMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode~1none\/title","value":"SBUMessageInputModeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode~1none\/fragments","value":[{"kind":"identifier","text":"SBUMessageInputModeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode~1edit\/title","value":"SBUMessageInputModeEdit"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode~1edit\/fragments","value":[{"kind":"identifier","text":"SBUMessageInputModeEdit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode~1quoteReply\/title","value":"SBUMessageInputModeQuoteReply"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode~1quoteReply\/fragments","value":[{"kind":"identifier","text":"SBUMessageInputModeQuoteReply"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode\/title","value":"SBUMessageInputMode"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode\/fragments","value":[{"kind":"identifier","text":"SBUMessageInputMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}