{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageReceiptState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbumessagereceiptstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbumessagereceiptstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is an enumeration to message receipt state."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageReceiptState"}],"title":"SBUMessageReceiptState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@SendbirdUIKit@E@SBUMessageReceiptState","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUMessageReceiptState"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/delivered","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/none","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/notUsed","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/read"]},{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/Equatable-Implementations","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate\/init(rawvalue:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState/delivered":{"role":"symbol","title":"SBUMessageReceiptState.delivered","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"delivered"}],"abstract":[{"type":"text","text":"The message is delivered"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/delivered","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageReceiptStateDelivered"}],"url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate\/delivered"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState/notUsed":{"role":"symbol","title":"SBUMessageReceiptState.notUsed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notUsed"}],"abstract":[{"type":"text","text":"Not use receipt state"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/notUsed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageReceiptStateNotUsed"}],"url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate\/notused"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState":{"role":"symbol","title":"SBUMessageReceiptState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageReceiptState"}],"abstract":[{"type":"text","text":"This is an enumeration to message receipt state."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageReceiptState"}],"url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState/read":{"role":"symbol","title":"SBUMessageReceiptState.read","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"}],"abstract":[{"type":"text","text":"The message is read"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/read","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageReceiptStateRead"}],"url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate\/read"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState/none":{"role":"symbol","title":"SBUMessageReceiptState.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"The message is sent"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageReceiptStateNone"}],"url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate\/none"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState/SBUMessageReceiptStateReadReceipt":{"role":"symbol","title":"SBUMessageReceiptStateReadReceipt","fragments":[{"kind":"identifier","text":"SBUMessageReceiptStateReadReceipt"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/SBUMessageReceiptStateReadReceipt","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate\/sbumessagereceiptstatereadreceipt"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.sendbird.uikit\/SY"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState/SBUMessageReceiptStateDeliveryReceipt":{"role":"symbol","title":"SBUMessageReceiptStateDeliveryReceipt","fragments":[{"kind":"identifier","text":"SBUMessageReceiptStateDeliveryReceipt"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/SBUMessageReceiptStateDeliveryReceipt","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate\/sbumessagereceiptstatedeliveryreceipt"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate\/rawrepresentable-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageReceiptState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/sbumessagereceiptstate\/equatable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SBUMessageReceiptState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBUMessageReceiptState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBUMessageReceiptState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/SBUMessageReceiptStateDeliveryReceipt","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/SBUMessageReceiptStateReadReceipt","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/delivered","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/none","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/notUsed","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageReceiptState\/read"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageReceiptState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState~1delivered\/title","value":"SBUMessageReceiptStateDelivered"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState~1delivered\/fragments","value":[{"kind":"identifier","text":"SBUMessageReceiptStateDelivered"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState~1notUsed\/title","value":"SBUMessageReceiptStateNotUsed"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState~1notUsed\/fragments","value":[{"kind":"identifier","text":"SBUMessageReceiptStateNotUsed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState\/title","value":"SBUMessageReceiptState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState\/fragments","value":[{"kind":"identifier","text":"SBUMessageReceiptState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState~1read\/title","value":"SBUMessageReceiptStateRead"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState~1read\/fragments","value":[{"kind":"identifier","text":"SBUMessageReceiptStateRead"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState~1none\/title","value":"SBUMessageReceiptStateNone"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageReceiptState~1none\/fragments","value":[{"kind":"identifier","text":"SBUMessageReceiptStateNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}