{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelCell"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelcell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelcell"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding","doc:\/\/com.sendbird.uikit\/objc(pl)NSObject","doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","doc:\/\/com.sendbird.uikit\/s7CVarArgP","doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/s8SendableP","doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace","doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/contentStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/coverImage","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/coverImageSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/freezeState","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/infoIconSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/infoStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantCountLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantIcon","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantSpacer","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/separatorLine","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/theme","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/titleLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/titleSpacer","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/titleStackView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/awakeFromNib()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/configure(channel:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/layoutSubviews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupActions()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupLayouts()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupStyles()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupViews()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelCell"}],"title":"SBUOpenChannelCell","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelCell","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelCell"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/infoStackView":{"role":"symbol","title":"infoStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"abstract":[{"type":"text","text":"A vertical stack view to configure layouts of labels and icons that represent the channel information."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/infoStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"infoStackView"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/infostackview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/titleLabel":{"role":"symbol","title":"titleLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that represents the channel name."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/titleLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleLabel"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/titlelabel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/participantStackView":{"role":"symbol","title":"participantStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"abstract":[{"type":"text","text":"A horizontal stack view to configure layouts of the "},{"type":"codeVoice","code":"participantIcon"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"participantCount"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"participantStackView"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/participantstackview"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/setupViews()":{"role":"symbol","title":"setupViews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of views."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupViews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupViews"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/setupviews()"},"doc://com.sendbird.uikit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAccessibilityIdentification"},"doc://com.sendbird.uikit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/coverImageSize":{"role":"symbol","title":"coverImageSize","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"A value used in the size of "},{"type":"codeVoice","code":"coverImage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/coverImageSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coverImageSize"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/coverimagesize"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/participantIcon":{"role":"symbol","title":"participantIcon","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view that shows the participant icon."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantIcon","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"participantIcon"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/participanticon"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/titleSpacer":{"role":"symbol","title":"titleSpacer","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleSpacer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"A spacer used in "},{"type":"codeVoice","code":"titleStackView"},{"type":"text","text":" to provide spacing between "},{"type":"codeVoice","code":"titleLabel"},{"type":"text","text":" and "},{"type":"codeVoice","code":"lastUpdatedTimeLabel"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/titleSpacer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleSpacer"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/titlespacer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/initWithCoder:":{"role":"symbol","title":"initWithCoder:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/initWithCoder:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/initwithcoder:"},"doc://com.sendbird.uikit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.sendbird.uikit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.sendbird.uikit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"},"doc://com.sendbird.uikit/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIDynamicItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/contentStackView":{"role":"symbol","title":"contentStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"abstract":[{"type":"text","text":"A horizontal stack view to configure layouts of the entire view properties."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/contentStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"contentStackView"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/contentstackview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/infoIconSize":{"role":"symbol","title":"infoIconSize","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"infoIconSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"A value used in the size of icon image views."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/infoIconSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"infoIconSize"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/infoiconsize"},"doc://com.sendbird.uikit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UILargeContentViewerItem"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/configure(channel:)":{"role":"symbol","title":"configure(channel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This function configure a cell using "},{"type":"codeVoice","code":"OpenChannel"},{"type":"text","text":" information."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/configure(channel:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configureWithChannel:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/configure(channel:)"},"doc://com.sendbird.uikit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSObject"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/setupStyles()":{"role":"symbol","title":"setupStyles()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupStyles"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of styles."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupStyles()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupStyles"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/setupstyles()"},"doc://com.sendbird.uikit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItem"},"doc://com.sendbird.uikit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.uikit\/s7CVarArgP"},"doc://com.sendbird.uikit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/separatorLine":{"role":"symbol","title":"separatorLine","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"separatorLine"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"A view that is used as a separator between the channel cells."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/separatorLine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"separatorLine"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/separatorline"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUViewLifeCycle":{"role":"symbol","title":"SBUViewLifeCycle","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUViewLifeCycle"}],"abstract":[{"type":"text","text":"The protocol to manage the life cylce of some views. It defines setting views, styles, auto layouts and actions."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUViewLifeCycle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUViewLifeCycle"}],"url":"\/documentation\/sendbirduikit\/sbuviewlifecycle"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/freezeState":{"role":"symbol","title":"freezeState","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"freezeState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"abstract":[{"type":"text","text":"The image view that indicates the freezing state of the channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/freezeState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"freezeState"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/freezestate"},"doc://com.sendbird.uikit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)CALayerDelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/theme":{"role":"symbol","title":"theme","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelCellTheme","preciseIdentifier":"s:13SendbirdUIKit23SBUOpenChannelCellThemeC"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/theme","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/theme"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/coverImage":{"role":"symbol","title":"coverImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coverImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUCoverImageView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUCoverImageView"}],"abstract":[{"type":"text","text":"The image view that shows the channel cover image."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/coverImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coverImage"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/coverimage"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/participantSpacer":{"role":"symbol","title":"participantSpacer","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantSpacer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantSpacer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"participantSpacer"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/participantspacer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/initWithStyle:reuseIdentifier:":{"role":"symbol","title":"initWithStyle:reuseIdentifier:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/initWithStyle:reuseIdentifier:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/initwithstyle:reuseidentifier:"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell":{"role":"symbol","title":"SBUOpenChannelCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelCell"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell"},"doc://com.sendbird.uikit/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearance"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/participantCountLabel":{"role":"symbol","title":"participantCountLabel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantCountLabel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"abstract":[{"type":"text","text":"The label that represents the number of members in the channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantCountLabel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"participantCountLabel"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/participantcountlabel"},"doc://com.sendbird.uikit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UICoordinateSpace"},"doc://com.sendbird.uikit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment"},"doc://com.sendbird.uikit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/awakeFromNib()":{"role":"symbol","title":"awakeFromNib()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"awakeFromNib"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/awakeFromNib()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"awakeFromNib"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/awakefromnib()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/layoutsubviews()"},"doc://com.sendbird.uikit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment"},"doc://com.sendbird.uikit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.sendbird.uikit\/s8SendableP"},"doc://com.sendbird.uikit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIGestureRecognizerDelegate"},"doc://com.sendbird.uikit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusItemContainer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelCell":{"role":"symbol","title":"SBUBaseChannelCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelCell"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelcell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/setupLayouts()":{"role":"symbol","title":"setupLayouts()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupLayouts"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of autolayouts."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupLayouts()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupLayouts"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/setuplayouts()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/titleStackView":{"role":"symbol","title":"titleStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"abstract":[{"type":"text","text":"A horizontal stack view to configure layouts of the "},{"type":"codeVoice","code":"titleLabel"},{"type":"text","text":", "},{"type":"codeVoice","code":"lastUpdatedTimeLabel"},{"type":"text","text":" and icons."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/titleStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"titleStackView"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/titlestackview"},"doc://com.sendbird.uikit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding"},"doc://com.sendbird.uikit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/setupActions()":{"role":"symbol","title":"setupActions()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupActions"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function handles the initialization of actions."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupActions()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupActions"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/setupactions()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBUOpenChannelCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelCell"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBUOpenChannelCell"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/contentStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/coverImage","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/coverImageSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/freezeState","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/infoIconSize","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/infoStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantCountLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantIcon","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantSpacer","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantStackView","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/separatorLine","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/titleLabel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/titleSpacer","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/titleStackView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/awakeFromNib()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/configure(channel:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/initWithCoder:","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/initWithStyle:reuseIdentifier:","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/layoutSubviews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupActions()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupLayouts()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupStyles()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/setupViews()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelCell"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelCell","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelCell","text":"SBUBaseChannelCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1infoStackView\/title","value":"infoStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1infoStackView\/fragments","value":[{"kind":"identifier","text":"infoStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1titleLabel\/title","value":"titleLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1titleLabel\/fragments","value":[{"kind":"identifier","text":"titleLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1participantStackView\/title","value":"participantStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1participantStackView\/fragments","value":[{"kind":"identifier","text":"participantStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1setupViews()\/title","value":"setupViews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1setupViews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1coverImageSize\/title","value":"coverImageSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1coverImageSize\/fragments","value":[{"kind":"identifier","text":"coverImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1participantIcon\/title","value":"participantIcon"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1participantIcon\/fragments","value":[{"kind":"identifier","text":"participantIcon"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1titleSpacer\/title","value":"titleSpacer"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1titleSpacer\/fragments","value":[{"kind":"identifier","text":"titleSpacer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1contentStackView\/title","value":"contentStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1contentStackView\/fragments","value":[{"kind":"identifier","text":"contentStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1infoIconSize\/title","value":"infoIconSize"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1infoIconSize\/fragments","value":[{"kind":"identifier","text":"infoIconSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1configure(channel:)\/title","value":"configureWithChannel:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1configure(channel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configureWithChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1setupStyles()\/title","value":"setupStyles"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1setupStyles()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupStyles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1separatorLine\/title","value":"separatorLine"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1separatorLine\/fragments","value":[{"kind":"identifier","text":"separatorLine"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/title","value":"SBUViewLifeCycle"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUViewLifeCycle\/fragments","value":[{"kind":"identifier","text":"SBUViewLifeCycle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1freezeState\/title","value":"freezeState"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1freezeState\/fragments","value":[{"kind":"identifier","text":"freezeState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1coverImage\/title","value":"coverImage"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1coverImage\/fragments","value":[{"kind":"identifier","text":"coverImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1participantSpacer\/title","value":"participantSpacer"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1participantSpacer\/fragments","value":[{"kind":"identifier","text":"participantSpacer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell\/title","value":"SBUOpenChannelCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1participantCountLabel\/title","value":"participantCountLabel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1participantCountLabel\/fragments","value":[{"kind":"identifier","text":"participantCountLabel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1awakeFromNib()\/title","value":"awakeFromNib"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1awakeFromNib()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"awakeFromNib"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelCell\/title","value":"SBUBaseChannelCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelCell\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1setupLayouts()\/title","value":"setupLayouts"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1setupLayouts()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupLayouts"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1titleStackView\/title","value":"titleStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1titleStackView\/fragments","value":[{"kind":"identifier","text":"titleStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1setupActions()\/title","value":"setupActions"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1setupActions()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupActions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}