{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding","doc:\/\/com.sendbird.uikit\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.sendbird.uikit\/objc(pl)NSObject","doc:\/\/com.sendbird.uikit\/8PhotosUI30PHPickerViewControllerDelegateP","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUActionSheetDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsModuleHeaderDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsModuleListDataSource","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsModuleListDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULoadingIndicatorProtocol","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModuleHeaderDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModuleListDataSource","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModuleListDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewDelegate","doc:\/\/com.sendbird.uikit\/s7CVarArgP","doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/s8SendableP","doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIContentContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIImagePickerControllerDelegate","doc:\/\/com.sendbird.uikit\/objc(pl)UINavigationControllerDelegate","doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.sendbird.uikit\/objc(pl)UIStateRestoring","doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/init(channel:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/init(channelURL:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/channel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/headerComponent","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/listComponent","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/viewModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/baseChannelSettingsModule(_:channelForTableView:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/baseChannelSettingsModuleIsOperator(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/baseChannelSettingsViewModel(_:didChangeChannel:withContext:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/createViewModel(channel:channelURL:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/deleteChannel()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didSelectRowAt:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didTapLeftItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didTapRightItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didUpdateLeftItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didUpdateRightItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didUpdateTitleView:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModuleDidSelectDelete(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModuleDidSelectModerations(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModuleDidSelectParticipants(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsViewModel(_:didDeleteChannel:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/setupViews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/showDeleteChannelAlert()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/showModerationList()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/showParticipantsList()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/updateChannel(params:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}],"title":"SBUOpenChannelSettingsViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelSettingsViewController","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIStateRestoring"},"doc://com.sendbird.uikit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCommonDelegate":{"role":"symbol","title":"SBUCommonDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCommonDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCommonDelegate"}],"url":"\/documentation\/sendbirduikit\/sbucommondelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewModelDelegate":{"role":"symbol","title":"SBUOpenChannelSettingsViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/init(channelURL:)":{"role":"symbol","title":"init(channelURL:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"If you don’t have channel object and have channelURL, use this initialize function."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/init(channelURL:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithChannelURL:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/init(channelurl:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/openChannelSettingsModule(_:didTapRightItem:)":{"role":"symbol","title":"openChannelSettingsModule(_:didTapRightItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapRightItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"rightBarButton"},{"type":"text","text":" was selected."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didTapRightItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openChannelSettingsModule:didTapRightItem:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/openchannelsettingsmodule(_:didtaprightitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUActionSheetDelegate":{"role":"symbol","title":"SBUActionSheetDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUActionSheetDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUActionSheetDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUActionSheetDelegate"}],"url":"\/documentation\/sendbirduikit\/sbuactionsheetdelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/showParticipantsList()":{"role":"symbol","title":"showParticipantsList()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showParticipantsList"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"If you want to use a custom userListViewController, override it and implement it."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/showParticipantsList()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showParticipantsList"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/showparticipantslist()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/openChannelSettingsModule(_:didUpdateRightItem:)":{"role":"symbol","title":"openChannelSettingsModule(_:didUpdateRightItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateRightItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"rightBarButton"},{"type":"text","text":" was selected."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didUpdateRightItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openChannelSettingsModule:didUpdateRightItem:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/openchannelsettingsmodule(_:didupdaterightitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsModuleListDelegate":{"role":"symbol","title":"SBUOpenChannelSettingsModuleListDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsModuleListDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModuleListDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsModuleListDelegate"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsmodulelistdelegate"},"doc://com.sendbird.uikit/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSExtensionRequestHandling"},"doc://com.sendbird.uikit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.uikit\/s7CVarArgP"},"doc://com.sendbird.uikit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/createViewModel(channel:channelURL:)":{"role":"symbol","title":"createViewModel(channel:channelURL:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Creates the view model, loading initial messages from given starting point."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/createViewModel(channel:channelURL:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createViewModelWithChannel:channelURL:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/createviewmodel(channel:channelurl:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/baseChannelSettingsModule(_:channelForTableView:)":{"role":"symbol","title":"baseChannelSettingsModule(_:channelForTableView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUBaseChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit28SBUBaseChannelSettingsModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelForTableView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Ask the data source to return the channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/baseChannelSettingsModule(_:channelForTableView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseChannelSettingsModule:channelForTableView:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/basechannelsettingsmodule(_:channelfortableview:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewController":{"role":"symbol","title":"SBUBaseChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/openChannelSettingsModule(_:didUpdateLeftItem:)":{"role":"symbol","title":"openChannelSettingsModule(_:didUpdateLeftItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" value has been updated."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didUpdateLeftItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openChannelSettingsModule:didUpdateLeftItem:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/openchannelsettingsmodule(_:didupdateleftitem:)"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/listComponent":{"role":"symbol","title":"listComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC4ListC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/listComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"listComponent"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/listcomponent"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/deleteChannel()":{"deprecated":true,"role":"symbol","title":"deleteChannel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteChannel"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/deleteChannel()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteChannel"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/deletechannel()"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsModuleListDelegate":{"role":"symbol","title":"SBUBaseChannelSettingsModuleListDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsModuleListDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsModuleListDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsModuleListDelegate"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsmodulelistdelegate"},"doc://com.sendbird.uikit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/showDeleteChannelAlert()":{"role":"symbol","title":"showDeleteChannelAlert()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showDeleteChannelAlert"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Shows deletes channel confirm alert."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/showDeleteChannelAlert()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showDeleteChannelAlert"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/showdeletechannelalert()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/updateChannel(params:)":{"deprecated":true,"role":"symbol","title":"updateChannel(params:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateChannel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"params"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannelUpdateParams","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannelUpdateParams"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/updateChannel(params:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateChannelWithParams:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/updatechannel(params:)"},"doc://com.sendbird.uikit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.uikit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsModuleHeaderDelegate":{"role":"symbol","title":"SBUOpenChannelSettingsModuleHeaderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsModuleHeaderDelegate"}],"abstract":[{"type":"text","text":"Event methods for the views updates and performing actions from the header component in open channel settings module."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModuleHeaderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsModuleHeaderDelegate"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsmoduleheaderdelegate"},"doc://com.sendbird.uikit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController":{"role":"symbol","title":"SBUOpenChannelSettingsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/init(channel:)":{"role":"symbol","title":"init(channel:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"If you have channel object, use this initialize function."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/init(channel:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithChannel:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/init(channel:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/setupViews()":{"role":"symbol","title":"setupViews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function setups views."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/setupViews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupViews"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/setupviews()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/baseChannelSettingsModuleIsOperator(_:)":{"role":"symbol","title":"baseChannelSettingsModuleIsOperator(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelSettingsModuleIsOperator"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUBaseChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit28SBUBaseChannelSettingsModuleC4ListC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Ask the data source to return the operator status"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/baseChannelSettingsModuleIsOperator(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseChannelSettingsModuleIsOperator:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/basechannelsettingsmoduleisoperator(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/openChannelSettingsModuleDidSelectDelete(_:)":{"role":"symbol","title":"openChannelSettingsModuleDidSelectDelete(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelSettingsModuleDidSelectDelete"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC4ListC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the delete item cell was selected in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModuleDidSelectDelete(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openChannelSettingsModuleDidSelectDelete:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/openchannelsettingsmoduledidselectdelete(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsViewModelDelegate":{"role":"symbol","title":"SBUBaseChannelSettingsViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/headerComponent":{"role":"symbol","title":"headerComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC6HeaderC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/headerComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"headerComponent"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/headercomponent"},"doc://com.sendbird.uikit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/openChannelSettingsViewModel(_:didDeleteChannel:)":{"role":"symbol","title":"openChannelSettingsViewModel(_:didDeleteChannel:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelSettingsViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelSettingsViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDeleteChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the current user delete the channel."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsViewModel(_:didDeleteChannel:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openChannelSettingsViewModel:didDeleteChannel:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/openchannelsettingsviewmodel(_:diddeletechannel:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/viewModel":{"role":"symbol","title":"viewModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelSettingsViewModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/viewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewModel"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/viewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/openChannelSettingsModuleDidSelectModerations(_:)":{"role":"symbol","title":"openChannelSettingsModuleDidSelectModerations(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelSettingsModuleDidSelectModerations"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC4ListC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the moderations item cell was selected in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModuleDidSelectModerations(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openChannelSettingsModuleDidSelectModerations:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/openchannelsettingsmoduledidselectmoderations(_:)"},"doc://com.sendbird.uikit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.sendbird.uikit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSObject"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUSelectablePhotoViewDelegate":{"role":"symbol","title":"SBUSelectablePhotoViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUSelectablePhotoViewDelegate"}],"abstract":[{"type":"text","text":"Event methods for "},{"type":"codeVoice","code":"SBUSelectablePhotoViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUSelectablePhotoViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUSelectablePhotoViewDelegate"}],"url":"\/documentation\/sendbirduikit\/sbuselectablephotoviewdelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsModuleListDataSource":{"role":"symbol","title":"SBUOpenChannelSettingsModuleListDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsModuleListDataSource"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsModuleListDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelSettingsModuleListDataSource"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsmodulelistdatasource"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/openChannelSettingsModule(_:didTapLeftItem:)":{"role":"symbol","title":"openChannelSettingsModule(_:didTapLeftItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" was selected."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didTapLeftItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openChannelSettingsModule:didTapLeftItem:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/openchannelsettingsmodule(_:didtapleftitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBULoadingIndicatorProtocol":{"role":"symbol","title":"SBULoadingIndicatorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBULoadingIndicatorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULoadingIndicatorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBULoadingIndicatorProtocol"}],"url":"\/documentation\/sendbirduikit\/sbuloadingindicatorprotocol"},"doc://com.sendbird.uikit/8PhotosUI30PHPickerViewControllerDelegateP":{"type":"unresolvable","title":"PhotosUI.PHPickerViewControllerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/8PhotosUI30PHPickerViewControllerDelegateP"},"doc://com.sendbird.uikit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.sendbird.uikit\/s8SendableP"},"doc://com.sendbird.uikit/objc(pl)UIImagePickerControllerDelegate":{"type":"unresolvable","title":"UIKit.UIImagePickerControllerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIImagePickerControllerDelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsModuleHeaderDelegate":{"role":"symbol","title":"SBUBaseChannelSettingsModuleHeaderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsModuleHeaderDelegate"}],"abstract":[{"type":"text","text":"Event methods for the views updates and performing actions from the header component in channel settings module."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsModuleHeaderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsModuleHeaderDelegate"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsmoduleheaderdelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/openChannelSettingsModule(_:didSelectRowAt:)":{"role":"symbol","title":"openChannelSettingsModule(_:didSelectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the setting item cell was selected in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didSelectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openChannelSettingsModule:didSelectRowAt:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/openchannelsettingsmodule(_:didselectrowat:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/openChannelSettingsModule(_:didUpdateTitleView:)":{"role":"symbol","title":"openChannelSettingsModule(_:didUpdateTitleView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelSettingsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateTitleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"titleView"},{"type":"text","text":" value has been updated."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didUpdateTitleView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openChannelSettingsModule:didUpdateTitleView:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/openchannelsettingsmodule(_:didupdatetitleview:)"},"doc://com.sendbird.uikit/objc(pl)UINavigationControllerDelegate":{"type":"unresolvable","title":"UIKit.UINavigationControllerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UINavigationControllerDelegate"},"doc://com.sendbird.uikit/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIContentContainer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/channel":{"role":"symbol","title":"channel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"OpenChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDOpenChannel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/channel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channel"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/channel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCommonViewModelDelegate":{"role":"symbol","title":"SBUCommonViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCommonViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCommonViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbucommonviewmodeldelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseChannelSettingsModuleListDataSource":{"role":"symbol","title":"SBUBaseChannelSettingsModuleListDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseChannelSettingsModuleListDataSource"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsModuleListDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseChannelSettingsModuleListDataSource"}],"url":"\/documentation\/sendbirduikit\/sbubasechannelsettingsmodulelistdatasource"},"doc://com.sendbird.uikit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/baseChannelSettingsViewModel(_:didChangeChannel:withContext:)":{"role":"symbol","title":"baseChannelSettingsViewModel(_:didChangeChannel:withContext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseChannelSettingsViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseChannelSettingsViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didChangeChannel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"withContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDMessageContext"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/baseChannelSettingsViewModel(_:didChangeChannel:withContext:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseChannelSettingsViewModel:didChangeChannel:withContext:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/basechannelsettingsviewmodel(_:didchangechannel:withcontext:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/showModerationList()":{"role":"symbol","title":"showModerationList()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showModerationList"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"If you want to use a custom moderationsViewController, override it and implement it."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/showModerationList()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showModerationList"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/showmoderationlist()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelSettingsViewController/openChannelSettingsModuleDidSelectParticipants(_:)":{"role":"symbol","title":"openChannelSettingsModuleDidSelectParticipants(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openChannelSettingsModuleDidSelectParticipants"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUOpenChannelSettingsModule","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit28SBUOpenChannelSettingsModuleC4ListC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the participants item cell was selected in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModuleDidSelectParticipants(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openChannelSettingsModuleDidSelectParticipants:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelsettingsviewcontroller\/openchannelsettingsmoduledidselectparticipants(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBUOpenChannelSettingsViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/channel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/headerComponent","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/listComponent","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/viewModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/baseChannelSettingsModule(_:channelForTableView:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/baseChannelSettingsModuleIsOperator(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/baseChannelSettingsViewModel(_:didChangeChannel:withContext:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/createViewModel(channel:channelURL:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/deleteChannel()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/init(channel:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/init(channelURL:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didSelectRowAt:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didTapLeftItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didTapRightItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didUpdateLeftItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didUpdateRightItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModule(_:didUpdateTitleView:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModuleDidSelectDelete(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModuleDidSelectModerations(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsModuleDidSelectParticipants(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/openChannelSettingsViewModel(_:didDeleteChannel:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/setupViews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/showDeleteChannelAlert()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/showModerationList()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/showParticipantsList()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelSettingsViewController\/updateChannel(params:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseChannelSettingsViewController","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseChannelSettingsViewController","text":"SBUBaseChannelSettingsViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1init(channelURL:)\/title","value":"initWithChannelURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1init(channelURL:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannelURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didTapRightItem:)\/title","value":"openChannelSettingsModule:didTapRightItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didTapRightItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openChannelSettingsModule:didTapRightItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1showParticipantsList()\/title","value":"showParticipantsList"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1showParticipantsList()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showParticipantsList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didUpdateRightItem:)\/title","value":"openChannelSettingsModule:didUpdateRightItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didUpdateRightItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openChannelSettingsModule:didUpdateRightItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1createViewModel(channel:channelURL:)\/title","value":"createViewModelWithChannel:channelURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1createViewModel(channel:channelURL:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createViewModelWithChannel:channelURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1baseChannelSettingsModule(_:channelForTableView:)\/title","value":"baseChannelSettingsModule:channelForTableView:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1baseChannelSettingsModule(_:channelForTableView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelSettingsModule:channelForTableView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/title","value":"SBUBaseChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseChannelSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didUpdateLeftItem:)\/title","value":"openChannelSettingsModule:didUpdateLeftItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didUpdateLeftItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openChannelSettingsModule:didUpdateLeftItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1listComponent\/title","value":"listComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1listComponent\/fragments","value":[{"kind":"identifier","text":"listComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1deleteChannel()\/title","value":"deleteChannel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1deleteChannel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteChannel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1showDeleteChannelAlert()\/title","value":"showDeleteChannelAlert"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1showDeleteChannelAlert()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showDeleteChannelAlert"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1updateChannel(params:)\/title","value":"updateChannelWithParams:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1updateChannel(params:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateChannelWithParams:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController\/title","value":"SBUOpenChannelSettingsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelSettingsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1init(channel:)\/title","value":"initWithChannel:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1init(channel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1setupViews()\/title","value":"setupViews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1setupViews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1baseChannelSettingsModuleIsOperator(_:)\/title","value":"baseChannelSettingsModuleIsOperator:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1baseChannelSettingsModuleIsOperator(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelSettingsModuleIsOperator:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModuleDidSelectDelete(_:)\/title","value":"openChannelSettingsModuleDidSelectDelete:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModuleDidSelectDelete(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openChannelSettingsModuleDidSelectDelete:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1headerComponent\/title","value":"headerComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1headerComponent\/fragments","value":[{"kind":"identifier","text":"headerComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsViewModel(_:didDeleteChannel:)\/title","value":"openChannelSettingsViewModel:didDeleteChannel:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsViewModel(_:didDeleteChannel:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openChannelSettingsViewModel:didDeleteChannel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1viewModel\/title","value":"viewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1viewModel\/fragments","value":[{"kind":"identifier","text":"viewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModuleDidSelectModerations(_:)\/title","value":"openChannelSettingsModuleDidSelectModerations:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModuleDidSelectModerations(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openChannelSettingsModuleDidSelectModerations:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didTapLeftItem:)\/title","value":"openChannelSettingsModule:didTapLeftItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didTapLeftItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openChannelSettingsModule:didTapLeftItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didSelectRowAt:)\/title","value":"openChannelSettingsModule:didSelectRowAt:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openChannelSettingsModule:didSelectRowAt:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didUpdateTitleView:)\/title","value":"openChannelSettingsModule:didUpdateTitleView:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModule(_:didUpdateTitleView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openChannelSettingsModule:didUpdateTitleView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1channel\/title","value":"channel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1channel\/fragments","value":[{"kind":"identifier","text":"channel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1baseChannelSettingsViewModel(_:didChangeChannel:withContext:)\/title","value":"baseChannelSettingsViewModel:didChangeChannel:withContext:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1baseChannelSettingsViewModel(_:didChangeChannel:withContext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseChannelSettingsViewModel:didChangeChannel:withContext:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1showModerationList()\/title","value":"showModerationList"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1showModerationList()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showModerationList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModuleDidSelectParticipants(_:)\/title","value":"openChannelSettingsModuleDidSelectParticipants:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelSettingsViewController~1openChannelSettingsModuleDidSelectParticipants(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"openChannelSettingsModuleDidSelectParticipants:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}