{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUQuotedMessageViewDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuquotedmessageviewdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuquotedmessageviewdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule\/List"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUQuotedMessageViewDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUQuotedMessageViewDelegate\/didTapQuotedMessageView(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUQuotedMessageViewDelegate"}],"title":"SBUQuotedMessageViewDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@SendbirdUIKit@objc(pl)SBUQuotedMessageViewDelegate","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUQuotedMessageViewDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelModule/List":{"role":"symbol","title":"SBUGroupChannelModule.List","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"List"}],"abstract":[{"type":"text","text":"A module component that represent the list of "},{"type":"codeVoice","code":"SBUGroupChannelModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelModule\/List","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"List"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannelmodule\/list"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUQuotedMessageViewDelegate":{"role":"symbol","title":"SBUQuotedMessageViewDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUQuotedMessageViewDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUQuotedMessageViewDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUQuotedMessageViewDelegate"}],"url":"\/documentation\/sendbirduikit\/sbuquotedmessageviewdelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUQuotedMessageViewDelegate/didTapQuotedMessageView(_:)":{"navigatorTitle":[{"kind":"identifier","text":"didTapQuotedMessageView:"}],"role":"symbol","title":"didTapQuotedMessageView(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapQuotedMessageView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUQuotedBaseMessageView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUQuotedBaseMessageView"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"SBUQuotedBaseMessageView"},{"type":"text","text":" was tapped."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUQuotedMessageViewDelegate\/didTapQuotedMessageView(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sendbirduikit\/sbuquotedmessageviewdelegate\/didtapquotedmessageview(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SBUQuotedMessageViewDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBUQuotedMessageViewDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBUQuotedMessageViewDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUQuotedMessageViewDelegate\/didTapQuotedMessageView(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUQuotedMessageViewDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUQuotedMessageViewDelegate\/title","value":"SBUQuotedMessageViewDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUQuotedMessageViewDelegate\/fragments","value":[{"kind":"identifier","text":"SBUQuotedMessageViewDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUQuotedMessageViewDelegate~1didTapQuotedMessageView(_:)\/title","value":"didTapQuotedMessageView:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUQuotedMessageViewDelegate~1didTapQuotedMessageView(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapQuotedMessageView:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}