{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding","doc:\/\/com.sendbird.uikit\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.sendbird.uikit\/objc(pl)NSObject","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserModuleHeaderDataSource","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserModuleHeaderDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserModuleListDataSource","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserModuleListDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewModelDataSource","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULoadingIndicatorProtocol","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModuleHeaderDataSource","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModuleHeaderDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModuleListDataSource","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModuleListDelegate","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewModelDataSource","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewModelDelegate","doc:\/\/com.sendbird.uikit\/s7CVarArgP","doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP","doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP","doc:\/\/com.sendbird.uikit\/SQ","doc:\/\/com.sendbird.uikit\/SH","doc:\/\/com.sendbird.uikit\/s8SendableP","doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIContentContainer","doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UINavigationControllerDelegate","doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.sendbird.uikit\/objc(pl)UIStateRestoring","doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment","doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/init(channel:users:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/init(channelURL:channelType:users:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/headerComponent","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/listComponent","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/baseSelectedUserViewModel(_:didUpdateSelectedUsers:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/createViewModel(channel:channelURL:channelType:users:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didDetectPreloadingPosition:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didSelectRowAt:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didTapLeftItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didTapRightItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didUpdateLeftItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didUpdateRightItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didUpdateTitleView:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModuleDidSelectRetry(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorViewModel(_:didRegisterOperatorIds:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerSelectedUsers()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/setupViews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewDidLoad()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewWillAppear(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewWillDisappear(_:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"title":"SBURegisterOperatorViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewController","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserViewModelDelegate":{"role":"symbol","title":"SBUBaseSelectUserViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectuserviewmodeldelegate"},"doc://com.sendbird.uikit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIResponderStandardEditActions"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorModuleDidSelectRetry(_:)":{"role":"symbol","title":"registerOperatorModuleDidSelectRetry(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModuleDidSelectRetry"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC4ListC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the retry button was selected from the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModuleDidSelectRetry(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorModuleDidSelectRetry:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormoduledidselectretry(_:)"},"doc://com.sendbird.uikit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIFocusEnvironment"},"doc://com.sendbird.uikit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIUserActivityRestoring"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserModuleListDelegate":{"role":"symbol","title":"SBUBaseSelectUserModuleListDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserModuleListDelegate"}],"abstract":[{"type":"text","text":"Event methods for the views updates and performing actions from the list component."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserModuleListDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserModuleListDelegate"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectusermodulelistdelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorModuleListDataSource":{"role":"symbol","title":"SBURegisterOperatorModuleListDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorModuleListDataSource"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModuleListDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorModuleListDataSource"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatormodulelistdatasource"},"doc://com.sendbird.uikit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIAppearanceContainer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/setupViews()":{"role":"symbol","title":"setupViews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setupViews"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function setups views."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/setupViews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setupViews"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/setupviews()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorModule(_:didDetectPreloadingPosition:)":{"role":"symbol","title":"registerOperatorModule(_:didDetectPreloadingPosition:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didDetectPreloadingPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the tableView detected preloading position in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didDetectPreloadingPosition:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorModule:didDetectPreloadingPosition:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormodule(_:diddetectpreloadingposition:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCommonViewModelDelegate":{"role":"symbol","title":"SBUCommonViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCommonViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCommonViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sbucommonviewmodeldelegate"},"doc://com.sendbird.uikit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.sendbird.uikit\/SH"},"doc://com.sendbird.uikit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s28CustomDebugStringConvertibleP"},"doc://com.sendbird.uikit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UITraitEnvironment"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/viewWillDisappear(_:)":{"role":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewWillDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/viewwilldisappear(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserViewModelDataSource":{"role":"symbol","title":"SBUBaseSelectUserViewModelDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserViewModelDataSource"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewModelDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserViewModelDataSource"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectuserviewmodeldatasource"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorModule(_:didTapRightItem:)":{"role":"symbol","title":"registerOperatorModule(_:didTapRightItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapRightItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"rightBarButton"},{"type":"text","text":" was selected."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didTapRightItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorModule:didTapRightItem:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormodule(_:didtaprightitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewModelDataSource":{"role":"symbol","title":"SBURegisterOperatorViewModelDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewModelDataSource"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewModelDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewModelDataSource"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewmodeldatasource"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/createViewModel(channel:channelURL:channelType:users:)":{"role":"symbol","title":"createViewModel(channel:channelURL:channelType:users:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createViewModel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"users"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Creates view model."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/createViewModel(channel:channelURL:channelType:users:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createViewModelWithChannel:channelURL:channelType:users:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/createviewmodel(channel:channelurl:channeltype:users:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/headerComponent":{"role":"symbol","title":"headerComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC6HeaderC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/headerComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"headerComponent"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/headercomponent"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/baseSelectedUserViewModel(_:didUpdateSelectedUsers:)":{"role":"symbol","title":"baseSelectedUserViewModel(_:didUpdateSelectedUsers:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseSelectedUserViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUBaseSelectUserViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseSelectUserViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateSelectedUsers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/baseSelectedUserViewModel(_:didUpdateSelectedUsers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"baseSelectedUserViewModel:didUpdateSelectedUsers:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/baseselecteduserviewmodel(_:didupdateselectedusers:)"},"doc://com.sendbird.uikit/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIStateRestoring"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUCommonDelegate":{"role":"symbol","title":"SBUCommonDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUCommonDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUCommonDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUCommonDelegate"}],"url":"\/documentation\/sendbirduikit\/sbucommondelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorModule(_:didSelectRowAt:)":{"role":"symbol","title":"registerOperatorModule(_:didSelectRowAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC4ListC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when the member cell was selected in the "},{"type":"codeVoice","code":"listComponent"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didSelectRowAt:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorModule:didSelectRowAt:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormodule(_:didselectrowat:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorViewModel(_:didRegisterOperatorIds:)":{"role":"symbol","title":"registerOperatorViewModel(_:didRegisterOperatorIds:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorViewModel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewModel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didRegisterOperatorIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Called when it has registered operators with their IDs."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorViewModel(_:didRegisterOperatorIds:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorViewModel:didRegisterOperatorIds:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatorviewmodel(_:didregisteroperatorids:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/viewwillappear(_:)"},"doc://com.sendbird.uikit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.sendbird.uikit\/s7CVarArgP"},"doc://com.sendbird.uikit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.sendbird.uikit/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSExtensionRequestHandling"},"doc://com.sendbird.uikit/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSCoding"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorModule(_:didUpdateLeftItem:)":{"role":"symbol","title":"registerOperatorModule(_:didUpdateLeftItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" value has been updated."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didUpdateLeftItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorModule:didUpdateLeftItem:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormodule(_:didupdateleftitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorModuleHeaderDelegate":{"role":"symbol","title":"SBURegisterOperatorModuleHeaderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorModuleHeaderDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModuleHeaderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorModuleHeaderDelegate"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatormoduleheaderdelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserModuleListDataSource":{"role":"symbol","title":"SBUBaseSelectUserModuleListDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserModuleListDataSource"}],"abstract":[{"type":"text","text":"Methods to get data source for the list component."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserModuleListDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserModuleListDataSource"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectusermodulelistdatasource"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorModuleHeaderDataSource":{"role":"symbol","title":"SBURegisterOperatorModuleHeaderDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorModuleHeaderDataSource"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModuleHeaderDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorModuleHeaderDataSource"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatormoduleheaderdatasource"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserModuleHeaderDelegate":{"role":"symbol","title":"SBUBaseSelectUserModuleHeaderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserModuleHeaderDelegate"}],"abstract":[{"type":"text","text":"Event methods for the views updates and performing actions from the header component in user selection module."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserModuleHeaderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserModuleHeaderDelegate"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectusermoduleheaderdelegate"},"doc://com.sendbird.uikit/objc(pl)UINavigationControllerDelegate":{"type":"unresolvable","title":"UIKit.UINavigationControllerDelegate","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UINavigationControllerDelegate"},"doc://com.sendbird.uikit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.sendbird.uikit\/SQ"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorModule(_:didUpdateRightItem:)":{"role":"symbol","title":"registerOperatorModule(_:didUpdateRightItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateRightItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"rightBarButton"},{"type":"text","text":" was selected."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didUpdateRightItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorModule:didUpdateRightItem:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormodule(_:didupdaterightitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController":{"role":"symbol","title":"SBURegisterOperatorViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller"},"doc://com.sendbird.uikit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.sendbird.uikit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)NSObject"},"doc://com.sendbird.uikit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.sendbird.uikit\/s23CustomStringConvertibleP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/viewModel":{"role":"symbol","title":"viewModel","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewModel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBURegisterOperatorViewModel","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBURegisterOperatorViewModel"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewModel"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/viewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/init(channelURL:channelType:users:)":{"role":"symbol","title":"init(channelURL:channelType:users:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channelURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"channelType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelType","preciseIdentifier":"c:@M@SendbirdChatSDK@E@SBDChannelType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"users"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"If you have channelURL and users objects, use this initialize function."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/init(channelURL:channelType:users:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithChannelURL:channelType:users:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/init(channelurl:channeltype:users:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewModelDelegate":{"role":"symbol","title":"SBURegisterOperatorViewModelDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewModelDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewModelDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorViewModelDelegate"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewmodeldelegate"},"doc://com.sendbird.uikit/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.sendbird.uikit\/objc(pl)UIContentContainer"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBULoadingIndicatorProtocol":{"role":"symbol","title":"SBULoadingIndicatorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBULoadingIndicatorProtocol"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBULoadingIndicatorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBULoadingIndicatorProtocol"}],"url":"\/documentation\/sendbirduikit\/sbuloadingindicatorprotocol"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/viewdidload()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserViewController":{"role":"symbol","title":"SBUBaseSelectUserViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserViewController"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectuserviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorModuleListDelegate":{"role":"symbol","title":"SBURegisterOperatorModuleListDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorModuleListDelegate"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorModuleListDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBURegisterOperatorModuleListDelegate"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatormodulelistdelegate"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/init(channel:users:)":{"role":"symbol","title":"init(channel:users:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"channel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDBaseChannel"},{"kind":"text","text":", "},{"kind":"externalParam","text":"users"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SBUUser","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUUser"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"If you have channel and users objects, use this initialize function."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/init(channel:users:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithChannel:users:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/init(channel:users:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorModule(_:didTapLeftItem:)":{"role":"symbol","title":"registerOperatorModule(_:didTapLeftItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" was selected."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didTapLeftItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorModule:didTapLeftItem:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormodule(_:didtapleftitem:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/listComponent":{"role":"symbol","title":"listComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"List","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC4ListC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/listComponent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"listComponent"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/listcomponent"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUBaseSelectUserModuleHeaderDataSource":{"role":"symbol","title":"SBUBaseSelectUserModuleHeaderDataSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUBaseSelectUserModuleHeaderDataSource"}],"abstract":[{"type":"text","text":"Methods to get data source for header component in a user selection."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserModuleHeaderDataSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUBaseSelectUserModuleHeaderDataSource"}],"url":"\/documentation\/sendbirduikit\/sbubaseselectusermoduleheaderdatasource"},"doc://com.sendbird.uikit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.sendbird.uikit\/s8SendableP"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerOperatorModule(_:didUpdateTitleView:)":{"role":"symbol","title":"registerOperatorModule(_:didUpdateTitleView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerOperatorModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBURegisterOperatorModule","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit25SBURegisterOperatorModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateTitleView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"titleView"},{"type":"text","text":" value has been updated."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didUpdateTitleView:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerOperatorModule:didUpdateTitleView:"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registeroperatormodule(_:didupdatetitleview:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBURegisterOperatorViewController/registerSelectedUsers()":{"role":"symbol","title":"registerSelectedUsers()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerSelectedUsers"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This function calls "},{"type":"codeVoice","code":"registerAsOperators"},{"type":"text","text":" function."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerSelectedUsers()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerSelectedUsers"}],"url":"\/documentation\/sendbirduikit\/sburegisteroperatorviewcontroller\/registerselectedusers()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SBURegisterOperatorViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/headerComponent","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/listComponent","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewModel"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/baseSelectedUserViewModel(_:didUpdateSelectedUsers:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/createViewModel(channel:channelURL:channelType:users:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/init(channel:users:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/init(channelURL:channelType:users:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didDetectPreloadingPosition:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didSelectRowAt:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didTapLeftItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didTapRightItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didUpdateLeftItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didUpdateRightItem:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModule(_:didUpdateTitleView:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorModuleDidSelectRetry(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerOperatorViewModel(_:didRegisterOperatorIds:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/registerSelectedUsers()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/setupViews()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewDidLoad()","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewWillAppear(_:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBURegisterOperatorViewController\/viewWillDisappear(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBURegisterOperatorViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUBaseSelectUserViewController","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUBaseSelectUserViewController","text":"SBUBaseSelectUserViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModuleDidSelectRetry(_:)\/title","value":"registerOperatorModuleDidSelectRetry:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModuleDidSelectRetry(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorModuleDidSelectRetry:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1setupViews()\/title","value":"setupViews"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1setupViews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setupViews"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didDetectPreloadingPosition:)\/title","value":"registerOperatorModule:didDetectPreloadingPosition:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didDetectPreloadingPosition:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorModule:didDetectPreloadingPosition:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didTapRightItem:)\/title","value":"registerOperatorModule:didTapRightItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didTapRightItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorModule:didTapRightItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1createViewModel(channel:channelURL:channelType:users:)\/title","value":"createViewModelWithChannel:channelURL:channelType:users:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1createViewModel(channel:channelURL:channelType:users:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createViewModelWithChannel:channelURL:channelType:users:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1headerComponent\/title","value":"headerComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1headerComponent\/fragments","value":[{"kind":"identifier","text":"headerComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1baseSelectedUserViewModel(_:didUpdateSelectedUsers:)\/title","value":"baseSelectedUserViewModel:didUpdateSelectedUsers:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1baseSelectedUserViewModel(_:didUpdateSelectedUsers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"baseSelectedUserViewModel:didUpdateSelectedUsers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didSelectRowAt:)\/title","value":"registerOperatorModule:didSelectRowAt:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorModule:didSelectRowAt:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorViewModel(_:didRegisterOperatorIds:)\/title","value":"registerOperatorViewModel:didRegisterOperatorIds:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorViewModel(_:didRegisterOperatorIds:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorViewModel:didRegisterOperatorIds:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didUpdateLeftItem:)\/title","value":"registerOperatorModule:didUpdateLeftItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didUpdateLeftItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorModule:didUpdateLeftItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didUpdateRightItem:)\/title","value":"registerOperatorModule:didUpdateRightItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didUpdateRightItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorModule:didUpdateRightItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/title","value":"SBURegisterOperatorViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController\/fragments","value":[{"kind":"identifier","text":"SBURegisterOperatorViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1viewModel\/title","value":"viewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1viewModel\/fragments","value":[{"kind":"identifier","text":"viewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1init(channelURL:channelType:users:)\/title","value":"initWithChannelURL:channelType:users:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1init(channelURL:channelType:users:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannelURL:channelType:users:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseSelectUserViewController\/title","value":"SBUBaseSelectUserViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUBaseSelectUserViewController\/fragments","value":[{"kind":"identifier","text":"SBUBaseSelectUserViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1init(channel:users:)\/title","value":"initWithChannel:users:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1init(channel:users:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChannel:users:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didTapLeftItem:)\/title","value":"registerOperatorModule:didTapLeftItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didTapLeftItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorModule:didTapLeftItem:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1listComponent\/title","value":"listComponent"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1listComponent\/fragments","value":[{"kind":"identifier","text":"listComponent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didUpdateTitleView:)\/title","value":"registerOperatorModule:didUpdateTitleView:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerOperatorModule(_:didUpdateTitleView:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerOperatorModule:didUpdateTitleView:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerSelectedUsers()\/title","value":"registerSelectedUsers"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBURegisterOperatorViewController~1registerSelectedUsers()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerSelectedUsers"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}