{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannelURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/channelcollection(_:context:deletedchannelurls:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/channelcollection(_:context:deletedchannelurls:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:deletedChannelURLs:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"GroupChannelCollectionDelegate.channelCollection(_:context:deletedChannelURLs:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannelURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"title":"channelCollection(_:context:deletedChannelURLs:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@SendbirdUIKit@objc(cs)SBUGroupChannelListViewModel(im)channelCollection:context:deletedChannelURLs:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/GroupChannelCollectionDelegate-Implementations"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModel/channelCollection(_:context:deletedChannelURLs:)":{"role":"symbol","title":"channelCollection(_:context:deletedChannelURLs:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannelURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:deletedChannelURLs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/channelcollection(_:context:deletedchannelurls:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModel/GroupChannelCollectionDelegate-Implementations":{"role":"collectionGroup","title":"GroupChannelCollectionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/GroupChannelCollectionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/groupchannelcollectiondelegate-implementations"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModel":{"role":"symbol","title":"SBUGroupChannelListViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewModel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"channelCollection:context:deletedChannelURLs:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"channelCollection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDGroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"collection"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"deletedChannelURLs:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"deletedChannelURLs"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel~1channelCollection(_:context:deletedChannelURLs:)\/title","value":"channelCollection:context:deletedChannelURLs:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel~1channelCollection(_:context:deletedChannelURLs:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel\/title","value":"SBUGroupChannelListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}