{"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/connectiondelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/connectiondelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/ConnectionDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/didSucceedReconnection()"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SendbirdUIKit"}],"role":"collectionGroup","title":"ConnectionDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModel":{"role":"symbol","title":"SBUGroupChannelListViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewModel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModel/didSucceedReconnection()":{"role":"symbol","title":"didSucceedReconnection()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didSucceedReconnection"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/didSucceedReconnection()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didSucceedReconnection"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/didsucceedreconnection()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/didSucceedReconnection()"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel\/title","value":"SBUGroupChannelListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel~1didSucceedReconnection()\/title","value":"didSucceedReconnection"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel~1didSucceedReconnection()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSucceedReconnection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}