{"variants":[{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/groupchannelcollectiondelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/groupchannelcollectiondelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/GroupChannelCollectionDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:addedChannels:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:deletedChannelURLs:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:updatedChannels:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"SendbirdUIKit"}],"role":"collectionGroup","title":"GroupChannelCollectionDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModel/channelCollection(_:context:deletedChannelURLs:)":{"role":"symbol","title":"channelCollection(_:context:deletedChannelURLs:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deletedChannelURLs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:deletedChannelURLs:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/channelcollection(_:context:deletedchannelurls:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModel/channelCollection(_:context:addedChannels:)":{"role":"symbol","title":"channelCollection(_:context:addedChannels:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"addedChannels"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:addedChannels:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelCollection:context:addedChannels:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/channelcollection(_:context:addedchannels:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModel":{"role":"symbol","title":"SBUGroupChannelListViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUGroupChannelListViewModel"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUGroupChannelListViewModel"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUGroupChannelListViewModel/channelCollection(_:context:updatedChannels:)":{"role":"symbol","title":"channelCollection(_:context:updatedChannels:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"channelCollection"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"GroupChannelCollection","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannelCollection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChannelContext","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDChannelContext"},{"kind":"text","text":", "},{"kind":"externalParam","text":"updatedChannels"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"GroupChannel","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDGroupChannel"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:updatedChannels:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"channelCollection:context:updatedChannels:"}],"url":"\/documentation\/sendbirduikit\/sbugroupchannellistviewmodel\/channelcollection(_:context:updatedchannels:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:addedChannels:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:deletedChannelURLs:)","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUGroupChannelListViewModel\/channelCollection(_:context:updatedChannels:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel~1channelCollection(_:context:deletedChannelURLs:)\/title","value":"channelCollection:context:deletedChannelURLs:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel~1channelCollection(_:context:deletedChannelURLs:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelCollection:context:deletedChannelURLs:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel~1channelCollection(_:context:addedChannels:)\/title","value":"channelCollection:context:addedChannels:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel~1channelCollection(_:context:addedChannels:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelCollection:context:addedChannels:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel\/title","value":"SBUGroupChannelListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel\/fragments","value":[{"kind":"identifier","text":"SBUGroupChannelListViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel~1channelCollection(_:context:updatedChannels:)\/title","value":"channelCollection:context:updatedChannels:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUGroupChannelListViewModel~1channelCollection(_:context:updatedChannels:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"channelCollection:context:updatedChannels:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}