{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbumessageinputmode\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbumessageinputmode\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/none","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The default mode"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"SBUMessageInputMode.none","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@SendbirdUIKit@E@SBUMessageInputMode@SBUMessageInputModeNone","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SBUMessageInputModeNone"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputMode/none":{"role":"symbol","title":"SBUMessageInputMode.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"The default mode"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageInputModeNone"}],"url":"\/documentation\/sendbirduikit\/sbumessageinputmode\/none"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUMessageInputMode":{"role":"symbol","title":"SBUMessageInputMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUMessageInputMode"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUMessageInputMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUMessageInputMode"}],"url":"\/documentation\/sendbirduikit\/sbumessageinputmode"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SBUMessageInputModeNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SBUMessageInputModeNone"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SBUMessageInputModeNone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode~1none\/title","value":"SBUMessageInputModeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode~1none\/fragments","value":[{"kind":"identifier","text":"SBUMessageInputModeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode\/title","value":"SBUMessageInputMode"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUMessageInputMode\/fragments","value":[{"kind":"identifier","text":"SBUMessageInputMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}