{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moderationsModule"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsModule","preciseIdentifier":"s:13SendbirdUIKit20SBUModerationsModuleC","text":"SBUModerationsModule"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsModule\/Header","preciseIdentifier":"s:13SendbirdUIKit20SBUModerationsModuleC6HeaderC","text":"Header"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":" "},{"kind":"internalParam","text":"leftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"component","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SBUModerationsModule.Header"},{"type":"text","text":" object"}]}]},{"name":"leftItem","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Selected "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbumoderationsviewcontroller\/moderationsmodule(_:didtapleftitem:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbumoderationsviewcontroller\/moderationsmodule(_:didtapleftitem:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController\/moderationsModule(_:didTapLeftItem:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" was selected."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moderationsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUModerationsModule","preciseIdentifier":"s:13SendbirdUIKit20SBUModerationsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit20SBUModerationsModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"title":"moderationsModule(_:didTapLeftItem:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUModerationsViewController(im)moderationsModule:didTapLeftItem:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"moderationsModule:didTapLeftItem:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUModerationsModule/Header":{"role":"symbol","title":"SBUModerationsModule.Header","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"codeVoice","code":"SBUModerationsModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsModule\/Header","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Header"}],"url":"\/documentation\/sendbirduikit\/sbumoderationsmodule\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUModerationsViewController":{"role":"symbol","title":"SBUModerationsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUModerationsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUModerationsViewController"}],"url":"\/documentation\/sendbirduikit\/sbumoderationsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/Header":{"role":"symbol","title":"Header","fragments":[{"kind":"identifier","text":"Header"}],"abstract":[{"type":"text","text":"A module component that represent the header of "},{"type":"text","text":"SBUMessageSearchModule"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit\/header"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUModerationsModule":{"role":"symbol","title":"SBUModerationsModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUModerationsModule"}],"abstract":[{"type":"text","text":"The class that represents the moderation module."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUModerationsModule"}],"url":"\/documentation\/sendbirduikit\/sbumoderationsmodule"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUModerationsViewController/moderationsModule(_:didTapLeftItem:)":{"role":"symbol","title":"moderationsModule(_:didTapLeftItem:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moderationsModule"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBUModerationsModule","preciseIdentifier":"s:13SendbirdUIKit20SBUModerationsModuleC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Header","preciseIdentifier":"s:13SendbirdUIKit20SBUModerationsModuleC6HeaderC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didTapLeftItem"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when "},{"type":"codeVoice","code":"leftBarButton"},{"type":"text","text":" was selected."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController\/moderationsModule(_:didTapLeftItem:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"moderationsModule:didTapLeftItem:"}],"url":"\/documentation\/sendbirduikit\/sbumoderationsviewcontroller\/moderationsmodule(_:didtapleftitem:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"moderationsModule:didTapLeftItem:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moderationsModule:didTapLeftItem:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"moderationsModule:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/Header","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)Header","text":"Header"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"headerComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTapLeftItem:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIBarButtonItem","preciseIdentifier":"c:objc(cs)UIBarButtonItem"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"leftItem"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController\/title","value":"SBUModerationsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController\/fragments","value":[{"kind":"identifier","text":"SBUModerationsViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController~1moderationsModule(_:didTapLeftItem:)\/title","value":"moderationsModule:didTapLeftItem:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController~1moderationsModule(_:didTapLeftItem:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moderationsModule:didTapLeftItem:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}