{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showBannedUserList"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbumoderationsviewcontroller\/showbanneduserlist()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbumoderationsviewcontroller\/showbanneduserlist()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController\/showBannedUserList()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is a function that shows the banned member List."},{"type":"text","text":" "},{"type":"text","text":"If you want to use a custom UserListViewController, override it and implement it."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showBannedUserList"},{"kind":"text","text":"()"}],"title":"showBannedUserList()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUModerationsViewController(im)showBannedUserList","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"showBannedUserList"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUModerationsViewController/showBannedUserList()":{"role":"symbol","title":"showBannedUserList()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showBannedUserList"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This is a function that shows the banned member List."},{"type":"text","text":" "},{"type":"text","text":"If you want to use a custom UserListViewController, override it and implement it."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController\/showBannedUserList()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showBannedUserList"}],"url":"\/documentation\/sendbirduikit\/sbumoderationsviewcontroller\/showbanneduserlist()"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUModerationsViewController":{"role":"symbol","title":"SBUModerationsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUModerationsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUModerationsViewController"}],"url":"\/documentation\/sendbirduikit\/sbumoderationsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showBannedUserList"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showBannedUserList"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showBannedUserList"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController~1showBannedUserList()\/title","value":"showBannedUserList"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController~1showBannedUserList()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showBannedUserList"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController\/title","value":"SBUModerationsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController\/fragments","value":[{"kind":"identifier","text":"SBUModerationsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}