{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbumoderationsviewcontroller\/viewwillappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbumoderationsviewcontroller\/viewwillappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController\/viewWillAppear(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"viewWillAppear(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUModerationsViewController(im)viewWillAppear:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUModerationsViewController/viewWillAppear(_:)":{"role":"symbol","title":"viewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController\/viewWillAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"url":"\/documentation\/sendbirduikit\/sbumoderationsviewcontroller\/viewwillappear(_:)"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUModerationsViewController":{"role":"symbol","title":"SBUModerationsViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUModerationsViewController"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUModerationsViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUModerationsViewController"}],"url":"\/documentation\/sendbirduikit\/sbumoderationsviewcontroller"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewWillAppear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController\/title","value":"SBUModerationsViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUModerationsViewController\/fragments","value":[{"kind":"identifier","text":"SBUModerationsViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}