{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AdminMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDAdminMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchanneladminmessagecell\/configure(_:hidedateview:isoverlay:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchanneladminmessagecell\/configure(_:hidedateview:isoverlay:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelAdminMessageCell\/configure(_:hideDateView:isOverlay:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AdminMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDAdminMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"configure(_:hideDateView:isOverlay:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelAdminMessageCell(im)configure:hideDateView:isOverlay:","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"configure:hideDateView:isOverlay:"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelAdminMessageCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelAdminMessageCell":{"role":"symbol","title":"SBUOpenChannelAdminMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelAdminMessageCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelAdminMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelAdminMessageCell"}],"url":"\/documentation\/sendbirduikit\/sbuopenchanneladminmessagecell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelAdminMessageCell/configure(_:hideDateView:isOverlay:)":{"role":"symbol","title":"configure(_:hideDateView:isOverlay:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"configure"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AdminMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDAdminMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hideDateView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isOverlay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelAdminMessageCell\/configure(_:hideDateView:isOverlay:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"configure:hideDateView:isOverlay:"}],"url":"\/documentation\/sendbirduikit\/sbuopenchanneladminmessagecell\/configure(_:hidedateview:isoverlay:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"configure:hideDateView:isOverlay:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configure:hideDateView:isOverlay:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"configure:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SBDAdminMessage","preciseIdentifier":"c:@M@SendbirdChatSDK@objc(cs)SBDAdminMessage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideDateView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"hideDateView"},{"kind":"text","text":" "},{"kind":"identifier","text":"isOverlay:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isOverlay"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelAdminMessageCell\/title","value":"SBUOpenChannelAdminMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelAdminMessageCell\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelAdminMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelAdminMessageCell~1configure(_:hideDateView:isOverlay:)\/title","value":"configure:hideDateView:isOverlay:"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelAdminMessageCell~1configure(_:hideDateView:isOverlay:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"configure:hideDateView:isOverlay:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}