{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView","text":"SBUStackView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelcell\/participantstackview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sendbirduikit\/sbuopenchannelcell\/participantstackview"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantStackView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A horizontal stack view to configure layouts of the "},{"type":"codeVoice","code":"participantIcon"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"participantCount"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"title":"participantStackView","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SendbirdUIKit@objc(cs)SBUOpenChannelCell(py)participantStackView","modules":[{"name":"SendbirdUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"participantStackView"}]},"hierarchy":{"paths":[["doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell"]]},"references":{"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell/participantStackView":{"role":"symbol","title":"participantStackView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participantStackView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView"}],"abstract":[{"type":"text","text":"A horizontal stack view to configure layouts of the "},{"type":"codeVoice","code":"participantIcon"},{"type":"text","text":" and the "},{"type":"codeVoice","code":"participantCount"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell\/participantStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"participantStackView"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell\/participantstackview"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit":{"role":"collection","title":"SendbirdUIKit","abstract":[{"type":"text","text":"Sendbird UIKit for iOS"}],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit","kind":"symbol","type":"topic","url":"\/documentation\/sendbirduikit"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUOpenChannelCell":{"role":"symbol","title":"SBUOpenChannelCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUOpenChannelCell"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUOpenChannelCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUOpenChannelCell"}],"url":"\/documentation\/sendbirduikit\/sbuopenchannelcell"},"doc://com.sendbird.uikit/documentation/SendbirdUIKit/SBUStackView":{"role":"symbol","title":"SBUStackView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SBUStackView"}],"abstract":[],"identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUStackView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SBUStackView"}],"url":"\/documentation\/sendbirduikit\/sbustackview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"participantStackView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"participantStackView"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.sendbird.uikit\/documentation\/SendbirdUIKit\/SBUStackView","preciseIdentifier":"c:@M@SendbirdUIKit@objc(cs)SBUStackView","text":"SBUStackView"},{"kind":"text","text":" * "},{"kind":"identifier","text":"participantStackView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1participantStackView\/title","value":"participantStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell~1participantStackView\/fragments","value":[{"kind":"identifier","text":"participantStackView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell\/title","value":"SBUOpenChannelCell"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUOpenChannelCell\/fragments","value":[{"kind":"identifier","text":"SBUOpenChannelCell"}]},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUStackView\/title","value":"SBUStackView"},{"op":"replace","path":"\/references\/doc:~1~1com.sendbird.uikit~1documentation~1SendbirdUIKit~1SBUStackView\/fragments","value":[{"kind":"identifier","text":"SBUStackView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}